from typing import List, Dict, Tuple, Set, Union, Literal, Optional, Any

from decimal import Decimal

from faker import Faker
import mimesis
from mimesis import Generic
import inspect
                
                
provider_return_types = {
    'aba' : str,
    'academic_degree' : str,
    'address' : str,
    'administrative_unit' : str,
    'alphabet' : list,
    'am_pm' : str,
    'android_platform_token' : str,
    'answer' : str,
    'ascii_company_email' : str,
    'ascii_email' : str,
    'ascii_free_email' : str,
    'ascii_safe_email' : str,
    'bank' : str,
    'bank_country' : str,
    'basic_phone_number' : str,
    'bban' : str,
    'binary' : bytes,
    'birthdate' : str,
    'blood_type' : str,
    'boolean' : str,
    'bothify' : str,
    'bs' : str,
    'building_number' : str,
    'calling_code' : str,
    'catch_phrase' : str,
    'century' : str,
    'chrome' : str,
    'city' : str,
    'city_prefix' : str,
    'city_suffix' : str,
    'color' : str,
    'color_hsl' : tuple,
    'color_hsv' : tuple,
    'color_name' : str,
    'color_rgb' : tuple,
    'color_rgb_float' : tuple,
    'company' : str,
    'company_email' : str,
    'company_suffix' : str,
    'company_type' : str,
    'continent' : str,
    'coordinate' : str,
    'coordinates' : dict,
    'country' : str,
    'country_calling_code' : str,
    'country_code' : str,
    'country_emoji_flag' : str,
    'credit_card_expire' : str,
    'credit_card_full' : str,
    'credit_card_number' : str,
    'credit_card_provider' : str,
    'credit_card_security_code' : str,
    'cryptocurrency' : tuple,
    'cryptocurrency_code' : str,
    'cryptocurrency_iso_code' : str,
    'cryptocurrency_name' : str,
    'cryptocurrency_symbol' : str,
    'csv' : str,
    'currency' : tuple,
    'currency_code' : str,
    'currency_iso_code' : str,
    'currency_name' : str,
    'currency_symbol' : str,
    'current_country' : str,
    'current_country_code' : str,
    'date' : str,
    'date_between' : str,
    'date_between_dates' : str,
    'date_object' : str,
    'date_of_birth' : str,
    'date_this_century' : str,
    'date_this_decade' : str,
    'date_this_month' : str,
    'date_this_year' : str,
    'date_time' : str,
    'date_time_ad' : str,
    'date_time_between' : str,
    'date_time_between_dates' : str,
    'date_time_this_century' : str,
    'date_time_this_decade' : str,
    'date_time_this_month' : str,
    'date_time_this_year' : str,
    'datetime' : str,
    'day_of_month' : str,
    'day_of_week' : str,
    'default_country' : str,
    'dga' : str,
    'dish' : str,
    'doi' : str,
    'domain_name' : str,
    'domain_word' : str,
    'drink' : str,
    'dsv' : str,
    'duration' : str,
    'ean' : str,
    'ean13' : str,
    'ean8' : str,
    'ein' : str,
    'email' : str,
    'emoji' : str,
    'federal_subject' : str,
    'file_extension' : str,
    'file_name' : str,
    'file_path' : str,
    'firefox' : str,
    'first_name' : str,
    'first_name_female' : str,
    'first_name_male' : str,
    'first_name_nonbinary' : str,
    'fixed_width' : str,
    'formatted_date' : str,
    'formatted_datetime' : str,
    'formatted_time' : str,
    'free_email' : str,
    'free_email_domain' : str,
    'fruit' : str,
    'full_name' : str,
    'future_date' : str,
    'future_datetime' : str,
    'gender' : str,
    'gender_code' : str,
    'gender_symbol' : str,
    'get_current_locale' : str,
    'get_providers' : list,
    'get_words_list' : list,
    'gmt_offset' : str,
    'height' : str,
    'hex_color' : str,
    'hexify' : str,
    'hostname' : str,
    'http_method' : str,
    'http_status_code' : str,
    'iana_id' : str,
    'iata_code' : str,
    'iban' : str,
    'icao_code' : str,
    'identifier' : str,
    'image_url' : str,
    'internet_explorer' : str,
    'invalid_ssn' : str,
    'ios_platform_token' : str,
    'ipv4' : str,
    'ipv4_network_class' : str,
    'ipv4_private' : str,
    'ipv4_public' : str,
    'ipv6' : str,
    'isbn10' : str,
    'isbn13' : str,
    'isd_code' : str,
    'iso8601' : str,
    'items' : list,
    'itin' : str,
    'job' : str,
    'job_female' : str,
    'job_male' : str,
    'json' : str,
    'json_bytes' : bytes,
    'language' : str,
    'language_code' : str,
    'language_name' : str,
    'last_name' : str,
    'last_name_female' : str,
    'last_name_male' : str,
    'last_name_nonbinary' : str,
    'latitude' : str,
    'latlng' : tuple,
    'level' : str,
    'lexify' : str,
    'license_plate' : str,
    'linux_platform_token' : str,
    'linux_processor' : str,
    'local_latlng' : tuple,
    'locale' : str,
    'localized_ean' : str,
    'localized_ean13' : str,
    'localized_ean8' : str,
    'location_on_land' : tuple,
    'longitude' : str,
    'mac_address' : str,
    'mac_platform_token' : str,
    'mac_processor' : str,
    'md5' : str,
    'military_apo' : str,
    'military_dpo' : str,
    'military_ship' : str,
    'military_state' : str,
    'mime_type' : str,
    'month' : str,
    'month_name' : str,
    'msisdn' : str,
    'name' : str,
    'name_female' : str,
    'name_male' : str,
    'name_nonbinary' : str,
    'nationality' : str,
    'nic_handle' : str,
    'nic_handles' : list,
    'null_boolean' : str,
    'numerify' : str,
    'occupation' : str,
    'opera' : str,
    'paragraph' : str,
    'paragraphs' : list,
    'passport_dates' : tuple,
    'passport_dob' : str,
    'passport_full' : str,
    'passport_gender' : str,
    'passport_number' : str,
    'passport_owner' : tuple,
    'password' : str,
    'past_date' : str,
    'past_datetime' : str,
    'periodicity' : str,
    'phone_number' : str,
    'political_views' : str,
    'port_number' : str,
    'postal_code' : str,
    'postalcode' : str,
    'postalcode_in_state' : str,
    'postalcode_plus4' : str,
    'postcode' : str,
    'postcode_in_state' : str,
    'prefecture' : str,
    'prefix' : str,
    'prefix_female' : str,
    'prefix_male' : str,
    'prefix_nonbinary' : str,
    'price' : str,
    'price_in_btc' : str,
    'pricetag' : str,
    'profile' : dict,
    'province' : str,
    'psv' : str,
    'pybool' : str,
    'pydecimal' : str,
    'pydict' : dict,
    'pyfloat' : str,
    'pyint' : str,
    'pyiterable' : list,
    'pylist' : list,
    'pyobject' : str,
    'pyset' : set,
    'pystr' : str,
    'pystr_format' : str,
    'pystruct' : tuple,
    'pytimezone' : str,
    'pytuple' : tuple,
    'quote' : str,
    'random_choices' : list,
    'random_digit' : str,
    'random_digit_above_two' : str,
    'random_digit_not_null' : str,
    'random_digit_not_null_or_empty' : str,
    'random_digit_or_empty' : str,
    'random_element' : str,
    'random_elements' : list,
    'random_int' : str,
    'random_letter' : str,
    'random_letters' : list,
    'random_lowercase_letter' : str,
    'random_number' : str,
    'random_sample' : list,
    'random_uppercase_letter' : str,
    'randomize_nb_elements' : str,
    'region' : str,
    'reseed' : str,
    'rgb_color' : tuple,
    'rgb_css_color' : str,
    'ripe_id' : str,
    'safari' : str,
    'safe_color_name' : str,
    'safe_domain_name' : str,
    'safe_email' : str,
    'safe_hex_color' : str,
    'sbn9' : str,
    'secondary_address' : str,
    'seed_instance' : str,
    'sentence' : str,
    'sentences' : list,
    'sex' : str,
    'sha1' : str,
    'sha256' : str,
    'simple_profile' : dict,
    'slug' : str,
    'spices' : str,
    'ssn' : str,
    'state' : str,
    'state_abbr' : str,
    'stock_exchange' : str,
    'stock_name' : str,
    'stock_ticker' : str,
    'street_address' : str,
    'street_name' : str,
    'street_number' : str,
    'street_suffix' : str,
    'suffix' : str,
    'suffix_female' : str,
    'suffix_male' : str,
    'suffix_nonbinary' : str,
    'surname' : str,
    'swift' : str,
    'swift11' : str,
    'swift8' : str,
    'tar' : bytes,
    'telephone' : str,
    'text' : str,
    'texts' : list,
    'time' : str,
    'time_delta' : str,
    'time_object' : str,
    'time_series' : str,
    'timestamp' : str,
    'timezone' : str,
    'title' : str,
    'tld' : str,
    'tsv' : str,
    'university' : str,
    'unix_device' : str,
    'unix_partition' : str,
    'unix_time' : str,
    'upc_a' : str,
    'upc_e' : str,
    'uri' : str,
    'uri_extension' : str,
    'uri_page' : str,
    'uri_path' : str,
    'url' : str,
    'user_agent' : str,
    'user_name' : str,
    'username' : str,
    'uuid4' : str,
    'vegetable' : str,
    'views_on' : str,
    'vin' : str,
    'week_date' : str,
    'weight' : str,
    'windows_platform_token' : str,
    'word' : str,
    'words' : list,
    'worldview' : str,
    'year' : str,
    'zip' : bytes,
    'zip_code' : str,
    'zipcode' : str,
    'zipcode_in_state' : str,
    'zipcode_plus4' : str,
}
provider_methods = {
    'faker' : {
        'word_list': ['linux_processor', 'uri_extension', 'first_name_male', 'latlng', 'time', 'csv', 'mime_type', 'ripe_id', 'state_abbr', 'http_method', 'boolean', 'postalcode_in_state', 'prefix_female', 'swift', 'seed_instance', 'upc_e', 'date_time_this_year', 'bank_country', 'isbn13', 'military_ship', 'pylist', 'swift11', 'md5', 'psv', 'century', 'swift8', 'last_name_nonbinary', 'language_code', 'randomize_nb_elements', 'time_object', 'msisdn', 'name_female', 'unix_partition', 'cryptocurrency_name', 'postalcode', 'date_this_month', 'pyiterable', 'safari', 'currency_code', 'vin', 'enum', 'json_bytes', 'country_code', 'sbn9', 'street_address', 'ascii_email', 'slug', 'localized_ean', 'random_element', 'date_object', 'ios_platform_token', 'pytimezone', 'year', 'bs', 'color', 'ipv6', 'safe_email', 'country_calling_code', 'date_of_birth', 'administrative_unit', 'json', 'suffix_female', 'date_time_ad', 'localized_ean13', 'date_this_decade', 'zipcode', 'http_status_code', 'ein', 'cryptocurrency', 'time_series', 'ssn', 'mac_address', 'name_male', 'credit_card_provider', 'day_of_week', 'first_name_female', 'pystr_format', 'aba', 'date_this_century', 'domain_name', 'country', 'iban', 'provider', 'safe_hex_color', 'user_name', 'current_country_code', 'isbn10', 'unix_device', 'date_time', 'credit_card_expire', 'state', 'timezone', 'xml', 'currency_symbol', 'credit_card_security_code', 'color_hsv', 'prefix', 'pyfloat', 'emoji', 'first_name_nonbinary', 'random_letters', 'pystr', 'zipcode_plus4', 'am_pm', 'android_platform_token', 'city_prefix', 'latitude', 'localized_ean8', 'basic_phone_number', 'word', 'local_latlng', 'free_email_domain', 'random_int', 'city_suffix', 'dsv', 'sha1', 'date_time_this_decade', 'format', 'past_date', 'language_name', 'military_apo', 'military_dpo', 'postalcode_plus4', 'pybool', 'suffix_male', 'linux_platform_token', 'unix_time', 'bothify', 'uri', 'del_arguments', 'last_name', 'sentence', 'password', 'domain_word', 'coordinate', 'street_suffix', 'get_providers', 'date_time_this_century', 'company_suffix', 'nic_handle', 'texts', 'date_time_this_month', 'company', 'currency', 'rgb_css_color', 'postcode_in_state', 'ascii_company_email', 'image', 'upc_a', 'file_name', 'city', 'hostname', 'pydecimal', 'pyset', 'image_url', 'random_letter', 'url', 'dga', 'parse', 'passport_dob', 'seed_locale', 'file_extension', 'military_state', 'date', 'past_datetime', 'suffix_nonbinary', 'random_digit_or_empty', 'last_name_male', 'random_digit', 'day_of_month', 'cryptocurrency_code', 'bban', 'color_name', 'ean13', 'get_arguments', 'month_name', 'ipv4_public', 'name_nonbinary', 'numerify', 'ascii_safe_email', 'simple_profile', 'get_words_list', 'iana_id', 'job_male', 'prefix_nonbinary', 'suffix', 'user_agent', 'itin', 'random_elements', 'passport_dates', 'future_datetime', 'random_uppercase_letter', 'street_name', 'hexify', 'port_number', 'pydict', 'zip', 'paragraphs', 'passport_owner', 'firefox', 'ipv4', 'location_on_land', 'null_boolean', 'building_number', 'postcode', 'credit_card_number', 'prefix_male', 'passport_full', 'uuid4', 'hex_color', 'catch_phrase', 'binary', 'job_female', 'zipcode_in_state', 'random_digit_not_null', 'future_date', 'ipv4_private', 'email', 'iso8601', 'passport_gender', 'pyobject', 'pytuple', 'fixed_width', 'set_formatter', 'tar', 'file_path', 'profile', 'safe_color_name', 'license_plate', 'sha256', 'random_digit_not_null_or_empty', 'name', 'random_lowercase_letter', 'free_email', 'rgb_color', 'windows_platform_token', 'uri_path', 'safe_domain_name', 'date_between_dates', 'lexify', 'doi', 'phone_number', 'color_hsl', 'random_number', 'items', 'set_arguments', 'pyint', 'words', 'random_choices', 'time_delta', 'first_name', 'opera', 'mac_platform_token', 'tsv', 'month', 'uri_page', 'date_this_year', 'passport_number', 'company_email', 'longitude', 'ean8', 'address', 'get_formatter', 'last_name_female', 'invalid_ssn', 'date_time_between_dates', 'text', 'date_between', 'pricetag', 'color_rgb', 'pystruct', 'date_time_between', 'ean', 'chrome', 'add_provider', 'current_country', 'paragraph', 'random_digit_above_two', 'color_rgb_float', 'currency_name', 'internet_explorer', 'ascii_free_email', 'mac_processor', 'sentences', 'job', 'tld', 'credit_card_full', 'secondary_address', 'random_sample', 'locale', 'ipv4_network_class', 'nic_handles'],
        'word_tokens': {'linux_processor': ['linux', 'processor'], 'uri_extension': ['uri', 'extension'], 'first_name_male': ['first', 'name', 'male'], 'latlng': ['latlng'], 'time': ['time'], 'csv': ['csv'], 'mime_type': ['mime', 'type'], 'ripe_id': ['ripe', 'id'], 'state_abbr': ['state', 'abbr'], 'http_method': ['http', 'method'], 'boolean': ['boolean'], 'postalcode_in_state': ['postalcode', 'in', 'state'], 'prefix_female': ['prefix', 'female'], 'swift': ['swift'], 'seed_instance': ['seed', 'instance'], 'upc_e': ['upc', 'e'], 'date_time_this_year': ['date', 'time', 'this', 'year'], 'bank_country': ['bank', 'country'], 'isbn13': ['isbn13'], 'military_ship': ['military', 'ship'], 'pylist': ['pylist'], 'swift11': ['swift11'], 'md5': ['md5'], 'psv': ['psv'], 'century': ['century'], 'swift8': ['swift8'], 'last_name_nonbinary': ['last', 'name', 'nonbinary'], 'language_code': ['language', 'code'], 'randomize_nb_elements': ['randomize', 'nb', 'elements'], 'time_object': ['time', 'object'], 'msisdn': ['msisdn'], 'name_female': ['name', 'female'], 'unix_partition': ['unix', 'partition'], 'cryptocurrency_name': ['cryptocurrency', 'name'], 'postalcode': ['postalcode'], 'date_this_month': ['date', 'this', 'month'], 'pyiterable': ['pyiterable'], 'safari': ['safari'], 'currency_code': ['currency', 'code'], 'vin': ['vin'], 'enum': ['enum'], 'json_bytes': ['json', 'bytes'], 'country_code': ['country', 'code'], 'sbn9': ['sbn9'], 'street_address': ['street', 'address'], 'ascii_email': ['ascii', 'email'], 'slug': ['slug'], 'localized_ean': ['localized', 'ean'], 'random_element': ['random', 'element'], 'date_object': ['date', 'object'], 'ios_platform_token': ['ios', 'platform', 'token'], 'pytimezone': ['pytimezone'], 'year': ['year'], 'bs': ['bs'], 'color': ['color'], 'ipv6': ['ipv6'], 'safe_email': ['safe', 'email'], 'country_calling_code': ['country', 'calling', 'code'], 'date_of_birth': ['date', 'of', 'birth'], 'administrative_unit': ['administrative', 'unit'], 'json': ['json'], 'suffix_female': ['suffix', 'female'], 'date_time_ad': ['date', 'time', 'ad'], 'localized_ean13': ['localized', 'ean13'], 'date_this_decade': ['date', 'this', 'decade'], 'zipcode': ['zipcode'], 'http_status_code': ['http', 'status', 'code'], 'ein': ['ein'], 'cryptocurrency': ['cryptocurrency'], 'time_series': ['time', 'series'], 'ssn': ['ssn'], 'mac_address': ['mac', 'address'], 'name_male': ['name', 'male'], 'credit_card_provider': ['credit', 'card', 'provider'], 'day_of_week': ['day', 'of', 'week'], 'first_name_female': ['first', 'name', 'female'], 'pystr_format': ['pystr', 'format'], 'aba': ['aba'], 'date_this_century': ['date', 'this', 'century'], 'domain_name': ['domain', 'name'], 'country': ['country'], 'iban': ['iban'], 'provider': ['provider'], 'safe_hex_color': ['safe', 'hex', 'color'], 'user_name': ['user', 'name'], 'current_country_code': ['current', 'country', 'code'], 'isbn10': ['isbn10'], 'unix_device': ['unix', 'device'], 'date_time': ['date', 'time'], 'credit_card_expire': ['credit', 'card', 'expire'], 'state': ['state'], 'timezone': ['timezone'], 'xml': ['xml'], 'currency_symbol': ['currency', 'symbol'], 'credit_card_security_code': ['credit', 'card', 'security', 'code'], 'color_hsv': ['color', 'hsv'], 'prefix': ['prefix'], 'pyfloat': ['pyfloat'], 'emoji': ['emoji'], 'first_name_nonbinary': ['first', 'name', 'nonbinary'], 'random_letters': ['random', 'letters'], 'pystr': ['pystr'], 'zipcode_plus4': ['zipcode', 'plus4'], 'am_pm': ['am', 'pm'], 'android_platform_token': ['android', 'platform', 'token'], 'city_prefix': ['city', 'prefix'], 'latitude': ['latitude'], 'localized_ean8': ['localized', 'ean8'], 'basic_phone_number': ['basic', 'phone', 'number'], 'word': ['word'], 'local_latlng': ['local', 'latlng'], 'free_email_domain': ['free', 'email', 'domain'], 'random_int': ['random', 'int'], 'city_suffix': ['city', 'suffix'], 'dsv': ['dsv'], 'sha1': ['sha1'], 'date_time_this_decade': ['date', 'time', 'this', 'decade'], 'format': ['format'], 'past_date': ['past', 'date'], 'language_name': ['language', 'name'], 'military_apo': ['military', 'apo'], 'military_dpo': ['military', 'dpo'], 'postalcode_plus4': ['postalcode', 'plus4'], 'pybool': ['pybool'], 'suffix_male': ['suffix', 'male'], 'linux_platform_token': ['linux', 'platform', 'token'], 'unix_time': ['unix', 'time'], 'bothify': ['bothify'], 'uri': ['uri'], 'del_arguments': ['del', 'arguments'], 'last_name': ['last', 'name'], 'sentence': ['sentence'], 'password': ['password'], 'domain_word': ['domain', 'word'], 'coordinate': ['coordinate'], 'street_suffix': ['street', 'suffix'], 'get_providers': ['get', 'providers'], 'date_time_this_century': ['date', 'time', 'this', 'century'], 'company_suffix': ['company', 'suffix'], 'nic_handle': ['nic', 'handle'], 'texts': ['texts'], 'date_time_this_month': ['date', 'time', 'this', 'month'], 'company': ['company'], 'currency': ['currency'], 'rgb_css_color': ['rgb', 'css', 'color'], 'postcode_in_state': ['postcode', 'in', 'state'], 'ascii_company_email': ['ascii', 'company', 'email'], 'image': ['image'], 'upc_a': ['upc', 'a'], 'file_name': ['file', 'name'], 'city': ['city'], 'hostname': ['hostname'], 'pydecimal': ['pydecimal'], 'pyset': ['pyset'], 'image_url': ['image', 'url'], 'random_letter': ['random', 'letter'], 'url': ['url'], 'dga': ['dga'], 'parse': ['parse'], 'passport_dob': ['passport', 'dob'], 'seed_locale': ['seed', 'locale'], 'file_extension': ['file', 'extension'], 'military_state': ['military', 'state'], 'date': ['date'], 'past_datetime': ['past', 'datetime'], 'suffix_nonbinary': ['suffix', 'nonbinary'], 'random_digit_or_empty': ['random', 'digit', 'or', 'empty'], 'last_name_male': ['last', 'name', 'male'], 'random_digit': ['random', 'digit'], 'day_of_month': ['day', 'of', 'month'], 'cryptocurrency_code': ['cryptocurrency', 'code'], 'bban': ['bban'], 'color_name': ['color', 'name'], 'ean13': ['ean13'], 'get_arguments': ['get', 'arguments'], 'month_name': ['month', 'name'], 'ipv4_public': ['ipv4', 'public'], 'name_nonbinary': ['name', 'nonbinary'], 'numerify': ['numerify'], 'ascii_safe_email': ['ascii', 'safe', 'email'], 'simple_profile': ['simple', 'profile'], 'get_words_list': ['get', 'words', 'list'], 'iana_id': ['iana', 'id'], 'job_male': ['job', 'male'], 'prefix_nonbinary': ['prefix', 'nonbinary'], 'suffix': ['suffix'], 'user_agent': ['user', 'agent'], 'itin': ['itin'], 'random_elements': ['random', 'elements'], 'passport_dates': ['passport', 'dates'], 'future_datetime': ['future', 'datetime'], 'random_uppercase_letter': ['random', 'uppercase', 'letter'], 'street_name': ['street', 'name'], 'hexify': ['hexify'], 'port_number': ['port', 'number'], 'pydict': ['pydict'], 'zip': ['zip'], 'paragraphs': ['paragraphs'], 'passport_owner': ['passport', 'owner'], 'firefox': ['firefox'], 'ipv4': ['ipv4'], 'location_on_land': ['location', 'on', 'land'], 'null_boolean': ['null', 'boolean'], 'building_number': ['building', 'number'], 'postcode': ['postcode'], 'credit_card_number': ['credit', 'card', 'number'], 'prefix_male': ['prefix', 'male'], 'passport_full': ['passport', 'full'], 'uuid4': ['uuid4'], 'hex_color': ['hex', 'color'], 'catch_phrase': ['catch', 'phrase'], 'binary': ['binary'], 'job_female': ['job', 'female'], 'zipcode_in_state': ['zipcode', 'in', 'state'], 'random_digit_not_null': ['random', 'digit', 'not', 'null'], 'future_date': ['future', 'date'], 'ipv4_private': ['ipv4', 'private'], 'email': ['email'], 'iso8601': ['iso8601'], 'passport_gender': ['passport', 'gender'], 'pyobject': ['pyobject'], 'pytuple': ['pytuple'], 'fixed_width': ['fixed', 'width'], 'set_formatter': ['set', 'formatter'], 'tar': ['tar'], 'file_path': ['file', 'path'], 'profile': ['profile'], 'safe_color_name': ['safe', 'color', 'name'], 'license_plate': ['license', 'plate'], 'sha256': ['sha256'], 'random_digit_not_null_or_empty': ['random', 'digit', 'not', 'null', 'or', 'empty'], 'name': ['name'], 'random_lowercase_letter': ['random', 'lowercase', 'letter'], 'free_email': ['free', 'email'], 'rgb_color': ['rgb', 'color'], 'windows_platform_token': ['windows', 'platform', 'token'], 'uri_path': ['uri', 'path'], 'safe_domain_name': ['safe', 'domain', 'name'], 'date_between_dates': ['date', 'between', 'dates'], 'lexify': ['lexify'], 'doi': ['doi'], 'phone_number': ['phone', 'number'], 'color_hsl': ['color', 'hsl'], 'random_number': ['random', 'number'], 'items': ['items'], 'set_arguments': ['set', 'arguments'], 'pyint': ['pyint'], 'words': ['words'], 'random_choices': ['random', 'choices'], 'time_delta': ['time', 'delta'], 'first_name': ['first', 'name'], 'opera': ['opera'], 'mac_platform_token': ['mac', 'platform', 'token'], 'tsv': ['tsv'], 'month': ['month'], 'uri_page': ['uri', 'page'], 'date_this_year': ['date', 'this', 'year'], 'passport_number': ['passport', 'number'], 'company_email': ['company', 'email'], 'longitude': ['longitude'], 'ean8': ['ean8'], 'address': ['address'], 'get_formatter': ['get', 'formatter'], 'last_name_female': ['last', 'name', 'female'], 'invalid_ssn': ['invalid', 'ssn'], 'date_time_between_dates': ['date', 'time', 'between', 'dates'], 'text': ['text'], 'date_between': ['date', 'between'], 'pricetag': ['pricetag'], 'color_rgb': ['color', 'rgb'], 'pystruct': ['pystruct'], 'date_time_between': ['date', 'time', 'between'], 'ean': ['ean'], 'chrome': ['chrome'], 'add_provider': ['add', 'provider'], 'current_country': ['current', 'country'], 'paragraph': ['paragraph'], 'random_digit_above_two': ['random', 'digit', 'above', 'two'], 'color_rgb_float': ['color', 'rgb', 'float'], 'currency_name': ['currency', 'name'], 'internet_explorer': ['internet', 'explorer'], 'ascii_free_email': ['ascii', 'free', 'email'], 'mac_processor': ['mac', 'processor'], 'sentences': ['sentences'], 'job': ['job'], 'tld': ['tld'], 'credit_card_full': ['credit', 'card', 'full'], 'secondary_address': ['secondary', 'address'], 'random_sample': ['random', 'sample'], 'locale': ['locale'], 'ipv4_network_class': ['ipv4', 'network', 'class'], 'nic_handles': ['nic', 'handles']},
        'word_tokens_set': {'linux_processor': {'processor', 'linux'}, 'uri_extension': {'extension', 'uri'}, 'first_name_male': {'male', 'name', 'first'}, 'latlng': {'latlng'}, 'time': {'time'}, 'csv': {'csv'}, 'mime_type': {'mime', 'type'}, 'ripe_id': {'id', 'ripe'}, 'state_abbr': {'state', 'abbr'}, 'http_method': {'method', 'http'}, 'boolean': {'boolean'}, 'postalcode_in_state': {'postalcode', 'state', 'in'}, 'prefix_female': {'prefix', 'female'}, 'swift': {'swift'}, 'seed_instance': {'instance', 'seed'}, 'upc_e': {'upc', 'e'}, 'date_time_this_year': {'year', 'date', 'this', 'time'}, 'bank_country': {'country', 'bank'}, 'isbn13': {'isbn13'}, 'military_ship': {'military', 'ship'}, 'pylist': {'pylist'}, 'swift11': {'swift11'}, 'md5': {'md5'}, 'psv': {'psv'}, 'century': {'century'}, 'swift8': {'swift8'}, 'last_name_nonbinary': {'last', 'nonbinary', 'name'}, 'language_code': {'language', 'code'}, 'randomize_nb_elements': {'randomize', 'elements', 'nb'}, 'time_object': {'object', 'time'}, 'msisdn': {'msisdn'}, 'name_female': {'female', 'name'}, 'unix_partition': {'partition', 'unix'}, 'cryptocurrency_name': {'name', 'cryptocurrency'}, 'postalcode': {'postalcode'}, 'date_this_month': {'month', 'date', 'this'}, 'pyiterable': {'pyiterable'}, 'safari': {'safari'}, 'currency_code': {'currency', 'code'}, 'vin': {'vin'}, 'enum': {'enum'}, 'json_bytes': {'json', 'bytes'}, 'country_code': {'country', 'code'}, 'sbn9': {'sbn9'}, 'street_address': {'address', 'street'}, 'ascii_email': {'ascii', 'email'}, 'slug': {'slug'}, 'localized_ean': {'localized', 'ean'}, 'random_element': {'random', 'element'}, 'date_object': {'object', 'date'}, 'ios_platform_token': {'platform', 'ios', 'token'}, 'pytimezone': {'pytimezone'}, 'year': {'year'}, 'bs': {'bs'}, 'color': {'color'}, 'ipv6': {'ipv6'}, 'safe_email': {'email', 'safe'}, 'country_calling_code': {'country', 'calling', 'code'}, 'date_of_birth': {'birth', 'date', 'of'}, 'administrative_unit': {'administrative', 'unit'}, 'json': {'json'}, 'suffix_female': {'female', 'suffix'}, 'date_time_ad': {'ad', 'date', 'time'}, 'localized_ean13': {'localized', 'ean13'}, 'date_this_decade': {'decade', 'date', 'this'}, 'zipcode': {'zipcode'}, 'http_status_code': {'http', 'code', 'status'}, 'ein': {'ein'}, 'cryptocurrency': {'cryptocurrency'}, 'time_series': {'series', 'time'}, 'ssn': {'ssn'}, 'mac_address': {'address', 'mac'}, 'name_male': {'name', 'male'}, 'credit_card_provider': {'provider', 'card', 'credit'}, 'day_of_week': {'of', 'day', 'week'}, 'first_name_female': {'female', 'name', 'first'}, 'pystr_format': {'pystr', 'format'}, 'aba': {'aba'}, 'date_this_century': {'century', 'date', 'this'}, 'domain_name': {'domain', 'name'}, 'country': {'country'}, 'iban': {'iban'}, 'provider': {'provider'}, 'safe_hex_color': {'color', 'safe', 'hex'}, 'user_name': {'user', 'name'}, 'current_country_code': {'country', 'current', 'code'}, 'isbn10': {'isbn10'}, 'unix_device': {'unix', 'device'}, 'date_time': {'date', 'time'}, 'credit_card_expire': {'expire', 'card', 'credit'}, 'state': {'state'}, 'timezone': {'timezone'}, 'xml': {'xml'}, 'currency_symbol': {'currency', 'symbol'}, 'credit_card_security_code': {'security', 'code', 'card', 'credit'}, 'color_hsv': {'hsv', 'color'}, 'prefix': {'prefix'}, 'pyfloat': {'pyfloat'}, 'emoji': {'emoji'}, 'first_name_nonbinary': {'nonbinary', 'name', 'first'}, 'random_letters': {'random', 'letters'}, 'pystr': {'pystr'}, 'zipcode_plus4': {'plus4', 'zipcode'}, 'am_pm': {'am', 'pm'}, 'android_platform_token': {'platform', 'android', 'token'}, 'city_prefix': {'prefix', 'city'}, 'latitude': {'latitude'}, 'localized_ean8': {'localized', 'ean8'}, 'basic_phone_number': {'phone', 'number', 'basic'}, 'word': {'word'}, 'local_latlng': {'local', 'latlng'}, 'free_email_domain': {'domain', 'email', 'free'}, 'random_int': {'random', 'int'}, 'city_suffix': {'city', 'suffix'}, 'dsv': {'dsv'}, 'sha1': {'sha1'}, 'date_time_this_decade': {'decade', 'date', 'this', 'time'}, 'format': {'format'}, 'past_date': {'date', 'past'}, 'language_name': {'language', 'name'}, 'military_apo': {'military', 'apo'}, 'military_dpo': {'military', 'dpo'}, 'postalcode_plus4': {'postalcode', 'plus4'}, 'pybool': {'pybool'}, 'suffix_male': {'suffix', 'male'}, 'linux_platform_token': {'platform', 'linux', 'token'}, 'unix_time': {'unix', 'time'}, 'bothify': {'bothify'}, 'uri': {'uri'}, 'del_arguments': {'del', 'arguments'}, 'last_name': {'last', 'name'}, 'sentence': {'sentence'}, 'password': {'password'}, 'domain_word': {'word', 'domain'}, 'coordinate': {'coordinate'}, 'street_suffix': {'street', 'suffix'}, 'get_providers': {'providers', 'get'}, 'date_time_this_century': {'century', 'date', 'this', 'time'}, 'company_suffix': {'company', 'suffix'}, 'nic_handle': {'nic', 'handle'}, 'texts': {'texts'}, 'date_time_this_month': {'month', 'date', 'this', 'time'}, 'company': {'company'}, 'currency': {'currency'}, 'rgb_css_color': {'color', 'css', 'rgb'}, 'postcode_in_state': {'state', 'in', 'postcode'}, 'ascii_company_email': {'company', 'ascii', 'email'}, 'image': {'image'}, 'upc_a': {'a', 'upc'}, 'file_name': {'file', 'name'}, 'city': {'city'}, 'hostname': {'hostname'}, 'pydecimal': {'pydecimal'}, 'pyset': {'pyset'}, 'image_url': {'url', 'image'}, 'random_letter': {'random', 'letter'}, 'url': {'url'}, 'dga': {'dga'}, 'parse': {'parse'}, 'passport_dob': {'dob', 'passport'}, 'seed_locale': {'locale', 'seed'}, 'file_extension': {'file', 'extension'}, 'military_state': {'military', 'state'}, 'date': {'date'}, 'past_datetime': {'datetime', 'past'}, 'suffix_nonbinary': {'suffix', 'nonbinary'}, 'random_digit_or_empty': {'random', 'digit', 'or', 'empty'}, 'last_name_male': {'last', 'name', 'male'}, 'random_digit': {'random', 'digit'}, 'day_of_month': {'month', 'of', 'day'}, 'cryptocurrency_code': {'code', 'cryptocurrency'}, 'bban': {'bban'}, 'color_name': {'color', 'name'}, 'ean13': {'ean13'}, 'get_arguments': {'arguments', 'get'}, 'month_name': {'month', 'name'}, 'ipv4_public': {'public', 'ipv4'}, 'name_nonbinary': {'nonbinary', 'name'}, 'numerify': {'numerify'}, 'ascii_safe_email': {'email', 'ascii', 'safe'}, 'simple_profile': {'profile', 'simple'}, 'get_words_list': {'list', 'words', 'get'}, 'iana_id': {'id', 'iana'}, 'job_male': {'job', 'male'}, 'prefix_nonbinary': {'prefix', 'nonbinary'}, 'suffix': {'suffix'}, 'user_agent': {'agent', 'user'}, 'itin': {'itin'}, 'random_elements': {'random', 'elements'}, 'passport_dates': {'passport', 'dates'}, 'future_datetime': {'future', 'datetime'}, 'random_uppercase_letter': {'uppercase', 'random', 'letter'}, 'street_name': {'street', 'name'}, 'hexify': {'hexify'}, 'port_number': {'number', 'port'}, 'pydict': {'pydict'}, 'zip': {'zip'}, 'paragraphs': {'paragraphs'}, 'passport_owner': {'owner', 'passport'}, 'firefox': {'firefox'}, 'ipv4': {'ipv4'}, 'location_on_land': {'location', 'land', 'on'}, 'null_boolean': {'boolean', 'null'}, 'building_number': {'number', 'building'}, 'postcode': {'postcode'}, 'credit_card_number': {'number', 'card', 'credit'}, 'prefix_male': {'prefix', 'male'}, 'passport_full': {'passport', 'full'}, 'uuid4': {'uuid4'}, 'hex_color': {'color', 'hex'}, 'catch_phrase': {'catch', 'phrase'}, 'binary': {'binary'}, 'job_female': {'female', 'job'}, 'zipcode_in_state': {'state', 'in', 'zipcode'}, 'random_digit_not_null': {'random', 'digit', 'null', 'not'}, 'future_date': {'future', 'date'}, 'ipv4_private': {'private', 'ipv4'}, 'email': {'email'}, 'iso8601': {'iso8601'}, 'passport_gender': {'passport', 'gender'}, 'pyobject': {'pyobject'}, 'pytuple': {'pytuple'}, 'fixed_width': {'width', 'fixed'}, 'set_formatter': {'formatter', 'set'}, 'tar': {'tar'}, 'file_path': {'path', 'file'}, 'profile': {'profile'}, 'safe_color_name': {'name', 'color', 'safe'}, 'license_plate': {'license', 'plate'}, 'sha256': {'sha256'}, 'random_digit_not_null_or_empty': {'not', 'or', 'digit', 'empty', 'null', 'random'}, 'name': {'name'}, 'random_lowercase_letter': {'lowercase', 'random', 'letter'}, 'free_email': {'email', 'free'}, 'rgb_color': {'color', 'rgb'}, 'windows_platform_token': {'windows', 'platform', 'token'}, 'uri_path': {'path', 'uri'}, 'safe_domain_name': {'domain', 'name', 'safe'}, 'date_between_dates': {'date', 'dates', 'between'}, 'lexify': {'lexify'}, 'doi': {'doi'}, 'phone_number': {'phone', 'number'}, 'color_hsl': {'hsl', 'color'}, 'random_number': {'random', 'number'}, 'items': {'items'}, 'set_arguments': {'arguments', 'set'}, 'pyint': {'pyint'}, 'words': {'words'}, 'random_choices': {'random', 'choices'}, 'time_delta': {'delta', 'time'}, 'first_name': {'name', 'first'}, 'opera': {'opera'}, 'mac_platform_token': {'token', 'platform', 'mac'}, 'tsv': {'tsv'}, 'month': {'month'}, 'uri_page': {'page', 'uri'}, 'date_this_year': {'year', 'date', 'this'}, 'passport_number': {'number', 'passport'}, 'company_email': {'company', 'email'}, 'longitude': {'longitude'}, 'ean8': {'ean8'}, 'address': {'address'}, 'get_formatter': {'formatter', 'get'}, 'last_name_female': {'last', 'female', 'name'}, 'invalid_ssn': {'ssn', 'invalid'}, 'date_time_between_dates': {'date', 'dates', 'between', 'time'}, 'text': {'text'}, 'date_between': {'date', 'between'}, 'pricetag': {'pricetag'}, 'color_rgb': {'color', 'rgb'}, 'pystruct': {'pystruct'}, 'date_time_between': {'date', 'between', 'time'}, 'ean': {'ean'}, 'chrome': {'chrome'}, 'add_provider': {'provider', 'add'}, 'current_country': {'country', 'current'}, 'paragraph': {'paragraph'}, 'random_digit_above_two': {'random', 'two', 'digit', 'above'}, 'color_rgb_float': {'color', 'rgb', 'float'}, 'currency_name': {'currency', 'name'}, 'internet_explorer': {'explorer', 'internet'}, 'ascii_free_email': {'ascii', 'email', 'free'}, 'mac_processor': {'processor', 'mac'}, 'sentences': {'sentences'}, 'job': {'job'}, 'tld': {'tld'}, 'credit_card_full': {'full', 'card', 'credit'}, 'secondary_address': {'address', 'secondary'}, 'random_sample': {'random', 'sample'}, 'locale': {'locale'}, 'ipv4_network_class': {'class', 'network', 'ipv4'}, 'nic_handles': {'handles', 'nic'}}
    },
    'mimesis' : {
        'word_list': ['time', 'company_type', 'iata_code', 'century', 'answer', 'university', 'full_name', 'price_in_btc', 'username', 'country_code', 'default_country', 'political_views', 'timestamp', 'year', 'color', 'update_dataset', 'override_locale', 'stock_exchange', 'gender_symbol', 'isd_code', 'prefecture', 'postal_code', 'day_of_week', 'title', 'academic_degree', 'country', 'language', 'views_on', 'bank', 'surname', 'datetime', 'state', 'cryptocurrency_symbol', 'timezone', 'coordinates', 'currency_symbol', 'emoji', 'stock_ticker', 'formatted_date', 'cryptocurrency_iso_code', 'latitude', 'word', 'dish', 'quote', 'weight', 'last_name', 'sentence', 'icao_code', 'password', 'reseed', 'street_suffix', 'currency_iso_code', 'formatted_datetime', 'company', 'country_emoji_flag', 'week_date', 'occupation', 'level', 'city', 'spices', 'date', 'price', 'day_of_month', 'nationality', 'gmt_offset', 'gender_code', 'drink', 'street_name', 'province', 'formatted_time', 'hex_color', 'email', 'gender', 'periodicity', 'name', 'vegetable', 'sex', 'rgb_color', 'phone_number', 'region', 'identifier', 'zip_code', 'words', 'birthdate', 'first_name', 'height', 'month', 'longitude', 'street_number', 'address', 'worldview', 'text', 'telephone', 'calling_code', 'get_current_locale', 'stock_name', 'validate_enum', 'federal_subject', 'fruit', 'duration', 'blood_type', 'bulk_create_datetimes', 'alphabet', 'continent'],
        'word_tokens': {'time': ['time'], 'company_type': ['company', 'type'], 'iata_code': ['iata', 'code'], 'century': ['century'], 'answer': ['answer'], 'university': ['university'], 'full_name': ['full', 'name'], 'price_in_btc': ['price', 'in', 'btc'], 'username': ['username'], 'country_code': ['country', 'code'], 'default_country': ['default', 'country'], 'political_views': ['political', 'views'], 'timestamp': ['timestamp'], 'year': ['year'], 'color': ['color'], 'update_dataset': ['update', 'dataset'], 'override_locale': ['override', 'locale'], 'stock_exchange': ['stock', 'exchange'], 'gender_symbol': ['gender', 'symbol'], 'isd_code': ['isd', 'code'], 'prefecture': ['prefecture'], 'postal_code': ['postal', 'code'], 'day_of_week': ['day', 'of', 'week'], 'title': ['title'], 'academic_degree': ['academic', 'degree'], 'country': ['country'], 'language': ['language'], 'views_on': ['views', 'on'], 'bank': ['bank'], 'surname': ['surname'], 'datetime': ['datetime'], 'state': ['state'], 'cryptocurrency_symbol': ['cryptocurrency', 'symbol'], 'timezone': ['timezone'], 'coordinates': ['coordinates'], 'currency_symbol': ['currency', 'symbol'], 'emoji': ['emoji'], 'stock_ticker': ['stock', 'ticker'], 'formatted_date': ['formatted', 'date'], 'cryptocurrency_iso_code': ['cryptocurrency', 'iso', 'code'], 'latitude': ['latitude'], 'word': ['word'], 'dish': ['dish'], 'quote': ['quote'], 'weight': ['weight'], 'last_name': ['last', 'name'], 'sentence': ['sentence'], 'icao_code': ['icao', 'code'], 'password': ['password'], 'reseed': ['reseed'], 'street_suffix': ['street', 'suffix'], 'currency_iso_code': ['currency', 'iso', 'code'], 'formatted_datetime': ['formatted', 'datetime'], 'company': ['company'], 'country_emoji_flag': ['country', 'emoji', 'flag'], 'week_date': ['week', 'date'], 'occupation': ['occupation'], 'level': ['level'], 'city': ['city'], 'spices': ['spices'], 'date': ['date'], 'price': ['price'], 'day_of_month': ['day', 'of', 'month'], 'nationality': ['nationality'], 'gmt_offset': ['gmt', 'offset'], 'gender_code': ['gender', 'code'], 'drink': ['drink'], 'street_name': ['street', 'name'], 'province': ['province'], 'formatted_time': ['formatted', 'time'], 'hex_color': ['hex', 'color'], 'email': ['email'], 'gender': ['gender'], 'periodicity': ['periodicity'], 'name': ['name'], 'vegetable': ['vegetable'], 'sex': ['sex'], 'rgb_color': ['rgb', 'color'], 'phone_number': ['phone', 'number'], 'region': ['region'], 'identifier': ['identifier'], 'zip_code': ['zip', 'code'], 'words': ['words'], 'birthdate': ['birthdate'], 'first_name': ['first', 'name'], 'height': ['height'], 'month': ['month'], 'longitude': ['longitude'], 'street_number': ['street', 'number'], 'address': ['address'], 'worldview': ['worldview'], 'text': ['text'], 'telephone': ['telephone'], 'calling_code': ['calling', 'code'], 'get_current_locale': ['get', 'current', 'locale'], 'stock_name': ['stock', 'name'], 'validate_enum': ['validate', 'enum'], 'federal_subject': ['federal', 'subject'], 'fruit': ['fruit'], 'duration': ['duration'], 'blood_type': ['blood', 'type'], 'bulk_create_datetimes': ['bulk', 'create', 'datetimes'], 'alphabet': ['alphabet'], 'continent': ['continent']},
        'word_tokens_set': {'time': {'time'}, 'company_type': {'company', 'type'}, 'iata_code': {'code', 'iata'}, 'century': {'century'}, 'answer': {'answer'}, 'university': {'university'}, 'full_name': {'name', 'full'}, 'price_in_btc': {'btc', 'in', 'price'}, 'username': {'username'}, 'country_code': {'country', 'code'}, 'default_country': {'country', 'default'}, 'political_views': {'views', 'political'}, 'timestamp': {'timestamp'}, 'year': {'year'}, 'color': {'color'}, 'update_dataset': {'dataset', 'update'}, 'override_locale': {'locale', 'override'}, 'stock_exchange': {'stock', 'exchange'}, 'gender_symbol': {'symbol', 'gender'}, 'isd_code': {'isd', 'code'}, 'prefecture': {'prefecture'}, 'postal_code': {'code', 'postal'}, 'day_of_week': {'of', 'day', 'week'}, 'title': {'title'}, 'academic_degree': {'degree', 'academic'}, 'country': {'country'}, 'language': {'language'}, 'views_on': {'views', 'on'}, 'bank': {'bank'}, 'surname': {'surname'}, 'datetime': {'datetime'}, 'state': {'state'}, 'cryptocurrency_symbol': {'symbol', 'cryptocurrency'}, 'timezone': {'timezone'}, 'coordinates': {'coordinates'}, 'currency_symbol': {'currency', 'symbol'}, 'emoji': {'emoji'}, 'stock_ticker': {'stock', 'ticker'}, 'formatted_date': {'date', 'formatted'}, 'cryptocurrency_iso_code': {'iso', 'code', 'cryptocurrency'}, 'latitude': {'latitude'}, 'word': {'word'}, 'dish': {'dish'}, 'quote': {'quote'}, 'weight': {'weight'}, 'last_name': {'last', 'name'}, 'sentence': {'sentence'}, 'icao_code': {'icao', 'code'}, 'password': {'password'}, 'reseed': {'reseed'}, 'street_suffix': {'street', 'suffix'}, 'currency_iso_code': {'currency', 'iso', 'code'}, 'formatted_datetime': {'datetime', 'formatted'}, 'company': {'company'}, 'country_emoji_flag': {'country', 'flag', 'emoji'}, 'week_date': {'date', 'week'}, 'occupation': {'occupation'}, 'level': {'level'}, 'city': {'city'}, 'spices': {'spices'}, 'date': {'date'}, 'price': {'price'}, 'day_of_month': {'month', 'of', 'day'}, 'nationality': {'nationality'}, 'gmt_offset': {'gmt', 'offset'}, 'gender_code': {'code', 'gender'}, 'drink': {'drink'}, 'street_name': {'street', 'name'}, 'province': {'province'}, 'formatted_time': {'formatted', 'time'}, 'hex_color': {'color', 'hex'}, 'email': {'email'}, 'gender': {'gender'}, 'periodicity': {'periodicity'}, 'name': {'name'}, 'vegetable': {'vegetable'}, 'sex': {'sex'}, 'rgb_color': {'color', 'rgb'}, 'phone_number': {'phone', 'number'}, 'region': {'region'}, 'identifier': {'identifier'}, 'zip_code': {'zip', 'code'}, 'words': {'words'}, 'birthdate': {'birthdate'}, 'first_name': {'name', 'first'}, 'height': {'height'}, 'month': {'month'}, 'longitude': {'longitude'}, 'street_number': {'street', 'number'}, 'address': {'address'}, 'worldview': {'worldview'}, 'text': {'text'}, 'telephone': {'telephone'}, 'calling_code': {'calling', 'code'}, 'get_current_locale': {'current', 'locale', 'get'}, 'stock_name': {'stock', 'name'}, 'validate_enum': {'validate', 'enum'}, 'federal_subject': {'federal', 'subject'}, 'fruit': {'fruit'}, 'duration': {'duration'}, 'blood_type': {'type', 'blood'}, 'bulk_create_datetimes': {'bulk', 'create', 'datetimes'}, 'alphabet': {'alphabet'}, 'continent': {'continent'}}
    },
    'mixed' : {
        'word_list': ['csv', 'mime_type', 'postalcode_in_state', 'prefix_female', 'isbn13', 'military_ship', 'pylist', 'md5', 'full_name', 'time_object', 'pyiterable', 'username', 'enum', 'country_code', 'ascii_email', 'default_country', 'ios_platform_token', 'year', 'bs', 'color', 'ipv6', 'safe_email', 'date_of_birth', 'date_this_decade', 'prefecture', 'credit_card_provider', 'aba', 'country', 'language', 'credit_card_expire', 'cryptocurrency_symbol', 'currency_symbol', 'prefix', 'formatted_date', 'localized_ean8', 'local_latlng', 'city_suffix', 'suffix_male', 'linux_platform_token', 'bothify', 'last_name', 'sentence', 'password', 'domain_word', 'company_suffix', 'formatted_datetime', 'currency', 'country_emoji_flag', 'level', 'ascii_company_email', 'file_name', 'image_url', 'url', 'parse', 'passport_dob', 'seed_locale', 'file_extension', 'date', 'last_name_male', 'random_digit', 'day_of_month', 'month_name', 'get_arguments', 'suffix', 'get_words_list', 'random_elements', 'gmt_offset', 'random_uppercase_letter', 'passport_owner', 'null_boolean', 'catch_phrase', 'job_female', 'zipcode_in_state', 'email', 'free_email', 'uri_path', 'safe_domain_name', 'date_between_dates', 'color_hsl', 'region', 'zip_code', 'identifier', 'time_delta', 'street_number', 'ean8', 'address', 'text', 'date_time_between_dates', 'pricetag', 'currency_name', 'stock_name', 'secondary_address', 'bulk_create_datetimes', 'alphabet', 'set_arguments', 'random_sample', 'first_name_male', 'ripe_id', 'http_method', 'swift11', 'randomize_nb_elements', 'unix_partition', 'name_female', 'sbn9', 'slug', 'political_views', 'localized_ean', 'random_element', 'update_dataset', 'localized_ean13', 'ein', 'isd_code', 'name_male', 'day_of_week', 'title', 'isbn10', 'surname', 'date_time', 'timezone', 'random_letters', 'android_platform_token', 'latitude', 'dsv', 'military_apo', 'unix_time', 'uri', 'del_arguments', 'reseed', 'street_suffix', 'get_providers', 'rgb_css_color', 'postcode_in_state', 'image', 'hostname', 'random_letter', 'spices', 'past_datetime', 'military_state', 'random_digit_or_empty', 'bban', 'ean13', 'name_nonbinary', 'ipv4_public', 'simple_profile', 'iana_id', 'nationality', 'future_datetime', 'street_name', 'zip', 'province', 'firefox', 'building_number', 'postcode', 'prefix_male', 'random_digit_not_null', 'set_formatter', 'license_plate', 'periodicity', 'sha256', 'name', 'random_lowercase_letter', 'rgb_color', 'vegetable', 'lexify', 'phone_number', 'pyint', 'random_choices', 'first_name', 'opera', 'mac_platform_token', 'tsv', 'worldview', 'invalid_ssn', 'telephone', 'pystruct', 'chrome', 'random_digit_above_two', 'internet_explorer', 'ascii_free_email', 'sentences', 'job', 'fruit', 'ipv4_network_class', 'nic_handles', 'linux_processor', 'uri_extension', 'time', 'state_abbr', 'seed_instance', 'date_time_this_year', 'psv', 'century', 'swift8', 'university', 'language_code', 'postalcode', 'safari', 'currency_code', 'vin', 'timestamp', 'date_object', 'administrative_unit', 'json', 'date_time_ad', 'override_locale', 'zipcode', 'stock_exchange', 'gender_symbol', 'cryptocurrency', 'time_series', 'ssn', 'mac_address', 'xml', 'pystr_format', 'date_this_century', 'academic_degree', 'domain_name', 'provider', 'bank', 'current_country_code', 'datetime', 'state', 'coordinates', 'pyfloat', 'credit_card_security_code', 'color_hsv', 'emoji', 'first_name_nonbinary', 'zipcode_plus4', 'pystr', 'city_prefix', 'cryptocurrency_iso_code', 'basic_phone_number', 'word', 'random_int', 'free_email_domain', 'dish', 'quote', 'date_time_this_decade', 'language_name', 'pybool', 'postalcode_plus4', 'icao_code', 'coordinate', 'date_time_this_century', 'currency_iso_code', 'date_time_this_month', 'company', 'week_date', 'upc_a', 'pyset', 'pydecimal', 'dga', 'suffix_nonbinary', 'numerify', 'user_agent', 'job_male', 'itin', 'passport_dates', 'hexify', 'port_number', 'pydict', 'paragraphs', 'formatted_time', 'ipv4', 'location_on_land', 'credit_card_number', 'passport_full', 'uuid4', 'hex_color', 'future_date', 'passport_gender', 'pyobject', 'pytuple', 'file_path', 'profile', 'safe_color_name', 'gender', 'birthdate', 'passport_number', 'longitude', 'last_name_female', 'get_formatter', 'color_rgb', 'get_current_locale', 'date_time_between', 'add_provider', 'validate_enum', 'tld', 'blood_type', 'locale', 'continent', 'latlng', 'boolean', 'swift', 'upc_e', 'bank_country', 'company_type', 'iata_code', 'answer', 'last_name_nonbinary', 'price_in_btc', 'msisdn', 'cryptocurrency_name', 'date_this_month', 'json_bytes', 'street_address', 'pytimezone', 'country_calling_code', 'suffix_female', 'http_status_code', 'postal_code', 'first_name_female', 'safe_hex_color', 'user_name', 'iban', 'views_on', 'unix_device', 'stock_ticker', 'am_pm', 'sha1', 'format', 'past_date', 'military_dpo', 'weight', 'texts', 'nic_handle', 'occupation', 'city', 'price', 'cryptocurrency_code', 'color_name', 'ascii_safe_email', 'prefix_nonbinary', 'gender_code', 'drink', 'binary', 'ipv4_private', 'iso8601', 'fixed_width', 'tar', 'random_digit_not_null_or_empty', 'windows_platform_token', 'sex', 'doi', 'random_number', 'items', 'words', 'height', 'month', 'uri_page', 'date_this_year', 'company_email', 'date_between', 'calling_code', 'ean', 'current_country', 'paragraph', 'color_rgb_float', 'mac_processor', 'federal_subject', 'duration', 'credit_card_full'],
        'word_tokens': {'csv': ['csv'], 'mime_type': ['mime', 'type'], 'postalcode_in_state': ['postalcode', 'in', 'state'], 'prefix_female': ['prefix', 'female'], 'isbn13': ['isbn13'], 'military_ship': ['military', 'ship'], 'pylist': ['pylist'], 'md5': ['md5'], 'full_name': ['full', 'name'], 'time_object': ['time', 'object'], 'pyiterable': ['pyiterable'], 'username': ['username'], 'enum': ['enum'], 'country_code': ['country', 'code'], 'ascii_email': ['ascii', 'email'], 'default_country': ['default', 'country'], 'ios_platform_token': ['ios', 'platform', 'token'], 'year': ['year'], 'bs': ['bs'], 'color': ['color'], 'ipv6': ['ipv6'], 'safe_email': ['safe', 'email'], 'date_of_birth': ['date', 'of', 'birth'], 'date_this_decade': ['date', 'this', 'decade'], 'prefecture': ['prefecture'], 'credit_card_provider': ['credit', 'card', 'provider'], 'aba': ['aba'], 'country': ['country'], 'language': ['language'], 'credit_card_expire': ['credit', 'card', 'expire'], 'cryptocurrency_symbol': ['cryptocurrency', 'symbol'], 'currency_symbol': ['currency', 'symbol'], 'prefix': ['prefix'], 'formatted_date': ['formatted', 'date'], 'localized_ean8': ['localized', 'ean8'], 'local_latlng': ['local', 'latlng'], 'city_suffix': ['city', 'suffix'], 'suffix_male': ['suffix', 'male'], 'linux_platform_token': ['linux', 'platform', 'token'], 'bothify': ['bothify'], 'last_name': ['last', 'name'], 'sentence': ['sentence'], 'password': ['password'], 'domain_word': ['domain', 'word'], 'company_suffix': ['company', 'suffix'], 'formatted_datetime': ['formatted', 'datetime'], 'currency': ['currency'], 'country_emoji_flag': ['country', 'emoji', 'flag'], 'level': ['level'], 'ascii_company_email': ['ascii', 'company', 'email'], 'file_name': ['file', 'name'], 'image_url': ['image', 'url'], 'url': ['url'], 'parse': ['parse'], 'passport_dob': ['passport', 'dob'], 'seed_locale': ['seed', 'locale'], 'file_extension': ['file', 'extension'], 'date': ['date'], 'last_name_male': ['last', 'name', 'male'], 'random_digit': ['random', 'digit'], 'day_of_month': ['day', 'of', 'month'], 'month_name': ['month', 'name'], 'get_arguments': ['get', 'arguments'], 'suffix': ['suffix'], 'get_words_list': ['get', 'words', 'list'], 'random_elements': ['random', 'elements'], 'gmt_offset': ['gmt', 'offset'], 'random_uppercase_letter': ['random', 'uppercase', 'letter'], 'passport_owner': ['passport', 'owner'], 'null_boolean': ['null', 'boolean'], 'catch_phrase': ['catch', 'phrase'], 'job_female': ['job', 'female'], 'zipcode_in_state': ['zipcode', 'in', 'state'], 'email': ['email'], 'free_email': ['free', 'email'], 'uri_path': ['uri', 'path'], 'safe_domain_name': ['safe', 'domain', 'name'], 'date_between_dates': ['date', 'between', 'dates'], 'color_hsl': ['color', 'hsl'], 'region': ['region'], 'zip_code': ['zip', 'code'], 'identifier': ['identifier'], 'time_delta': ['time', 'delta'], 'street_number': ['street', 'number'], 'ean8': ['ean8'], 'address': ['address'], 'text': ['text'], 'date_time_between_dates': ['date', 'time', 'between', 'dates'], 'pricetag': ['pricetag'], 'currency_name': ['currency', 'name'], 'stock_name': ['stock', 'name'], 'secondary_address': ['secondary', 'address'], 'bulk_create_datetimes': ['bulk', 'create', 'datetimes'], 'alphabet': ['alphabet'], 'set_arguments': ['set', 'arguments'], 'random_sample': ['random', 'sample'], 'first_name_male': ['first', 'name', 'male'], 'ripe_id': ['ripe', 'id'], 'http_method': ['http', 'method'], 'swift11': ['swift11'], 'randomize_nb_elements': ['randomize', 'nb', 'elements'], 'unix_partition': ['unix', 'partition'], 'name_female': ['name', 'female'], 'sbn9': ['sbn9'], 'slug': ['slug'], 'political_views': ['political', 'views'], 'localized_ean': ['localized', 'ean'], 'random_element': ['random', 'element'], 'update_dataset': ['update', 'dataset'], 'localized_ean13': ['localized', 'ean13'], 'ein': ['ein'], 'isd_code': ['isd', 'code'], 'name_male': ['name', 'male'], 'day_of_week': ['day', 'of', 'week'], 'title': ['title'], 'isbn10': ['isbn10'], 'surname': ['surname'], 'date_time': ['date', 'time'], 'timezone': ['timezone'], 'random_letters': ['random', 'letters'], 'android_platform_token': ['android', 'platform', 'token'], 'latitude': ['latitude'], 'dsv': ['dsv'], 'military_apo': ['military', 'apo'], 'unix_time': ['unix', 'time'], 'uri': ['uri'], 'del_arguments': ['del', 'arguments'], 'reseed': ['reseed'], 'street_suffix': ['street', 'suffix'], 'get_providers': ['get', 'providers'], 'rgb_css_color': ['rgb', 'css', 'color'], 'postcode_in_state': ['postcode', 'in', 'state'], 'image': ['image'], 'hostname': ['hostname'], 'random_letter': ['random', 'letter'], 'spices': ['spices'], 'past_datetime': ['past', 'datetime'], 'military_state': ['military', 'state'], 'random_digit_or_empty': ['random', 'digit', 'or', 'empty'], 'bban': ['bban'], 'ean13': ['ean13'], 'name_nonbinary': ['name', 'nonbinary'], 'ipv4_public': ['ipv4', 'public'], 'simple_profile': ['simple', 'profile'], 'iana_id': ['iana', 'id'], 'nationality': ['nationality'], 'future_datetime': ['future', 'datetime'], 'street_name': ['street', 'name'], 'zip': ['zip'], 'province': ['province'], 'firefox': ['firefox'], 'building_number': ['building', 'number'], 'postcode': ['postcode'], 'prefix_male': ['prefix', 'male'], 'random_digit_not_null': ['random', 'digit', 'not', 'null'], 'set_formatter': ['set', 'formatter'], 'license_plate': ['license', 'plate'], 'periodicity': ['periodicity'], 'sha256': ['sha256'], 'name': ['name'], 'random_lowercase_letter': ['random', 'lowercase', 'letter'], 'rgb_color': ['rgb', 'color'], 'vegetable': ['vegetable'], 'lexify': ['lexify'], 'phone_number': ['phone', 'number'], 'pyint': ['pyint'], 'random_choices': ['random', 'choices'], 'first_name': ['first', 'name'], 'opera': ['opera'], 'mac_platform_token': ['mac', 'platform', 'token'], 'tsv': ['tsv'], 'worldview': ['worldview'], 'invalid_ssn': ['invalid', 'ssn'], 'telephone': ['telephone'], 'pystruct': ['pystruct'], 'chrome': ['chrome'], 'random_digit_above_two': ['random', 'digit', 'above', 'two'], 'internet_explorer': ['internet', 'explorer'], 'ascii_free_email': ['ascii', 'free', 'email'], 'sentences': ['sentences'], 'job': ['job'], 'fruit': ['fruit'], 'ipv4_network_class': ['ipv4', 'network', 'class'], 'nic_handles': ['nic', 'handles'], 'linux_processor': ['linux', 'processor'], 'uri_extension': ['uri', 'extension'], 'time': ['time'], 'state_abbr': ['state', 'abbr'], 'seed_instance': ['seed', 'instance'], 'date_time_this_year': ['date', 'time', 'this', 'year'], 'psv': ['psv'], 'century': ['century'], 'swift8': ['swift8'], 'university': ['university'], 'language_code': ['language', 'code'], 'postalcode': ['postalcode'], 'safari': ['safari'], 'currency_code': ['currency', 'code'], 'vin': ['vin'], 'timestamp': ['timestamp'], 'date_object': ['date', 'object'], 'administrative_unit': ['administrative', 'unit'], 'json': ['json'], 'date_time_ad': ['date', 'time', 'ad'], 'override_locale': ['override', 'locale'], 'zipcode': ['zipcode'], 'stock_exchange': ['stock', 'exchange'], 'gender_symbol': ['gender', 'symbol'], 'cryptocurrency': ['cryptocurrency'], 'time_series': ['time', 'series'], 'ssn': ['ssn'], 'mac_address': ['mac', 'address'], 'xml': ['xml'], 'pystr_format': ['pystr', 'format'], 'date_this_century': ['date', 'this', 'century'], 'academic_degree': ['academic', 'degree'], 'domain_name': ['domain', 'name'], 'provider': ['provider'], 'bank': ['bank'], 'current_country_code': ['current', 'country', 'code'], 'datetime': ['datetime'], 'state': ['state'], 'coordinates': ['coordinates'], 'pyfloat': ['pyfloat'], 'credit_card_security_code': ['credit', 'card', 'security', 'code'], 'color_hsv': ['color', 'hsv'], 'emoji': ['emoji'], 'first_name_nonbinary': ['first', 'name', 'nonbinary'], 'zipcode_plus4': ['zipcode', 'plus4'], 'pystr': ['pystr'], 'city_prefix': ['city', 'prefix'], 'cryptocurrency_iso_code': ['cryptocurrency', 'iso', 'code'], 'basic_phone_number': ['basic', 'phone', 'number'], 'word': ['word'], 'random_int': ['random', 'int'], 'free_email_domain': ['free', 'email', 'domain'], 'dish': ['dish'], 'quote': ['quote'], 'date_time_this_decade': ['date', 'time', 'this', 'decade'], 'language_name': ['language', 'name'], 'pybool': ['pybool'], 'postalcode_plus4': ['postalcode', 'plus4'], 'icao_code': ['icao', 'code'], 'coordinate': ['coordinate'], 'date_time_this_century': ['date', 'time', 'this', 'century'], 'currency_iso_code': ['currency', 'iso', 'code'], 'date_time_this_month': ['date', 'time', 'this', 'month'], 'company': ['company'], 'week_date': ['week', 'date'], 'upc_a': ['upc', 'a'], 'pyset': ['pyset'], 'pydecimal': ['pydecimal'], 'dga': ['dga'], 'suffix_nonbinary': ['suffix', 'nonbinary'], 'numerify': ['numerify'], 'user_agent': ['user', 'agent'], 'job_male': ['job', 'male'], 'itin': ['itin'], 'passport_dates': ['passport', 'dates'], 'hexify': ['hexify'], 'port_number': ['port', 'number'], 'pydict': ['pydict'], 'paragraphs': ['paragraphs'], 'formatted_time': ['formatted', 'time'], 'ipv4': ['ipv4'], 'location_on_land': ['location', 'on', 'land'], 'credit_card_number': ['credit', 'card', 'number'], 'passport_full': ['passport', 'full'], 'uuid4': ['uuid4'], 'hex_color': ['hex', 'color'], 'future_date': ['future', 'date'], 'passport_gender': ['passport', 'gender'], 'pyobject': ['pyobject'], 'pytuple': ['pytuple'], 'file_path': ['file', 'path'], 'profile': ['profile'], 'safe_color_name': ['safe', 'color', 'name'], 'gender': ['gender'], 'birthdate': ['birthdate'], 'passport_number': ['passport', 'number'], 'longitude': ['longitude'], 'last_name_female': ['last', 'name', 'female'], 'get_formatter': ['get', 'formatter'], 'color_rgb': ['color', 'rgb'], 'get_current_locale': ['get', 'current', 'locale'], 'date_time_between': ['date', 'time', 'between'], 'add_provider': ['add', 'provider'], 'validate_enum': ['validate', 'enum'], 'tld': ['tld'], 'blood_type': ['blood', 'type'], 'locale': ['locale'], 'continent': ['continent'], 'latlng': ['latlng'], 'boolean': ['boolean'], 'swift': ['swift'], 'upc_e': ['upc', 'e'], 'bank_country': ['bank', 'country'], 'company_type': ['company', 'type'], 'iata_code': ['iata', 'code'], 'answer': ['answer'], 'last_name_nonbinary': ['last', 'name', 'nonbinary'], 'price_in_btc': ['price', 'in', 'btc'], 'msisdn': ['msisdn'], 'cryptocurrency_name': ['cryptocurrency', 'name'], 'date_this_month': ['date', 'this', 'month'], 'json_bytes': ['json', 'bytes'], 'street_address': ['street', 'address'], 'pytimezone': ['pytimezone'], 'country_calling_code': ['country', 'calling', 'code'], 'suffix_female': ['suffix', 'female'], 'http_status_code': ['http', 'status', 'code'], 'postal_code': ['postal', 'code'], 'first_name_female': ['first', 'name', 'female'], 'safe_hex_color': ['safe', 'hex', 'color'], 'user_name': ['user', 'name'], 'iban': ['iban'], 'views_on': ['views', 'on'], 'unix_device': ['unix', 'device'], 'stock_ticker': ['stock', 'ticker'], 'am_pm': ['am', 'pm'], 'sha1': ['sha1'], 'format': ['format'], 'past_date': ['past', 'date'], 'military_dpo': ['military', 'dpo'], 'weight': ['weight'], 'texts': ['texts'], 'nic_handle': ['nic', 'handle'], 'occupation': ['occupation'], 'city': ['city'], 'price': ['price'], 'cryptocurrency_code': ['cryptocurrency', 'code'], 'color_name': ['color', 'name'], 'ascii_safe_email': ['ascii', 'safe', 'email'], 'prefix_nonbinary': ['prefix', 'nonbinary'], 'gender_code': ['gender', 'code'], 'drink': ['drink'], 'binary': ['binary'], 'ipv4_private': ['ipv4', 'private'], 'iso8601': ['iso8601'], 'fixed_width': ['fixed', 'width'], 'tar': ['tar'], 'random_digit_not_null_or_empty': ['random', 'digit', 'not', 'null', 'or', 'empty'], 'windows_platform_token': ['windows', 'platform', 'token'], 'sex': ['sex'], 'doi': ['doi'], 'random_number': ['random', 'number'], 'items': ['items'], 'words': ['words'], 'height': ['height'], 'month': ['month'], 'uri_page': ['uri', 'page'], 'date_this_year': ['date', 'this', 'year'], 'company_email': ['company', 'email'], 'date_between': ['date', 'between'], 'calling_code': ['calling', 'code'], 'ean': ['ean'], 'current_country': ['current', 'country'], 'paragraph': ['paragraph'], 'color_rgb_float': ['color', 'rgb', 'float'], 'mac_processor': ['mac', 'processor'], 'federal_subject': ['federal', 'subject'], 'duration': ['duration'], 'credit_card_full': ['credit', 'card', 'full']},
        'word_tokens_set': {'csv': {'csv'}, 'mime_type': {'mime', 'type'}, 'postalcode_in_state': {'postalcode', 'state', 'in'}, 'prefix_female': {'prefix', 'female'}, 'isbn13': {'isbn13'}, 'military_ship': {'military', 'ship'}, 'pylist': {'pylist'}, 'md5': {'md5'}, 'full_name': {'name', 'full'}, 'time_object': {'object', 'time'}, 'pyiterable': {'pyiterable'}, 'username': {'username'}, 'enum': {'enum'}, 'country_code': {'country', 'code'}, 'ascii_email': {'ascii', 'email'}, 'default_country': {'country', 'default'}, 'ios_platform_token': {'platform', 'ios', 'token'}, 'year': {'year'}, 'bs': {'bs'}, 'color': {'color'}, 'ipv6': {'ipv6'}, 'safe_email': {'email', 'safe'}, 'date_of_birth': {'birth', 'date', 'of'}, 'date_this_decade': {'decade', 'date', 'this'}, 'prefecture': {'prefecture'}, 'credit_card_provider': {'provider', 'card', 'credit'}, 'aba': {'aba'}, 'country': {'country'}, 'language': {'language'}, 'credit_card_expire': {'expire', 'card', 'credit'}, 'cryptocurrency_symbol': {'symbol', 'cryptocurrency'}, 'currency_symbol': {'currency', 'symbol'}, 'prefix': {'prefix'}, 'formatted_date': {'date', 'formatted'}, 'localized_ean8': {'localized', 'ean8'}, 'local_latlng': {'local', 'latlng'}, 'city_suffix': {'city', 'suffix'}, 'suffix_male': {'suffix', 'male'}, 'linux_platform_token': {'platform', 'linux', 'token'}, 'bothify': {'bothify'}, 'last_name': {'last', 'name'}, 'sentence': {'sentence'}, 'password': {'password'}, 'domain_word': {'word', 'domain'}, 'company_suffix': {'company', 'suffix'}, 'formatted_datetime': {'datetime', 'formatted'}, 'currency': {'currency'}, 'country_emoji_flag': {'country', 'flag', 'emoji'}, 'level': {'level'}, 'ascii_company_email': {'company', 'ascii', 'email'}, 'file_name': {'file', 'name'}, 'image_url': {'url', 'image'}, 'url': {'url'}, 'parse': {'parse'}, 'passport_dob': {'dob', 'passport'}, 'seed_locale': {'locale', 'seed'}, 'file_extension': {'file', 'extension'}, 'date': {'date'}, 'last_name_male': {'last', 'name', 'male'}, 'random_digit': {'random', 'digit'}, 'day_of_month': {'month', 'of', 'day'}, 'month_name': {'month', 'name'}, 'get_arguments': {'arguments', 'get'}, 'suffix': {'suffix'}, 'get_words_list': {'list', 'words', 'get'}, 'random_elements': {'random', 'elements'}, 'gmt_offset': {'gmt', 'offset'}, 'random_uppercase_letter': {'uppercase', 'random', 'letter'}, 'passport_owner': {'owner', 'passport'}, 'null_boolean': {'boolean', 'null'}, 'catch_phrase': {'catch', 'phrase'}, 'job_female': {'female', 'job'}, 'zipcode_in_state': {'state', 'in', 'zipcode'}, 'email': {'email'}, 'free_email': {'email', 'free'}, 'uri_path': {'path', 'uri'}, 'safe_domain_name': {'domain', 'name', 'safe'}, 'date_between_dates': {'date', 'dates', 'between'}, 'color_hsl': {'hsl', 'color'}, 'region': {'region'}, 'zip_code': {'zip', 'code'}, 'identifier': {'identifier'}, 'time_delta': {'delta', 'time'}, 'street_number': {'street', 'number'}, 'ean8': {'ean8'}, 'address': {'address'}, 'text': {'text'}, 'date_time_between_dates': {'date', 'dates', 'between', 'time'}, 'pricetag': {'pricetag'}, 'currency_name': {'currency', 'name'}, 'stock_name': {'stock', 'name'}, 'secondary_address': {'address', 'secondary'}, 'bulk_create_datetimes': {'bulk', 'create', 'datetimes'}, 'alphabet': {'alphabet'}, 'set_arguments': {'arguments', 'set'}, 'random_sample': {'random', 'sample'}, 'first_name_male': {'male', 'name', 'first'}, 'ripe_id': {'id', 'ripe'}, 'http_method': {'method', 'http'}, 'swift11': {'swift11'}, 'randomize_nb_elements': {'randomize', 'elements', 'nb'}, 'unix_partition': {'partition', 'unix'}, 'name_female': {'female', 'name'}, 'sbn9': {'sbn9'}, 'slug': {'slug'}, 'political_views': {'views', 'political'}, 'localized_ean': {'localized', 'ean'}, 'random_element': {'random', 'element'}, 'update_dataset': {'dataset', 'update'}, 'localized_ean13': {'localized', 'ean13'}, 'ein': {'ein'}, 'isd_code': {'isd', 'code'}, 'name_male': {'name', 'male'}, 'day_of_week': {'of', 'day', 'week'}, 'title': {'title'}, 'isbn10': {'isbn10'}, 'surname': {'surname'}, 'date_time': {'date', 'time'}, 'timezone': {'timezone'}, 'random_letters': {'random', 'letters'}, 'android_platform_token': {'platform', 'android', 'token'}, 'latitude': {'latitude'}, 'dsv': {'dsv'}, 'military_apo': {'military', 'apo'}, 'unix_time': {'unix', 'time'}, 'uri': {'uri'}, 'del_arguments': {'del', 'arguments'}, 'reseed': {'reseed'}, 'street_suffix': {'street', 'suffix'}, 'get_providers': {'providers', 'get'}, 'rgb_css_color': {'color', 'css', 'rgb'}, 'postcode_in_state': {'state', 'in', 'postcode'}, 'image': {'image'}, 'hostname': {'hostname'}, 'random_letter': {'random', 'letter'}, 'spices': {'spices'}, 'past_datetime': {'datetime', 'past'}, 'military_state': {'military', 'state'}, 'random_digit_or_empty': {'random', 'digit', 'or', 'empty'}, 'bban': {'bban'}, 'ean13': {'ean13'}, 'name_nonbinary': {'nonbinary', 'name'}, 'ipv4_public': {'public', 'ipv4'}, 'simple_profile': {'profile', 'simple'}, 'iana_id': {'id', 'iana'}, 'nationality': {'nationality'}, 'future_datetime': {'future', 'datetime'}, 'street_name': {'street', 'name'}, 'zip': {'zip'}, 'province': {'province'}, 'firefox': {'firefox'}, 'building_number': {'number', 'building'}, 'postcode': {'postcode'}, 'prefix_male': {'prefix', 'male'}, 'random_digit_not_null': {'random', 'digit', 'null', 'not'}, 'set_formatter': {'formatter', 'set'}, 'license_plate': {'license', 'plate'}, 'periodicity': {'periodicity'}, 'sha256': {'sha256'}, 'name': {'name'}, 'random_lowercase_letter': {'lowercase', 'random', 'letter'}, 'rgb_color': {'color', 'rgb'}, 'vegetable': {'vegetable'}, 'lexify': {'lexify'}, 'phone_number': {'phone', 'number'}, 'pyint': {'pyint'}, 'random_choices': {'random', 'choices'}, 'first_name': {'name', 'first'}, 'opera': {'opera'}, 'mac_platform_token': {'token', 'platform', 'mac'}, 'tsv': {'tsv'}, 'worldview': {'worldview'}, 'invalid_ssn': {'ssn', 'invalid'}, 'telephone': {'telephone'}, 'pystruct': {'pystruct'}, 'chrome': {'chrome'}, 'random_digit_above_two': {'random', 'two', 'digit', 'above'}, 'internet_explorer': {'explorer', 'internet'}, 'ascii_free_email': {'ascii', 'email', 'free'}, 'sentences': {'sentences'}, 'job': {'job'}, 'fruit': {'fruit'}, 'ipv4_network_class': {'class', 'network', 'ipv4'}, 'nic_handles': {'handles', 'nic'}, 'linux_processor': {'processor', 'linux'}, 'uri_extension': {'extension', 'uri'}, 'time': {'time'}, 'state_abbr': {'state', 'abbr'}, 'seed_instance': {'instance', 'seed'}, 'date_time_this_year': {'year', 'date', 'this', 'time'}, 'psv': {'psv'}, 'century': {'century'}, 'swift8': {'swift8'}, 'university': {'university'}, 'language_code': {'language', 'code'}, 'postalcode': {'postalcode'}, 'safari': {'safari'}, 'currency_code': {'currency', 'code'}, 'vin': {'vin'}, 'timestamp': {'timestamp'}, 'date_object': {'object', 'date'}, 'administrative_unit': {'administrative', 'unit'}, 'json': {'json'}, 'date_time_ad': {'ad', 'date', 'time'}, 'override_locale': {'locale', 'override'}, 'zipcode': {'zipcode'}, 'stock_exchange': {'stock', 'exchange'}, 'gender_symbol': {'symbol', 'gender'}, 'cryptocurrency': {'cryptocurrency'}, 'time_series': {'series', 'time'}, 'ssn': {'ssn'}, 'mac_address': {'address', 'mac'}, 'xml': {'xml'}, 'pystr_format': {'pystr', 'format'}, 'date_this_century': {'century', 'date', 'this'}, 'academic_degree': {'degree', 'academic'}, 'domain_name': {'domain', 'name'}, 'provider': {'provider'}, 'bank': {'bank'}, 'current_country_code': {'country', 'current', 'code'}, 'datetime': {'datetime'}, 'state': {'state'}, 'coordinates': {'coordinates'}, 'pyfloat': {'pyfloat'}, 'credit_card_security_code': {'security', 'code', 'card', 'credit'}, 'color_hsv': {'hsv', 'color'}, 'emoji': {'emoji'}, 'first_name_nonbinary': {'nonbinary', 'name', 'first'}, 'zipcode_plus4': {'plus4', 'zipcode'}, 'pystr': {'pystr'}, 'city_prefix': {'prefix', 'city'}, 'cryptocurrency_iso_code': {'iso', 'code', 'cryptocurrency'}, 'basic_phone_number': {'phone', 'number', 'basic'}, 'word': {'word'}, 'random_int': {'random', 'int'}, 'free_email_domain': {'domain', 'email', 'free'}, 'dish': {'dish'}, 'quote': {'quote'}, 'date_time_this_decade': {'decade', 'date', 'this', 'time'}, 'language_name': {'language', 'name'}, 'pybool': {'pybool'}, 'postalcode_plus4': {'postalcode', 'plus4'}, 'icao_code': {'icao', 'code'}, 'coordinate': {'coordinate'}, 'date_time_this_century': {'century', 'date', 'this', 'time'}, 'currency_iso_code': {'currency', 'iso', 'code'}, 'date_time_this_month': {'month', 'date', 'this', 'time'}, 'company': {'company'}, 'week_date': {'date', 'week'}, 'upc_a': {'a', 'upc'}, 'pyset': {'pyset'}, 'pydecimal': {'pydecimal'}, 'dga': {'dga'}, 'suffix_nonbinary': {'suffix', 'nonbinary'}, 'numerify': {'numerify'}, 'user_agent': {'agent', 'user'}, 'job_male': {'job', 'male'}, 'itin': {'itin'}, 'passport_dates': {'passport', 'dates'}, 'hexify': {'hexify'}, 'port_number': {'number', 'port'}, 'pydict': {'pydict'}, 'paragraphs': {'paragraphs'}, 'formatted_time': {'formatted', 'time'}, 'ipv4': {'ipv4'}, 'location_on_land': {'location', 'land', 'on'}, 'credit_card_number': {'number', 'card', 'credit'}, 'passport_full': {'passport', 'full'}, 'uuid4': {'uuid4'}, 'hex_color': {'color', 'hex'}, 'future_date': {'future', 'date'}, 'passport_gender': {'passport', 'gender'}, 'pyobject': {'pyobject'}, 'pytuple': {'pytuple'}, 'file_path': {'path', 'file'}, 'profile': {'profile'}, 'safe_color_name': {'name', 'color', 'safe'}, 'gender': {'gender'}, 'birthdate': {'birthdate'}, 'passport_number': {'number', 'passport'}, 'longitude': {'longitude'}, 'last_name_female': {'last', 'female', 'name'}, 'get_formatter': {'formatter', 'get'}, 'color_rgb': {'color', 'rgb'}, 'get_current_locale': {'current', 'locale', 'get'}, 'date_time_between': {'date', 'between', 'time'}, 'add_provider': {'provider', 'add'}, 'validate_enum': {'validate', 'enum'}, 'tld': {'tld'}, 'blood_type': {'type', 'blood'}, 'locale': {'locale'}, 'continent': {'continent'}, 'latlng': {'latlng'}, 'boolean': {'boolean'}, 'swift': {'swift'}, 'upc_e': {'upc', 'e'}, 'bank_country': {'country', 'bank'}, 'company_type': {'company', 'type'}, 'iata_code': {'code', 'iata'}, 'answer': {'answer'}, 'last_name_nonbinary': {'last', 'nonbinary', 'name'}, 'price_in_btc': {'btc', 'in', 'price'}, 'msisdn': {'msisdn'}, 'cryptocurrency_name': {'name', 'cryptocurrency'}, 'date_this_month': {'month', 'date', 'this'}, 'json_bytes': {'json', 'bytes'}, 'street_address': {'address', 'street'}, 'pytimezone': {'pytimezone'}, 'country_calling_code': {'country', 'calling', 'code'}, 'suffix_female': {'female', 'suffix'}, 'http_status_code': {'http', 'code', 'status'}, 'postal_code': {'code', 'postal'}, 'first_name_female': {'female', 'name', 'first'}, 'safe_hex_color': {'color', 'safe', 'hex'}, 'user_name': {'user', 'name'}, 'iban': {'iban'}, 'views_on': {'views', 'on'}, 'unix_device': {'unix', 'device'}, 'stock_ticker': {'stock', 'ticker'}, 'am_pm': {'am', 'pm'}, 'sha1': {'sha1'}, 'format': {'format'}, 'past_date': {'date', 'past'}, 'military_dpo': {'military', 'dpo'}, 'weight': {'weight'}, 'texts': {'texts'}, 'nic_handle': {'nic', 'handle'}, 'occupation': {'occupation'}, 'city': {'city'}, 'price': {'price'}, 'cryptocurrency_code': {'code', 'cryptocurrency'}, 'color_name': {'color', 'name'}, 'ascii_safe_email': {'email', 'ascii', 'safe'}, 'prefix_nonbinary': {'prefix', 'nonbinary'}, 'gender_code': {'code', 'gender'}, 'drink': {'drink'}, 'binary': {'binary'}, 'ipv4_private': {'private', 'ipv4'}, 'iso8601': {'iso8601'}, 'fixed_width': {'width', 'fixed'}, 'tar': {'tar'}, 'random_digit_not_null_or_empty': {'not', 'or', 'digit', 'empty', 'null', 'random'}, 'windows_platform_token': {'windows', 'platform', 'token'}, 'sex': {'sex'}, 'doi': {'doi'}, 'random_number': {'random', 'number'}, 'items': {'items'}, 'words': {'words'}, 'height': {'height'}, 'month': {'month'}, 'uri_page': {'page', 'uri'}, 'date_this_year': {'year', 'date', 'this'}, 'company_email': {'company', 'email'}, 'date_between': {'date', 'between'}, 'calling_code': {'calling', 'code'}, 'ean': {'ean'}, 'current_country': {'country', 'current'}, 'paragraph': {'paragraph'}, 'color_rgb_float': {'color', 'rgb', 'float'}, 'mac_processor': {'processor', 'mac'}, 'federal_subject': {'federal', 'subject'}, 'duration': {'duration'}, 'credit_card_full': {'full', 'card', 'credit'}}
    },
}

python_builtin_types = {
    str,
    int,
    float,
    Decimal,
    bool,
    complex,
    bytes,
    tuple,
    list,
    set,
    frozenset,
    dict,
}
typing_origins = {List, Dict, Tuple, Set, Union, Literal, Optional}
recursive_types = {
    List,
    Dict,
    Tuple,
    Set,
    Union,
    Literal,
    Optional,
    list,
    dict,
    tuple,
    set,
    frozenset,
}
all_constr_attribs = {
    "default",
    "annotation",
    "min_length",
    "max_length",
    "pattern",
    "gt",
    "lt",
    "ge",
    "le",
    "multiple_of",
}

default_constr_dict = {
    "required": True,
    "default": None,
    "annotation": None,
    "min_length": None,
    "max_length": None,
    "pattern": None,
    "gt": None,
    "lt": None,
    "ge": None,
    "le": None,
    "multiple_of": None,
    "origin": None,
    "args": None,
}
        