from typing import List, Dict, Tuple, Set, Union, Literal, Optional, Any

from decimal import Decimal

from faker import Faker
import mimesis
from mimesis import Generic
import inspect
                
                
provider_return_types = {
    'aba' : str,
    'academic_degree' : str,
    'address' : str,
    'administrative_unit' : str,
    'alphabet' : list,
    'am_pm' : str,
    'android_platform_token' : str,
    'answer' : str,
    'ascii_company_email' : str,
    'ascii_email' : str,
    'ascii_free_email' : str,
    'ascii_safe_email' : str,
    'bank' : str,
    'bank_country' : str,
    'basic_phone_number' : str,
    'bban' : str,
    'binary' : bytes,
    'birthdate' : str,
    'blood_type' : str,
    'boolean' : str,
    'bothify' : str,
    'bs' : str,
    'building_number' : str,
    'calling_code' : str,
    'catch_phrase' : str,
    'century' : str,
    'chrome' : str,
    'city' : str,
    'city_prefix' : str,
    'city_suffix' : str,
    'color' : str,
    'color_hsl' : tuple,
    'color_hsv' : tuple,
    'color_name' : str,
    'color_rgb' : tuple,
    'color_rgb_float' : tuple,
    'company' : str,
    'company_email' : str,
    'company_suffix' : str,
    'company_type' : str,
    'continent' : str,
    'coordinate' : str,
    'coordinates' : dict,
    'country' : str,
    'country_calling_code' : str,
    'country_code' : str,
    'country_emoji_flag' : str,
    'credit_card_expire' : str,
    'credit_card_full' : str,
    'credit_card_number' : str,
    'credit_card_provider' : str,
    'credit_card_security_code' : str,
    'cryptocurrency' : tuple,
    'cryptocurrency_code' : str,
    'cryptocurrency_iso_code' : str,
    'cryptocurrency_name' : str,
    'cryptocurrency_symbol' : str,
    'csv' : str,
    'currency' : tuple,
    'currency_code' : str,
    'currency_iso_code' : str,
    'currency_name' : str,
    'currency_symbol' : str,
    'current_country' : str,
    'current_country_code' : str,
    'date' : str,
    'date_between' : str,
    'date_between_dates' : str,
    'date_object' : str,
    'date_of_birth' : str,
    'date_this_century' : str,
    'date_this_decade' : str,
    'date_this_month' : str,
    'date_this_year' : str,
    'date_time' : str,
    'date_time_ad' : str,
    'date_time_between' : str,
    'date_time_between_dates' : str,
    'date_time_this_century' : str,
    'date_time_this_decade' : str,
    'date_time_this_month' : str,
    'date_time_this_year' : str,
    'datetime' : str,
    'day_of_month' : str,
    'day_of_week' : str,
    'default_country' : str,
    'dga' : str,
    'dish' : str,
    'doi' : str,
    'domain_name' : str,
    'domain_word' : str,
    'drink' : str,
    'dsv' : str,
    'duration' : str,
    'ean' : str,
    'ean13' : str,
    'ean8' : str,
    'ein' : str,
    'email' : str,
    'emoji' : str,
    'federal_subject' : str,
    'file_extension' : str,
    'file_name' : str,
    'file_path' : str,
    'firefox' : str,
    'first_name' : str,
    'first_name_female' : str,
    'first_name_male' : str,
    'first_name_nonbinary' : str,
    'fixed_width' : str,
    'formatted_date' : str,
    'formatted_datetime' : str,
    'formatted_time' : str,
    'free_email' : str,
    'free_email_domain' : str,
    'fruit' : str,
    'full_name' : str,
    'future_date' : str,
    'future_datetime' : str,
    'gender' : str,
    'gender_code' : str,
    'gender_symbol' : str,
    'get_current_locale' : str,
    'get_providers' : list,
    'get_words_list' : list,
    'gmt_offset' : str,
    'height' : str,
    'hex_color' : str,
    'hexify' : str,
    'hostname' : str,
    'http_method' : str,
    'http_status_code' : str,
    'iana_id' : str,
    'iata_code' : str,
    'iban' : str,
    'icao_code' : str,
    'identifier' : str,
    'image_url' : str,
    'internet_explorer' : str,
    'invalid_ssn' : str,
    'ios_platform_token' : str,
    'ipv4' : str,
    'ipv4_network_class' : str,
    'ipv4_private' : str,
    'ipv4_public' : str,
    'ipv6' : str,
    'isbn10' : str,
    'isbn13' : str,
    'isd_code' : str,
    'iso8601' : str,
    'items' : list,
    'itin' : str,
    'job' : str,
    'job_female' : str,
    'job_male' : str,
    'json' : str,
    'json_bytes' : bytes,
    'language' : str,
    'language_code' : str,
    'language_name' : str,
    'last_name' : str,
    'last_name_female' : str,
    'last_name_male' : str,
    'last_name_nonbinary' : str,
    'latitude' : str,
    'latlng' : tuple,
    'level' : str,
    'lexify' : str,
    'license_plate' : str,
    'linux_platform_token' : str,
    'linux_processor' : str,
    'local_latlng' : tuple,
    'locale' : str,
    'localized_ean' : str,
    'localized_ean13' : str,
    'localized_ean8' : str,
    'location_on_land' : tuple,
    'longitude' : str,
    'mac_address' : str,
    'mac_platform_token' : str,
    'mac_processor' : str,
    'md5' : str,
    'military_apo' : str,
    'military_dpo' : str,
    'military_ship' : str,
    'military_state' : str,
    'mime_type' : str,
    'month' : str,
    'month_name' : str,
    'msisdn' : str,
    'name' : str,
    'name_female' : str,
    'name_male' : str,
    'name_nonbinary' : str,
    'nationality' : str,
    'nic_handle' : str,
    'nic_handles' : list,
    'null_boolean' : str,
    'numerify' : str,
    'occupation' : str,
    'opera' : str,
    'paragraph' : str,
    'paragraphs' : list,
    'passport_dates' : tuple,
    'passport_dob' : str,
    'passport_full' : str,
    'passport_gender' : str,
    'passport_number' : str,
    'passport_owner' : tuple,
    'password' : str,
    'past_date' : str,
    'past_datetime' : str,
    'periodicity' : str,
    'phone_number' : str,
    'political_views' : str,
    'port_number' : str,
    'postal_code' : str,
    'postalcode' : str,
    'postalcode_in_state' : str,
    'postalcode_plus4' : str,
    'postcode' : str,
    'postcode_in_state' : str,
    'prefecture' : str,
    'prefix' : str,
    'prefix_female' : str,
    'prefix_male' : str,
    'prefix_nonbinary' : str,
    'price' : str,
    'price_in_btc' : str,
    'pricetag' : str,
    'profile' : dict,
    'province' : str,
    'psv' : str,
    'pybool' : str,
    'pydecimal' : str,
    'pydict' : dict,
    'pyfloat' : str,
    'pyint' : str,
    'pyiterable' : tuple,
    'pylist' : list,
    'pyobject' : str,
    'pyset' : set,
    'pystr' : str,
    'pystr_format' : str,
    'pystruct' : tuple,
    'pytimezone' : str,
    'pytuple' : tuple,
    'quote' : str,
    'random_choices' : list,
    'random_digit' : str,
    'random_digit_above_two' : str,
    'random_digit_not_null' : str,
    'random_digit_not_null_or_empty' : str,
    'random_digit_or_empty' : str,
    'random_element' : str,
    'random_elements' : list,
    'random_int' : str,
    'random_letter' : str,
    'random_letters' : list,
    'random_lowercase_letter' : str,
    'random_number' : str,
    'random_sample' : list,
    'random_uppercase_letter' : str,
    'randomize_nb_elements' : str,
    'region' : str,
    'reseed' : str,
    'rgb_color' : tuple,
    'rgb_css_color' : str,
    'ripe_id' : str,
    'safari' : str,
    'safe_color_name' : str,
    'safe_domain_name' : str,
    'safe_email' : str,
    'safe_hex_color' : str,
    'sbn9' : str,
    'secondary_address' : str,
    'seed_instance' : str,
    'sentence' : str,
    'sentences' : list,
    'sex' : str,
    'sha1' : str,
    'sha256' : str,
    'simple_profile' : dict,
    'slug' : str,
    'spices' : str,
    'ssn' : str,
    'state' : str,
    'state_abbr' : str,
    'stock_exchange' : str,
    'stock_name' : str,
    'stock_ticker' : str,
    'street_address' : str,
    'street_name' : str,
    'street_number' : str,
    'street_suffix' : str,
    'suffix' : str,
    'suffix_female' : str,
    'suffix_male' : str,
    'suffix_nonbinary' : str,
    'surname' : str,
    'swift' : str,
    'swift11' : str,
    'swift8' : str,
    'tar' : bytes,
    'telephone' : str,
    'text' : str,
    'texts' : list,
    'time' : str,
    'time_delta' : str,
    'time_object' : str,
    'time_series' : str,
    'timestamp' : str,
    'timezone' : str,
    'title' : str,
    'tld' : str,
    'tsv' : str,
    'university' : str,
    'unix_device' : str,
    'unix_partition' : str,
    'unix_time' : str,
    'upc_a' : str,
    'upc_e' : str,
    'uri' : str,
    'uri_extension' : str,
    'uri_page' : str,
    'uri_path' : str,
    'url' : str,
    'user_agent' : str,
    'user_name' : str,
    'username' : str,
    'uuid4' : str,
    'vegetable' : str,
    'views_on' : str,
    'vin' : str,
    'week_date' : str,
    'weight' : str,
    'windows_platform_token' : str,
    'word' : str,
    'words' : list,
    'worldview' : str,
    'year' : str,
    'zip' : bytes,
    'zip_code' : str,
    'zipcode' : str,
    'zipcode_in_state' : str,
    'zipcode_plus4' : str,
}
provider_methods = {
    'faker' : {
        'word_list': ['zipcode_in_state', 'pystruct', 'word', 'opera', 'century', 'doi', 'unix_device', 'mime_type', 'day_of_month', 'prefix_nonbinary', 'language_code', 'user_agent', 'simple_profile', 'mac_processor', 'vin', 'date_this_decade', 'swift', 'swift8', 'seed_instance', 'email', 'free_email_domain', 'random_digit_or_empty', 'am_pm', 'current_country', 'ean', 'past_datetime', 'random_digit_not_null', 'invalid_ssn', 'sentence', 'prefix_female', 'random_digit_not_null_or_empty', 'location_on_land', 'file_path', 'credit_card_full', 'street_address', 'pystr', 'bank_country', 'uri_page', 'country_calling_code', 'postalcode_plus4', 'prefix_male', 'color_name', 'safe_email', 'passport_gender', 'text', 'dsv', 'iban', 'local_latlng', 'passport_full', 'postalcode_in_state', 'time_series', 'state_abbr', 'numerify', 'dga', 'job', 'random_lowercase_letter', 'safe_hex_color', 'tld', 'random_digit_above_two', 'currency', 'cryptocurrency_name', 'job_female', 'time_object', 'sentences', 'msisdn', 'md5', 'items', 'suffix_nonbinary', 'safe_color_name', 'hostname', 'cryptocurrency', 'postcode_in_state', 'pytuple', 'company_suffix', 'date_time_between_dates', 'randomize_nb_elements', 'safe_domain_name', 'passport_dates', 'address', 'isbn10', 'date_time_this_year', 'last_name_nonbinary', 'military_ship', 'swift11', 'texts', 'first_name_male', 'random_letter', 'paragraphs', 'street_name', 'timezone', 'get_providers', 'sha256', 'company_email', 'day_of_week', 'job_male', 'pytimezone', 'currency_code', 'date_object', 'language_name', 'sbn9', 'random_number', 'last_name_female', 'license_plate', 'date_time', 'nic_handle', 'zip', 'iso8601', 'tsv', 'ascii_free_email', 'bs', 'ascii_safe_email', 'file_name', 'military_state', 'uri_extension', 'http_method', 'locale', 'date_time_ad', 'city', 'passport_owner', 'localized_ean8', 'password', 'color_hsv', 'country', 'boolean', 'date_time_this_decade', 'name_nonbinary', 'itin', 'pylist', 'random_choices', 'random_uppercase_letter', 'latlng', 'rgb_color', 'domain_word', 'safari', 'catch_phrase', 'random_letters', 'pystr_format', 'profile', 'localized_ean', 'mac_address', 'random_sample', 'upc_e', 'uri_path', 'ipv4_network_class', 'ipv6', 'image_url', 'month_name', 'basic_phone_number', 'last_name', 'sha1', 'state', 'pricetag', 'unix_partition', 'currency_name', 'paragraph', 'future_datetime', 'mac_platform_token', 'windows_platform_token', 'date_time_between', 'pyint', 'bban', 'json_bytes', 'country_code', 'ripe_id', 'random_int', 'fixed_width', 'ean8', 'ein', 'pyfloat', 'ios_platform_token', 'words', 'color', 'tar', 'aba', 'pyset', 'suffix', 'file_extension', 'latitude', 'unix_time', 'get_words_list', 'csv', 'pyiterable', 'pybool', 'slug', 'suffix_male', 'building_number', 'credit_card_number', 'first_name_female', 'nic_handles', 'linux_platform_token', 'postcode', 'rgb_css_color', 'zipcode', 'date_this_century', 'android_platform_token', 'time_delta', 'first_name_nonbinary', 'domain_name', 'ascii_email', 'firefox', 'city_suffix', 'credit_card_security_code', 'current_country_code', 'date_between_dates', 'json', 'localized_ean13', 'name_male', 'bothify', 'url', 'date_time_this_month', 'credit_card_expire', 'military_dpo', 'emoji', 'ascii_company_email', 'uuid4', 'binary', 'ipv4_public', 'date_between', 'upc_a', 'future_date', 'random_element', 'credit_card_provider', 'hex_color', 'passport_number', 'company', 'hexify', 'ssn', 'lexify', 'phone_number', 'coordinate', 'date_this_month', 'internet_explorer', 'postalcode', 'name_female', 'ipv4', 'name', 'administrative_unit', 'first_name', 'user_name', 'pydecimal', 'random_elements', 'ipv4_private', 'past_date', 'linux_processor', 'color_rgb_float', 'pyobject', 'cryptocurrency_code', 'iana_id', 'uri', 'isbn13', 'suffix_female', 'year', 'longitude', 'date_time_this_century', 'http_status_code', 'zipcode_plus4', 'date_of_birth', 'last_name_male', 'color_hsl', 'passport_dob', 'date', 'currency_symbol', 'month', 'free_email', 'street_suffix', 'random_digit', 'color_rgb', 'military_apo', 'prefix', 'time', 'date_this_year', 'psv', 'secondary_address', 'chrome', 'null_boolean', 'ean13', 'city_prefix', 'port_number', 'pydict'],
        'word_tokens': {'zipcode_in_state': ['zipcode', 'in', 'state'], 'pystruct': ['pystruct'], 'word': ['word'], 'opera': ['opera'], 'century': ['century'], 'doi': ['doi'], 'unix_device': ['unix', 'device'], 'mime_type': ['mime', 'type'], 'day_of_month': ['day', 'of', 'month'], 'prefix_nonbinary': ['prefix', 'nonbinary'], 'language_code': ['language', 'code'], 'user_agent': ['user', 'agent'], 'simple_profile': ['simple', 'profile'], 'mac_processor': ['mac', 'processor'], 'vin': ['vin'], 'date_this_decade': ['date', 'this', 'decade'], 'swift': ['swift'], 'swift8': ['swift8'], 'seed_instance': ['seed', 'instance'], 'email': ['email'], 'free_email_domain': ['free', 'email', 'domain'], 'random_digit_or_empty': ['random', 'digit', 'or', 'empty'], 'am_pm': ['am', 'pm'], 'current_country': ['current', 'country'], 'ean': ['ean'], 'past_datetime': ['past', 'datetime'], 'random_digit_not_null': ['random', 'digit', 'not', 'null'], 'invalid_ssn': ['invalid', 'ssn'], 'sentence': ['sentence'], 'prefix_female': ['prefix', 'female'], 'random_digit_not_null_or_empty': ['random', 'digit', 'not', 'null', 'or', 'empty'], 'location_on_land': ['location', 'on', 'land'], 'file_path': ['file', 'path'], 'credit_card_full': ['credit', 'card', 'full'], 'street_address': ['street', 'address'], 'pystr': ['pystr'], 'bank_country': ['bank', 'country'], 'uri_page': ['uri', 'page'], 'country_calling_code': ['country', 'calling', 'code'], 'postalcode_plus4': ['postalcode', 'plus4'], 'prefix_male': ['prefix', 'male'], 'color_name': ['color', 'name'], 'safe_email': ['safe', 'email'], 'passport_gender': ['passport', 'gender'], 'text': ['text'], 'dsv': ['dsv'], 'iban': ['iban'], 'local_latlng': ['local', 'latlng'], 'passport_full': ['passport', 'full'], 'postalcode_in_state': ['postalcode', 'in', 'state'], 'time_series': ['time', 'series'], 'state_abbr': ['state', 'abbr'], 'numerify': ['numerify'], 'dga': ['dga'], 'job': ['job'], 'random_lowercase_letter': ['random', 'lowercase', 'letter'], 'safe_hex_color': ['safe', 'hex', 'color'], 'tld': ['tld'], 'random_digit_above_two': ['random', 'digit', 'above', 'two'], 'currency': ['currency'], 'cryptocurrency_name': ['cryptocurrency', 'name'], 'job_female': ['job', 'female'], 'time_object': ['time', 'object'], 'sentences': ['sentences'], 'msisdn': ['msisdn'], 'md5': ['md5'], 'items': ['items'], 'suffix_nonbinary': ['suffix', 'nonbinary'], 'safe_color_name': ['safe', 'color', 'name'], 'hostname': ['hostname'], 'cryptocurrency': ['cryptocurrency'], 'postcode_in_state': ['postcode', 'in', 'state'], 'pytuple': ['pytuple'], 'company_suffix': ['company', 'suffix'], 'date_time_between_dates': ['date', 'time', 'between', 'dates'], 'randomize_nb_elements': ['randomize', 'nb', 'elements'], 'safe_domain_name': ['safe', 'domain', 'name'], 'passport_dates': ['passport', 'dates'], 'address': ['address'], 'isbn10': ['isbn10'], 'date_time_this_year': ['date', 'time', 'this', 'year'], 'last_name_nonbinary': ['last', 'name', 'nonbinary'], 'military_ship': ['military', 'ship'], 'swift11': ['swift11'], 'texts': ['texts'], 'first_name_male': ['first', 'name', 'male'], 'random_letter': ['random', 'letter'], 'paragraphs': ['paragraphs'], 'street_name': ['street', 'name'], 'timezone': ['timezone'], 'get_providers': ['get', 'providers'], 'sha256': ['sha256'], 'company_email': ['company', 'email'], 'day_of_week': ['day', 'of', 'week'], 'job_male': ['job', 'male'], 'pytimezone': ['pytimezone'], 'currency_code': ['currency', 'code'], 'date_object': ['date', 'object'], 'language_name': ['language', 'name'], 'sbn9': ['sbn9'], 'random_number': ['random', 'number'], 'last_name_female': ['last', 'name', 'female'], 'license_plate': ['license', 'plate'], 'date_time': ['date', 'time'], 'nic_handle': ['nic', 'handle'], 'zip': ['zip'], 'iso8601': ['iso8601'], 'tsv': ['tsv'], 'ascii_free_email': ['ascii', 'free', 'email'], 'bs': ['bs'], 'ascii_safe_email': ['ascii', 'safe', 'email'], 'file_name': ['file', 'name'], 'military_state': ['military', 'state'], 'uri_extension': ['uri', 'extension'], 'http_method': ['http', 'method'], 'locale': ['locale'], 'date_time_ad': ['date', 'time', 'ad'], 'city': ['city'], 'passport_owner': ['passport', 'owner'], 'localized_ean8': ['localized', 'ean8'], 'password': ['password'], 'color_hsv': ['color', 'hsv'], 'country': ['country'], 'boolean': ['boolean'], 'date_time_this_decade': ['date', 'time', 'this', 'decade'], 'name_nonbinary': ['name', 'nonbinary'], 'itin': ['itin'], 'pylist': ['pylist'], 'random_choices': ['random', 'choices'], 'random_uppercase_letter': ['random', 'uppercase', 'letter'], 'latlng': ['latlng'], 'rgb_color': ['rgb', 'color'], 'domain_word': ['domain', 'word'], 'safari': ['safari'], 'catch_phrase': ['catch', 'phrase'], 'random_letters': ['random', 'letters'], 'pystr_format': ['pystr', 'format'], 'profile': ['profile'], 'localized_ean': ['localized', 'ean'], 'mac_address': ['mac', 'address'], 'random_sample': ['random', 'sample'], 'upc_e': ['upc', 'e'], 'uri_path': ['uri', 'path'], 'ipv4_network_class': ['ipv4', 'network', 'class'], 'ipv6': ['ipv6'], 'image_url': ['image', 'url'], 'month_name': ['month', 'name'], 'basic_phone_number': ['basic', 'phone', 'number'], 'last_name': ['last', 'name'], 'sha1': ['sha1'], 'state': ['state'], 'pricetag': ['pricetag'], 'unix_partition': ['unix', 'partition'], 'currency_name': ['currency', 'name'], 'paragraph': ['paragraph'], 'future_datetime': ['future', 'datetime'], 'mac_platform_token': ['mac', 'platform', 'token'], 'windows_platform_token': ['windows', 'platform', 'token'], 'date_time_between': ['date', 'time', 'between'], 'pyint': ['pyint'], 'bban': ['bban'], 'json_bytes': ['json', 'bytes'], 'country_code': ['country', 'code'], 'ripe_id': ['ripe', 'id'], 'random_int': ['random', 'int'], 'fixed_width': ['fixed', 'width'], 'ean8': ['ean8'], 'ein': ['ein'], 'pyfloat': ['pyfloat'], 'ios_platform_token': ['ios', 'platform', 'token'], 'words': ['words'], 'color': ['color'], 'tar': ['tar'], 'aba': ['aba'], 'pyset': ['pyset'], 'suffix': ['suffix'], 'file_extension': ['file', 'extension'], 'latitude': ['latitude'], 'unix_time': ['unix', 'time'], 'get_words_list': ['get', 'words', 'list'], 'csv': ['csv'], 'pyiterable': ['pyiterable'], 'pybool': ['pybool'], 'slug': ['slug'], 'suffix_male': ['suffix', 'male'], 'building_number': ['building', 'number'], 'credit_card_number': ['credit', 'card', 'number'], 'first_name_female': ['first', 'name', 'female'], 'nic_handles': ['nic', 'handles'], 'linux_platform_token': ['linux', 'platform', 'token'], 'postcode': ['postcode'], 'rgb_css_color': ['rgb', 'css', 'color'], 'zipcode': ['zipcode'], 'date_this_century': ['date', 'this', 'century'], 'android_platform_token': ['android', 'platform', 'token'], 'time_delta': ['time', 'delta'], 'first_name_nonbinary': ['first', 'name', 'nonbinary'], 'domain_name': ['domain', 'name'], 'ascii_email': ['ascii', 'email'], 'firefox': ['firefox'], 'city_suffix': ['city', 'suffix'], 'credit_card_security_code': ['credit', 'card', 'security', 'code'], 'current_country_code': ['current', 'country', 'code'], 'date_between_dates': ['date', 'between', 'dates'], 'json': ['json'], 'localized_ean13': ['localized', 'ean13'], 'name_male': ['name', 'male'], 'bothify': ['bothify'], 'url': ['url'], 'date_time_this_month': ['date', 'time', 'this', 'month'], 'credit_card_expire': ['credit', 'card', 'expire'], 'military_dpo': ['military', 'dpo'], 'emoji': ['emoji'], 'ascii_company_email': ['ascii', 'company', 'email'], 'uuid4': ['uuid4'], 'binary': ['binary'], 'ipv4_public': ['ipv4', 'public'], 'date_between': ['date', 'between'], 'upc_a': ['upc', 'a'], 'future_date': ['future', 'date'], 'random_element': ['random', 'element'], 'credit_card_provider': ['credit', 'card', 'provider'], 'hex_color': ['hex', 'color'], 'passport_number': ['passport', 'number'], 'company': ['company'], 'hexify': ['hexify'], 'ssn': ['ssn'], 'lexify': ['lexify'], 'phone_number': ['phone', 'number'], 'coordinate': ['coordinate'], 'date_this_month': ['date', 'this', 'month'], 'internet_explorer': ['internet', 'explorer'], 'postalcode': ['postalcode'], 'name_female': ['name', 'female'], 'ipv4': ['ipv4'], 'name': ['name'], 'administrative_unit': ['administrative', 'unit'], 'first_name': ['first', 'name'], 'user_name': ['user', 'name'], 'pydecimal': ['pydecimal'], 'random_elements': ['random', 'elements'], 'ipv4_private': ['ipv4', 'private'], 'past_date': ['past', 'date'], 'linux_processor': ['linux', 'processor'], 'color_rgb_float': ['color', 'rgb', 'float'], 'pyobject': ['pyobject'], 'cryptocurrency_code': ['cryptocurrency', 'code'], 'iana_id': ['iana', 'id'], 'uri': ['uri'], 'isbn13': ['isbn13'], 'suffix_female': ['suffix', 'female'], 'year': ['year'], 'longitude': ['longitude'], 'date_time_this_century': ['date', 'time', 'this', 'century'], 'http_status_code': ['http', 'status', 'code'], 'zipcode_plus4': ['zipcode', 'plus4'], 'date_of_birth': ['date', 'of', 'birth'], 'last_name_male': ['last', 'name', 'male'], 'color_hsl': ['color', 'hsl'], 'passport_dob': ['passport', 'dob'], 'date': ['date'], 'currency_symbol': ['currency', 'symbol'], 'month': ['month'], 'free_email': ['free', 'email'], 'street_suffix': ['street', 'suffix'], 'random_digit': ['random', 'digit'], 'color_rgb': ['color', 'rgb'], 'military_apo': ['military', 'apo'], 'prefix': ['prefix'], 'time': ['time'], 'date_this_year': ['date', 'this', 'year'], 'psv': ['psv'], 'secondary_address': ['secondary', 'address'], 'chrome': ['chrome'], 'null_boolean': ['null', 'boolean'], 'ean13': ['ean13'], 'city_prefix': ['city', 'prefix'], 'port_number': ['port', 'number'], 'pydict': ['pydict']},
        'word_tokens_set': {'zipcode_in_state': {'in', 'state', 'zipcode'}, 'pystruct': {'pystruct'}, 'word': {'word'}, 'opera': {'opera'}, 'century': {'century'}, 'doi': {'doi'}, 'unix_device': {'device', 'unix'}, 'mime_type': {'type', 'mime'}, 'day_of_month': {'month', 'day', 'of'}, 'prefix_nonbinary': {'prefix', 'nonbinary'}, 'language_code': {'language', 'code'}, 'user_agent': {'agent', 'user'}, 'simple_profile': {'simple', 'profile'}, 'mac_processor': {'mac', 'processor'}, 'vin': {'vin'}, 'date_this_decade': {'decade', 'date', 'this'}, 'swift': {'swift'}, 'swift8': {'swift8'}, 'seed_instance': {'instance', 'seed'}, 'email': {'email'}, 'free_email_domain': {'domain', 'free', 'email'}, 'random_digit_or_empty': {'empty', 'or', 'digit', 'random'}, 'am_pm': {'pm', 'am'}, 'current_country': {'current', 'country'}, 'ean': {'ean'}, 'past_datetime': {'past', 'datetime'}, 'random_digit_not_null': {'null', 'not', 'digit', 'random'}, 'invalid_ssn': {'invalid', 'ssn'}, 'sentence': {'sentence'}, 'prefix_female': {'prefix', 'female'}, 'random_digit_not_null_or_empty': {'or', 'not', 'empty', 'null', 'digit', 'random'}, 'location_on_land': {'location', 'on', 'land'}, 'file_path': {'path', 'file'}, 'credit_card_full': {'credit', 'full', 'card'}, 'street_address': {'address', 'street'}, 'pystr': {'pystr'}, 'bank_country': {'country', 'bank'}, 'uri_page': {'page', 'uri'}, 'country_calling_code': {'country', 'code', 'calling'}, 'postalcode_plus4': {'postalcode', 'plus4'}, 'prefix_male': {'male', 'prefix'}, 'color_name': {'color', 'name'}, 'safe_email': {'safe', 'email'}, 'passport_gender': {'gender', 'passport'}, 'text': {'text'}, 'dsv': {'dsv'}, 'iban': {'iban'}, 'local_latlng': {'local', 'latlng'}, 'passport_full': {'full', 'passport'}, 'postalcode_in_state': {'in', 'postalcode', 'state'}, 'time_series': {'time', 'series'}, 'state_abbr': {'state', 'abbr'}, 'numerify': {'numerify'}, 'dga': {'dga'}, 'job': {'job'}, 'random_lowercase_letter': {'letter', 'lowercase', 'random'}, 'safe_hex_color': {'color', 'safe', 'hex'}, 'tld': {'tld'}, 'random_digit_above_two': {'two', 'above', 'digit', 'random'}, 'currency': {'currency'}, 'cryptocurrency_name': {'cryptocurrency', 'name'}, 'job_female': {'job', 'female'}, 'time_object': {'time', 'object'}, 'sentences': {'sentences'}, 'msisdn': {'msisdn'}, 'md5': {'md5'}, 'items': {'items'}, 'suffix_nonbinary': {'suffix', 'nonbinary'}, 'safe_color_name': {'color', 'safe', 'name'}, 'hostname': {'hostname'}, 'cryptocurrency': {'cryptocurrency'}, 'postcode_in_state': {'in', 'state', 'postcode'}, 'pytuple': {'pytuple'}, 'company_suffix': {'suffix', 'company'}, 'date_time_between_dates': {'time', 'date', 'between', 'dates'}, 'randomize_nb_elements': {'elements', 'randomize', 'nb'}, 'safe_domain_name': {'domain', 'safe', 'name'}, 'passport_dates': {'passport', 'dates'}, 'address': {'address'}, 'isbn10': {'isbn10'}, 'date_time_this_year': {'year', 'time', 'date', 'this'}, 'last_name_nonbinary': {'last', 'name', 'nonbinary'}, 'military_ship': {'military', 'ship'}, 'swift11': {'swift11'}, 'texts': {'texts'}, 'first_name_male': {'male', 'first', 'name'}, 'random_letter': {'letter', 'random'}, 'paragraphs': {'paragraphs'}, 'street_name': {'street', 'name'}, 'timezone': {'timezone'}, 'get_providers': {'get', 'providers'}, 'sha256': {'sha256'}, 'company_email': {'company', 'email'}, 'day_of_week': {'week', 'day', 'of'}, 'job_male': {'male', 'job'}, 'pytimezone': {'pytimezone'}, 'currency_code': {'code', 'currency'}, 'date_object': {'date', 'object'}, 'language_name': {'language', 'name'}, 'sbn9': {'sbn9'}, 'random_number': {'number', 'random'}, 'last_name_female': {'last', 'female', 'name'}, 'license_plate': {'license', 'plate'}, 'date_time': {'time', 'date'}, 'nic_handle': {'handle', 'nic'}, 'zip': {'zip'}, 'iso8601': {'iso8601'}, 'tsv': {'tsv'}, 'ascii_free_email': {'free', 'email', 'ascii'}, 'bs': {'bs'}, 'ascii_safe_email': {'safe', 'email', 'ascii'}, 'file_name': {'name', 'file'}, 'military_state': {'military', 'state'}, 'uri_extension': {'uri', 'extension'}, 'http_method': {'http', 'method'}, 'locale': {'locale'}, 'date_time_ad': {'ad', 'time', 'date'}, 'city': {'city'}, 'passport_owner': {'owner', 'passport'}, 'localized_ean8': {'ean8', 'localized'}, 'password': {'password'}, 'color_hsv': {'color', 'hsv'}, 'country': {'country'}, 'boolean': {'boolean'}, 'date_time_this_decade': {'decade', 'time', 'date', 'this'}, 'name_nonbinary': {'name', 'nonbinary'}, 'itin': {'itin'}, 'pylist': {'pylist'}, 'random_choices': {'choices', 'random'}, 'random_uppercase_letter': {'letter', 'uppercase', 'random'}, 'latlng': {'latlng'}, 'rgb_color': {'color', 'rgb'}, 'domain_word': {'domain', 'word'}, 'safari': {'safari'}, 'catch_phrase': {'catch', 'phrase'}, 'random_letters': {'letters', 'random'}, 'pystr_format': {'format', 'pystr'}, 'profile': {'profile'}, 'localized_ean': {'ean', 'localized'}, 'mac_address': {'address', 'mac'}, 'random_sample': {'sample', 'random'}, 'upc_e': {'upc', 'e'}, 'uri_path': {'path', 'uri'}, 'ipv4_network_class': {'network', 'class', 'ipv4'}, 'ipv6': {'ipv6'}, 'image_url': {'image', 'url'}, 'month_name': {'month', 'name'}, 'basic_phone_number': {'phone', 'basic', 'number'}, 'last_name': {'last', 'name'}, 'sha1': {'sha1'}, 'state': {'state'}, 'pricetag': {'pricetag'}, 'unix_partition': {'partition', 'unix'}, 'currency_name': {'name', 'currency'}, 'paragraph': {'paragraph'}, 'future_datetime': {'future', 'datetime'}, 'mac_platform_token': {'mac', 'token', 'platform'}, 'windows_platform_token': {'windows', 'token', 'platform'}, 'date_time_between': {'time', 'date', 'between'}, 'pyint': {'pyint'}, 'bban': {'bban'}, 'json_bytes': {'bytes', 'json'}, 'country_code': {'country', 'code'}, 'ripe_id': {'ripe', 'id'}, 'random_int': {'int', 'random'}, 'fixed_width': {'width', 'fixed'}, 'ean8': {'ean8'}, 'ein': {'ein'}, 'pyfloat': {'pyfloat'}, 'ios_platform_token': {'ios', 'token', 'platform'}, 'words': {'words'}, 'color': {'color'}, 'tar': {'tar'}, 'aba': {'aba'}, 'pyset': {'pyset'}, 'suffix': {'suffix'}, 'file_extension': {'extension', 'file'}, 'latitude': {'latitude'}, 'unix_time': {'time', 'unix'}, 'get_words_list': {'get', 'list', 'words'}, 'csv': {'csv'}, 'pyiterable': {'pyiterable'}, 'pybool': {'pybool'}, 'slug': {'slug'}, 'suffix_male': {'male', 'suffix'}, 'building_number': {'number', 'building'}, 'credit_card_number': {'credit', 'card', 'number'}, 'first_name_female': {'first', 'female', 'name'}, 'nic_handles': {'handles', 'nic'}, 'linux_platform_token': {'linux', 'token', 'platform'}, 'postcode': {'postcode'}, 'rgb_css_color': {'color', 'rgb', 'css'}, 'zipcode': {'zipcode'}, 'date_this_century': {'century', 'date', 'this'}, 'android_platform_token': {'android', 'token', 'platform'}, 'time_delta': {'delta', 'time'}, 'first_name_nonbinary': {'first', 'name', 'nonbinary'}, 'domain_name': {'domain', 'name'}, 'ascii_email': {'email', 'ascii'}, 'firefox': {'firefox'}, 'city_suffix': {'suffix', 'city'}, 'credit_card_security_code': {'credit', 'card', 'code', 'security'}, 'current_country_code': {'current', 'country', 'code'}, 'date_between_dates': {'date', 'between', 'dates'}, 'json': {'json'}, 'localized_ean13': {'ean13', 'localized'}, 'name_male': {'male', 'name'}, 'bothify': {'bothify'}, 'url': {'url'}, 'date_time_this_month': {'month', 'time', 'date', 'this'}, 'credit_card_expire': {'credit', 'card', 'expire'}, 'military_dpo': {'military', 'dpo'}, 'emoji': {'emoji'}, 'ascii_company_email': {'company', 'email', 'ascii'}, 'uuid4': {'uuid4'}, 'binary': {'binary'}, 'ipv4_public': {'ipv4', 'public'}, 'date_between': {'date', 'between'}, 'upc_a': {'a', 'upc'}, 'future_date': {'date', 'future'}, 'random_element': {'element', 'random'}, 'credit_card_provider': {'credit', 'card', 'provider'}, 'hex_color': {'color', 'hex'}, 'passport_number': {'number', 'passport'}, 'company': {'company'}, 'hexify': {'hexify'}, 'ssn': {'ssn'}, 'lexify': {'lexify'}, 'phone_number': {'phone', 'number'}, 'coordinate': {'coordinate'}, 'date_this_month': {'month', 'date', 'this'}, 'internet_explorer': {'internet', 'explorer'}, 'postalcode': {'postalcode'}, 'name_female': {'female', 'name'}, 'ipv4': {'ipv4'}, 'name': {'name'}, 'administrative_unit': {'administrative', 'unit'}, 'first_name': {'first', 'name'}, 'user_name': {'name', 'user'}, 'pydecimal': {'pydecimal'}, 'random_elements': {'elements', 'random'}, 'ipv4_private': {'private', 'ipv4'}, 'past_date': {'date', 'past'}, 'linux_processor': {'linux', 'processor'}, 'color_rgb_float': {'color', 'rgb', 'float'}, 'pyobject': {'pyobject'}, 'cryptocurrency_code': {'cryptocurrency', 'code'}, 'iana_id': {'iana', 'id'}, 'uri': {'uri'}, 'isbn13': {'isbn13'}, 'suffix_female': {'suffix', 'female'}, 'year': {'year'}, 'longitude': {'longitude'}, 'date_time_this_century': {'century', 'time', 'date', 'this'}, 'http_status_code': {'status', 'http', 'code'}, 'zipcode_plus4': {'plus4', 'zipcode'}, 'date_of_birth': {'date', 'birth', 'of'}, 'last_name_male': {'last', 'male', 'name'}, 'color_hsl': {'color', 'hsl'}, 'passport_dob': {'dob', 'passport'}, 'date': {'date'}, 'currency_symbol': {'symbol', 'currency'}, 'month': {'month'}, 'free_email': {'free', 'email'}, 'street_suffix': {'suffix', 'street'}, 'random_digit': {'digit', 'random'}, 'color_rgb': {'color', 'rgb'}, 'military_apo': {'military', 'apo'}, 'prefix': {'prefix'}, 'time': {'time'}, 'date_this_year': {'year', 'date', 'this'}, 'psv': {'psv'}, 'secondary_address': {'secondary', 'address'}, 'chrome': {'chrome'}, 'null_boolean': {'null', 'boolean'}, 'ean13': {'ean13'}, 'city_prefix': {'prefix', 'city'}, 'port_number': {'port', 'number'}, 'pydict': {'pydict'}}
    },
    'mimesis' : {
        'word_list': ['spices', 'word', 'identifier', 'century', 'coordinates', 'day_of_month', 'alphabet', 'street_number', 'get_current_locale', 'email', 'university', 'reseed', 'region', 'language', 'birthdate', 'sentence', 'cryptocurrency_iso_code', 'surname', 'gmt_offset', 'federal_subject', 'text', 'iata_code', 'isd_code', 'stock_exchange', 'duration', 'height', 'datetime', 'timestamp', 'calling_code', 'postal_code', 'price_in_btc', 'week_date', 'answer', 'address', 'prefecture', 'continent', 'telephone', 'province', 'street_name', 'timezone', 'periodicity', 'cryptocurrency_symbol', 'day_of_week', 'country_emoji_flag', 'worldview', 'state', 'city', 'sex', 'password', 'country', 'full_name', 'rgb_color', 'nationality', 'price', 'gender_symbol', 'last_name', 'vegetable', 'dish', 'country_code', 'default_country', 'quote', 'drink', 'gender_code', 'formatted_datetime', 'words', 'color', 'weight', 'gender', 'formatted_date', 'currency_iso_code', 'company_type', 'latitude', 'stock_ticker', 'username', 'formatted_time', 'occupation', 'academic_degree', 'blood_type', 'fruit', 'zip_code', 'emoji', 'hex_color', 'company', 'political_views', 'bank', 'phone_number', 'name', 'first_name', 'year', 'longitude', 'icao_code', 'date', 'currency_symbol', 'month', 'street_suffix', 'stock_name', 'time', 'title', 'views_on', 'level'],
        'word_tokens': {'spices': ['spices'], 'word': ['word'], 'identifier': ['identifier'], 'century': ['century'], 'coordinates': ['coordinates'], 'day_of_month': ['day', 'of', 'month'], 'alphabet': ['alphabet'], 'street_number': ['street', 'number'], 'get_current_locale': ['get', 'current', 'locale'], 'email': ['email'], 'university': ['university'], 'reseed': ['reseed'], 'region': ['region'], 'language': ['language'], 'birthdate': ['birthdate'], 'sentence': ['sentence'], 'cryptocurrency_iso_code': ['cryptocurrency', 'iso', 'code'], 'surname': ['surname'], 'gmt_offset': ['gmt', 'offset'], 'federal_subject': ['federal', 'subject'], 'text': ['text'], 'iata_code': ['iata', 'code'], 'isd_code': ['isd', 'code'], 'stock_exchange': ['stock', 'exchange'], 'duration': ['duration'], 'height': ['height'], 'datetime': ['datetime'], 'timestamp': ['timestamp'], 'calling_code': ['calling', 'code'], 'postal_code': ['postal', 'code'], 'price_in_btc': ['price', 'in', 'btc'], 'week_date': ['week', 'date'], 'answer': ['answer'], 'address': ['address'], 'prefecture': ['prefecture'], 'continent': ['continent'], 'telephone': ['telephone'], 'province': ['province'], 'street_name': ['street', 'name'], 'timezone': ['timezone'], 'periodicity': ['periodicity'], 'cryptocurrency_symbol': ['cryptocurrency', 'symbol'], 'day_of_week': ['day', 'of', 'week'], 'country_emoji_flag': ['country', 'emoji', 'flag'], 'worldview': ['worldview'], 'state': ['state'], 'city': ['city'], 'sex': ['sex'], 'password': ['password'], 'country': ['country'], 'full_name': ['full', 'name'], 'rgb_color': ['rgb', 'color'], 'nationality': ['nationality'], 'price': ['price'], 'gender_symbol': ['gender', 'symbol'], 'last_name': ['last', 'name'], 'vegetable': ['vegetable'], 'dish': ['dish'], 'country_code': ['country', 'code'], 'default_country': ['default', 'country'], 'quote': ['quote'], 'drink': ['drink'], 'gender_code': ['gender', 'code'], 'formatted_datetime': ['formatted', 'datetime'], 'words': ['words'], 'color': ['color'], 'weight': ['weight'], 'gender': ['gender'], 'formatted_date': ['formatted', 'date'], 'currency_iso_code': ['currency', 'iso', 'code'], 'company_type': ['company', 'type'], 'latitude': ['latitude'], 'stock_ticker': ['stock', 'ticker'], 'username': ['username'], 'formatted_time': ['formatted', 'time'], 'occupation': ['occupation'], 'academic_degree': ['academic', 'degree'], 'blood_type': ['blood', 'type'], 'fruit': ['fruit'], 'zip_code': ['zip', 'code'], 'emoji': ['emoji'], 'hex_color': ['hex', 'color'], 'company': ['company'], 'political_views': ['political', 'views'], 'bank': ['bank'], 'phone_number': ['phone', 'number'], 'name': ['name'], 'first_name': ['first', 'name'], 'year': ['year'], 'longitude': ['longitude'], 'icao_code': ['icao', 'code'], 'date': ['date'], 'currency_symbol': ['currency', 'symbol'], 'month': ['month'], 'street_suffix': ['street', 'suffix'], 'stock_name': ['stock', 'name'], 'time': ['time'], 'title': ['title'], 'views_on': ['views', 'on'], 'level': ['level']},
        'word_tokens_set': {'spices': {'spices'}, 'word': {'word'}, 'identifier': {'identifier'}, 'century': {'century'}, 'coordinates': {'coordinates'}, 'day_of_month': {'month', 'day', 'of'}, 'alphabet': {'alphabet'}, 'street_number': {'street', 'number'}, 'get_current_locale': {'current', 'get', 'locale'}, 'email': {'email'}, 'university': {'university'}, 'reseed': {'reseed'}, 'region': {'region'}, 'language': {'language'}, 'birthdate': {'birthdate'}, 'sentence': {'sentence'}, 'cryptocurrency_iso_code': {'cryptocurrency', 'code', 'iso'}, 'surname': {'surname'}, 'gmt_offset': {'gmt', 'offset'}, 'federal_subject': {'subject', 'federal'}, 'text': {'text'}, 'iata_code': {'code', 'iata'}, 'isd_code': {'isd', 'code'}, 'stock_exchange': {'stock', 'exchange'}, 'duration': {'duration'}, 'height': {'height'}, 'datetime': {'datetime'}, 'timestamp': {'timestamp'}, 'calling_code': {'code', 'calling'}, 'postal_code': {'code', 'postal'}, 'price_in_btc': {'price', 'btc', 'in'}, 'week_date': {'week', 'date'}, 'answer': {'answer'}, 'address': {'address'}, 'prefecture': {'prefecture'}, 'continent': {'continent'}, 'telephone': {'telephone'}, 'province': {'province'}, 'street_name': {'street', 'name'}, 'timezone': {'timezone'}, 'periodicity': {'periodicity'}, 'cryptocurrency_symbol': {'cryptocurrency', 'symbol'}, 'day_of_week': {'week', 'day', 'of'}, 'country_emoji_flag': {'country', 'flag', 'emoji'}, 'worldview': {'worldview'}, 'state': {'state'}, 'city': {'city'}, 'sex': {'sex'}, 'password': {'password'}, 'country': {'country'}, 'full_name': {'full', 'name'}, 'rgb_color': {'color', 'rgb'}, 'nationality': {'nationality'}, 'price': {'price'}, 'gender_symbol': {'symbol', 'gender'}, 'last_name': {'last', 'name'}, 'vegetable': {'vegetable'}, 'dish': {'dish'}, 'country_code': {'country', 'code'}, 'default_country': {'country', 'default'}, 'quote': {'quote'}, 'drink': {'drink'}, 'gender_code': {'code', 'gender'}, 'formatted_datetime': {'formatted', 'datetime'}, 'words': {'words'}, 'color': {'color'}, 'weight': {'weight'}, 'gender': {'gender'}, 'formatted_date': {'date', 'formatted'}, 'currency_iso_code': {'iso', 'code', 'currency'}, 'company_type': {'type', 'company'}, 'latitude': {'latitude'}, 'stock_ticker': {'stock', 'ticker'}, 'username': {'username'}, 'formatted_time': {'time', 'formatted'}, 'occupation': {'occupation'}, 'academic_degree': {'academic', 'degree'}, 'blood_type': {'blood', 'type'}, 'fruit': {'fruit'}, 'zip_code': {'code', 'zip'}, 'emoji': {'emoji'}, 'hex_color': {'color', 'hex'}, 'company': {'company'}, 'political_views': {'views', 'political'}, 'bank': {'bank'}, 'phone_number': {'phone', 'number'}, 'name': {'name'}, 'first_name': {'first', 'name'}, 'year': {'year'}, 'longitude': {'longitude'}, 'icao_code': {'icao', 'code'}, 'date': {'date'}, 'currency_symbol': {'symbol', 'currency'}, 'month': {'month'}, 'street_suffix': {'suffix', 'street'}, 'stock_name': {'stock', 'name'}, 'time': {'time'}, 'title': {'title'}, 'views_on': {'views', 'on'}, 'level': {'level'}}
    },
    'mixed' : {
        'word_list': ['doi', 'day_of_month', 'user_agent', 'street_number', 'random_digit_or_empty', 'current_country', 'random_digit_not_null_or_empty', 'file_path', 'iata_code', 'isd_code', 'passport_full', 'postalcode_in_state', 'stock_exchange', 'random_digit_above_two', 'cryptocurrency_name', 'items', 'postcode_in_state', 'date_time_between_dates', 'week_date', 'telephone', 'periodicity', 'company_email', 'day_of_week', 'random_number', 'nic_handle', 'file_name', 'suffix_nonbinary', 'password', 'windows_platform_token', 'safari', 'catch_phrase', 'random_sample', 'price', 'uri_path', 'unix_partition', 'dish', 'date_time_between', 'country_code', 'ean8', 'ein', 'drink', 'words', 'gender', 'get_words_list', 'slug', 'building_number', 'date_this_century', 'ascii_email', 'json', 'city_suffix', 'date_between_dates', 'random_element', 'fruit', 'binary', 'future_date', 'credit_card_provider', 'passport_number', 'postalcode', 'name', 'administrative_unit', 'random_elements', 'uri', 'iana_id', 'suffix_female', 'date_of_birth', 'month', 'free_email', 'street_suffix', 'random_digit', 'stock_name', 'prefix', 'views_on', 'date_this_year', 'null_boolean', 'ean13', 'ripe_id', 'port_number', 'zipcode_in_state', 'pystruct', 'prefix_nonbinary', 'mac_processor', 'date_this_decade', 'get_current_locale', 'past_datetime', 'birthdate', 'sentence', 'prefix_female', 'cryptocurrency_iso_code', 'street_address', 'pystr', 'prefix_male', 'passport_gender', 'text', 'state_abbr', 'numerify', 'job', 'currency', 'job_female', 'sentences', 'hostname', 'company_suffix', 'calling_code', 'safe_domain_name', 'price_in_btc', 'answer', 'isbn10', 'continent', 'swift11', 'texts', 'street_name', 'get_providers', 'currency_code', 'ascii_free_email', 'bs', 'passport_owner', 'city', 'sex', 'localized_ean8', 'rgb_color', 'domain_word', 'random_letters', 'pystr_format', 'profile', 'upc_e', 'ipv6', 'gender_symbol', 'last_name', 'pricetag', 'currency_name', 'vegetable', 'future_datetime', 'pyint', 'pyfloat', 'color', 'tar', 'formatted_date', 'currency_iso_code', 'file_extension', 'latitude', 'unix_time', 'csv', 'occupation', 'postcode', 'nic_handles', 'linux_platform_token', 'academic_degree', 'blood_type', 'first_name_nonbinary', 'firefox', 'localized_ean13', 'date_time_this_month', 'credit_card_expire', 'upc_a', 'hexify', 'bank', 'coordinate', 'user_name', 'pydecimal', 'cryptocurrency_code', 'date_time_this_century', 'last_name_male', 'date', 'currency_symbol', 'military_apo', 'level', 'word', 'spices', 'identifier', 'opera', 'mime_type', 'coordinates', 'swift', 'swift8', 'seed_instance', 'email', 'university', 'ean', 'random_digit_not_null', 'invalid_ssn', 'region', 'language', 'credit_card_full', 'surname', 'country_calling_code', 'gmt_offset', 'iban', 'local_latlng', 'random_lowercase_letter', 'safe_hex_color', 'duration', 'time_object', 'msisdn', 'datetime', 'safe_color_name', 'timestamp', 'randomize_nb_elements', 'postal_code', 'passport_dates', 'address', 'date_time_this_year', 'last_name_nonbinary', 'military_ship', 'paragraphs', 'timezone', 'province', 'pytimezone', 'cryptocurrency_symbol', 'date_object', 'sbn9', 'language_name', 'iso8601', 'ascii_safe_email', 'uri_extension', 'http_method', 'color_hsv', 'date_time_this_decade', 'name_nonbinary', 'pylist', 'itin', 'random_choices', 'full_name', 'latlng', 'nationality', 'localized_ean', 'mac_address', 'image_url', 'month_name', 'basic_phone_number', 'mac_platform_token', 'bban', 'json_bytes', 'fixed_width', 'formatted_datetime', 'suffix', 'company_type', 'stock_ticker', 'username', 'formatted_time', 'pyiterable', 'pybool', 'first_name_female', 'rgb_css_color', 'zipcode', 'android_platform_token', 'domain_name', 'url', 'credit_card_security_code', 'current_country_code', 'military_dpo', 'emoji', 'ascii_company_email', 'uuid4', 'ipv4_public', 'date_between', 'date_this_month', 'internet_explorer', 'name_female', 'ipv4_private', 'pyobject', 'linux_processor', 'color_rgb_float', 'isbn13', 'http_status_code', 'zipcode_plus4', 'color_hsl', 'color_rgb', 'psv', 'city_prefix', 'century', 'unix_device', 'alphabet', 'language_code', 'vin', 'free_email_domain', 'am_pm', 'reseed', 'location_on_land', 'bank_country', 'uri_page', 'safe_email', 'color_name', 'federal_subject', 'dsv', 'time_series', 'dga', 'tld', 'height', 'md5', 'cryptocurrency', 'pytuple', 'prefecture', 'first_name_male', 'random_letter', 'sha256', 'job_male', 'country_emoji_flag', 'last_name_female', 'license_plate', 'date_time', 'zip', 'tsv', 'worldview', 'military_state', 'postalcode_plus4', 'locale', 'date_time_ad', 'random_uppercase_letter', 'state', 'country', 'boolean', 'ipv4_network_class', 'sha1', 'paragraph', 'default_country', 'random_int', 'quote', 'ios_platform_token', 'gender_code', 'aba', 'weight', 'pyset', 'suffix_male', 'credit_card_number', 'time_delta', 'name_male', 'bothify', 'zip_code', 'ssn', 'hex_color', 'company', 'political_views', 'lexify', 'phone_number', 'ipv4', 'first_name', 'past_date', 'year', 'longitude', 'icao_code', 'passport_dob', 'time', 'title', 'chrome', 'simple_profile', 'secondary_address', 'pydict'],
        'word_tokens': {'doi': ['doi'], 'day_of_month': ['day', 'of', 'month'], 'user_agent': ['user', 'agent'], 'street_number': ['street', 'number'], 'random_digit_or_empty': ['random', 'digit', 'or', 'empty'], 'current_country': ['current', 'country'], 'random_digit_not_null_or_empty': ['random', 'digit', 'not', 'null', 'or', 'empty'], 'file_path': ['file', 'path'], 'iata_code': ['iata', 'code'], 'isd_code': ['isd', 'code'], 'passport_full': ['passport', 'full'], 'postalcode_in_state': ['postalcode', 'in', 'state'], 'stock_exchange': ['stock', 'exchange'], 'random_digit_above_two': ['random', 'digit', 'above', 'two'], 'cryptocurrency_name': ['cryptocurrency', 'name'], 'items': ['items'], 'postcode_in_state': ['postcode', 'in', 'state'], 'date_time_between_dates': ['date', 'time', 'between', 'dates'], 'week_date': ['week', 'date'], 'telephone': ['telephone'], 'periodicity': ['periodicity'], 'company_email': ['company', 'email'], 'day_of_week': ['day', 'of', 'week'], 'random_number': ['random', 'number'], 'nic_handle': ['nic', 'handle'], 'file_name': ['file', 'name'], 'suffix_nonbinary': ['suffix', 'nonbinary'], 'password': ['password'], 'windows_platform_token': ['windows', 'platform', 'token'], 'safari': ['safari'], 'catch_phrase': ['catch', 'phrase'], 'random_sample': ['random', 'sample'], 'price': ['price'], 'uri_path': ['uri', 'path'], 'unix_partition': ['unix', 'partition'], 'dish': ['dish'], 'date_time_between': ['date', 'time', 'between'], 'country_code': ['country', 'code'], 'ean8': ['ean8'], 'ein': ['ein'], 'drink': ['drink'], 'words': ['words'], 'gender': ['gender'], 'get_words_list': ['get', 'words', 'list'], 'slug': ['slug'], 'building_number': ['building', 'number'], 'date_this_century': ['date', 'this', 'century'], 'ascii_email': ['ascii', 'email'], 'json': ['json'], 'city_suffix': ['city', 'suffix'], 'date_between_dates': ['date', 'between', 'dates'], 'random_element': ['random', 'element'], 'fruit': ['fruit'], 'binary': ['binary'], 'future_date': ['future', 'date'], 'credit_card_provider': ['credit', 'card', 'provider'], 'passport_number': ['passport', 'number'], 'postalcode': ['postalcode'], 'name': ['name'], 'administrative_unit': ['administrative', 'unit'], 'random_elements': ['random', 'elements'], 'uri': ['uri'], 'iana_id': ['iana', 'id'], 'suffix_female': ['suffix', 'female'], 'date_of_birth': ['date', 'of', 'birth'], 'month': ['month'], 'free_email': ['free', 'email'], 'street_suffix': ['street', 'suffix'], 'random_digit': ['random', 'digit'], 'stock_name': ['stock', 'name'], 'prefix': ['prefix'], 'views_on': ['views', 'on'], 'date_this_year': ['date', 'this', 'year'], 'null_boolean': ['null', 'boolean'], 'ean13': ['ean13'], 'ripe_id': ['ripe', 'id'], 'port_number': ['port', 'number'], 'zipcode_in_state': ['zipcode', 'in', 'state'], 'pystruct': ['pystruct'], 'prefix_nonbinary': ['prefix', 'nonbinary'], 'mac_processor': ['mac', 'processor'], 'date_this_decade': ['date', 'this', 'decade'], 'get_current_locale': ['get', 'current', 'locale'], 'past_datetime': ['past', 'datetime'], 'birthdate': ['birthdate'], 'sentence': ['sentence'], 'prefix_female': ['prefix', 'female'], 'cryptocurrency_iso_code': ['cryptocurrency', 'iso', 'code'], 'street_address': ['street', 'address'], 'pystr': ['pystr'], 'prefix_male': ['prefix', 'male'], 'passport_gender': ['passport', 'gender'], 'text': ['text'], 'state_abbr': ['state', 'abbr'], 'numerify': ['numerify'], 'job': ['job'], 'currency': ['currency'], 'job_female': ['job', 'female'], 'sentences': ['sentences'], 'hostname': ['hostname'], 'company_suffix': ['company', 'suffix'], 'calling_code': ['calling', 'code'], 'safe_domain_name': ['safe', 'domain', 'name'], 'price_in_btc': ['price', 'in', 'btc'], 'answer': ['answer'], 'isbn10': ['isbn10'], 'continent': ['continent'], 'swift11': ['swift11'], 'texts': ['texts'], 'street_name': ['street', 'name'], 'get_providers': ['get', 'providers'], 'currency_code': ['currency', 'code'], 'ascii_free_email': ['ascii', 'free', 'email'], 'bs': ['bs'], 'passport_owner': ['passport', 'owner'], 'city': ['city'], 'sex': ['sex'], 'localized_ean8': ['localized', 'ean8'], 'rgb_color': ['rgb', 'color'], 'domain_word': ['domain', 'word'], 'random_letters': ['random', 'letters'], 'pystr_format': ['pystr', 'format'], 'profile': ['profile'], 'upc_e': ['upc', 'e'], 'ipv6': ['ipv6'], 'gender_symbol': ['gender', 'symbol'], 'last_name': ['last', 'name'], 'pricetag': ['pricetag'], 'currency_name': ['currency', 'name'], 'vegetable': ['vegetable'], 'future_datetime': ['future', 'datetime'], 'pyint': ['pyint'], 'pyfloat': ['pyfloat'], 'color': ['color'], 'tar': ['tar'], 'formatted_date': ['formatted', 'date'], 'currency_iso_code': ['currency', 'iso', 'code'], 'file_extension': ['file', 'extension'], 'latitude': ['latitude'], 'unix_time': ['unix', 'time'], 'csv': ['csv'], 'occupation': ['occupation'], 'postcode': ['postcode'], 'nic_handles': ['nic', 'handles'], 'linux_platform_token': ['linux', 'platform', 'token'], 'academic_degree': ['academic', 'degree'], 'blood_type': ['blood', 'type'], 'first_name_nonbinary': ['first', 'name', 'nonbinary'], 'firefox': ['firefox'], 'localized_ean13': ['localized', 'ean13'], 'date_time_this_month': ['date', 'time', 'this', 'month'], 'credit_card_expire': ['credit', 'card', 'expire'], 'upc_a': ['upc', 'a'], 'hexify': ['hexify'], 'bank': ['bank'], 'coordinate': ['coordinate'], 'user_name': ['user', 'name'], 'pydecimal': ['pydecimal'], 'cryptocurrency_code': ['cryptocurrency', 'code'], 'date_time_this_century': ['date', 'time', 'this', 'century'], 'last_name_male': ['last', 'name', 'male'], 'date': ['date'], 'currency_symbol': ['currency', 'symbol'], 'military_apo': ['military', 'apo'], 'level': ['level'], 'word': ['word'], 'spices': ['spices'], 'identifier': ['identifier'], 'opera': ['opera'], 'mime_type': ['mime', 'type'], 'coordinates': ['coordinates'], 'swift': ['swift'], 'swift8': ['swift8'], 'seed_instance': ['seed', 'instance'], 'email': ['email'], 'university': ['university'], 'ean': ['ean'], 'random_digit_not_null': ['random', 'digit', 'not', 'null'], 'invalid_ssn': ['invalid', 'ssn'], 'region': ['region'], 'language': ['language'], 'credit_card_full': ['credit', 'card', 'full'], 'surname': ['surname'], 'country_calling_code': ['country', 'calling', 'code'], 'gmt_offset': ['gmt', 'offset'], 'iban': ['iban'], 'local_latlng': ['local', 'latlng'], 'random_lowercase_letter': ['random', 'lowercase', 'letter'], 'safe_hex_color': ['safe', 'hex', 'color'], 'duration': ['duration'], 'time_object': ['time', 'object'], 'msisdn': ['msisdn'], 'datetime': ['datetime'], 'safe_color_name': ['safe', 'color', 'name'], 'timestamp': ['timestamp'], 'randomize_nb_elements': ['randomize', 'nb', 'elements'], 'postal_code': ['postal', 'code'], 'passport_dates': ['passport', 'dates'], 'address': ['address'], 'date_time_this_year': ['date', 'time', 'this', 'year'], 'last_name_nonbinary': ['last', 'name', 'nonbinary'], 'military_ship': ['military', 'ship'], 'paragraphs': ['paragraphs'], 'timezone': ['timezone'], 'province': ['province'], 'pytimezone': ['pytimezone'], 'cryptocurrency_symbol': ['cryptocurrency', 'symbol'], 'date_object': ['date', 'object'], 'sbn9': ['sbn9'], 'language_name': ['language', 'name'], 'iso8601': ['iso8601'], 'ascii_safe_email': ['ascii', 'safe', 'email'], 'uri_extension': ['uri', 'extension'], 'http_method': ['http', 'method'], 'color_hsv': ['color', 'hsv'], 'date_time_this_decade': ['date', 'time', 'this', 'decade'], 'name_nonbinary': ['name', 'nonbinary'], 'pylist': ['pylist'], 'itin': ['itin'], 'random_choices': ['random', 'choices'], 'full_name': ['full', 'name'], 'latlng': ['latlng'], 'nationality': ['nationality'], 'localized_ean': ['localized', 'ean'], 'mac_address': ['mac', 'address'], 'image_url': ['image', 'url'], 'month_name': ['month', 'name'], 'basic_phone_number': ['basic', 'phone', 'number'], 'mac_platform_token': ['mac', 'platform', 'token'], 'bban': ['bban'], 'json_bytes': ['json', 'bytes'], 'fixed_width': ['fixed', 'width'], 'formatted_datetime': ['formatted', 'datetime'], 'suffix': ['suffix'], 'company_type': ['company', 'type'], 'stock_ticker': ['stock', 'ticker'], 'username': ['username'], 'formatted_time': ['formatted', 'time'], 'pyiterable': ['pyiterable'], 'pybool': ['pybool'], 'first_name_female': ['first', 'name', 'female'], 'rgb_css_color': ['rgb', 'css', 'color'], 'zipcode': ['zipcode'], 'android_platform_token': ['android', 'platform', 'token'], 'domain_name': ['domain', 'name'], 'url': ['url'], 'credit_card_security_code': ['credit', 'card', 'security', 'code'], 'current_country_code': ['current', 'country', 'code'], 'military_dpo': ['military', 'dpo'], 'emoji': ['emoji'], 'ascii_company_email': ['ascii', 'company', 'email'], 'uuid4': ['uuid4'], 'ipv4_public': ['ipv4', 'public'], 'date_between': ['date', 'between'], 'date_this_month': ['date', 'this', 'month'], 'internet_explorer': ['internet', 'explorer'], 'name_female': ['name', 'female'], 'ipv4_private': ['ipv4', 'private'], 'pyobject': ['pyobject'], 'linux_processor': ['linux', 'processor'], 'color_rgb_float': ['color', 'rgb', 'float'], 'isbn13': ['isbn13'], 'http_status_code': ['http', 'status', 'code'], 'zipcode_plus4': ['zipcode', 'plus4'], 'color_hsl': ['color', 'hsl'], 'color_rgb': ['color', 'rgb'], 'psv': ['psv'], 'city_prefix': ['city', 'prefix'], 'century': ['century'], 'unix_device': ['unix', 'device'], 'alphabet': ['alphabet'], 'language_code': ['language', 'code'], 'vin': ['vin'], 'free_email_domain': ['free', 'email', 'domain'], 'am_pm': ['am', 'pm'], 'reseed': ['reseed'], 'location_on_land': ['location', 'on', 'land'], 'bank_country': ['bank', 'country'], 'uri_page': ['uri', 'page'], 'safe_email': ['safe', 'email'], 'color_name': ['color', 'name'], 'federal_subject': ['federal', 'subject'], 'dsv': ['dsv'], 'time_series': ['time', 'series'], 'dga': ['dga'], 'tld': ['tld'], 'height': ['height'], 'md5': ['md5'], 'cryptocurrency': ['cryptocurrency'], 'pytuple': ['pytuple'], 'prefecture': ['prefecture'], 'first_name_male': ['first', 'name', 'male'], 'random_letter': ['random', 'letter'], 'sha256': ['sha256'], 'job_male': ['job', 'male'], 'country_emoji_flag': ['country', 'emoji', 'flag'], 'last_name_female': ['last', 'name', 'female'], 'license_plate': ['license', 'plate'], 'date_time': ['date', 'time'], 'zip': ['zip'], 'tsv': ['tsv'], 'worldview': ['worldview'], 'military_state': ['military', 'state'], 'postalcode_plus4': ['postalcode', 'plus4'], 'locale': ['locale'], 'date_time_ad': ['date', 'time', 'ad'], 'random_uppercase_letter': ['random', 'uppercase', 'letter'], 'state': ['state'], 'country': ['country'], 'boolean': ['boolean'], 'ipv4_network_class': ['ipv4', 'network', 'class'], 'sha1': ['sha1'], 'paragraph': ['paragraph'], 'default_country': ['default', 'country'], 'random_int': ['random', 'int'], 'quote': ['quote'], 'ios_platform_token': ['ios', 'platform', 'token'], 'gender_code': ['gender', 'code'], 'aba': ['aba'], 'weight': ['weight'], 'pyset': ['pyset'], 'suffix_male': ['suffix', 'male'], 'credit_card_number': ['credit', 'card', 'number'], 'time_delta': ['time', 'delta'], 'name_male': ['name', 'male'], 'bothify': ['bothify'], 'zip_code': ['zip', 'code'], 'ssn': ['ssn'], 'hex_color': ['hex', 'color'], 'company': ['company'], 'political_views': ['political', 'views'], 'lexify': ['lexify'], 'phone_number': ['phone', 'number'], 'ipv4': ['ipv4'], 'first_name': ['first', 'name'], 'past_date': ['past', 'date'], 'year': ['year'], 'longitude': ['longitude'], 'icao_code': ['icao', 'code'], 'passport_dob': ['passport', 'dob'], 'time': ['time'], 'title': ['title'], 'chrome': ['chrome'], 'simple_profile': ['simple', 'profile'], 'secondary_address': ['secondary', 'address'], 'pydict': ['pydict']},
        'word_tokens_set': {'doi': {'doi'}, 'day_of_month': {'month', 'day', 'of'}, 'user_agent': {'agent', 'user'}, 'street_number': {'street', 'number'}, 'random_digit_or_empty': {'empty', 'or', 'digit', 'random'}, 'current_country': {'current', 'country'}, 'random_digit_not_null_or_empty': {'or', 'not', 'empty', 'null', 'digit', 'random'}, 'file_path': {'path', 'file'}, 'iata_code': {'code', 'iata'}, 'isd_code': {'isd', 'code'}, 'passport_full': {'full', 'passport'}, 'postalcode_in_state': {'in', 'postalcode', 'state'}, 'stock_exchange': {'stock', 'exchange'}, 'random_digit_above_two': {'two', 'above', 'digit', 'random'}, 'cryptocurrency_name': {'cryptocurrency', 'name'}, 'items': {'items'}, 'postcode_in_state': {'in', 'state', 'postcode'}, 'date_time_between_dates': {'time', 'date', 'between', 'dates'}, 'week_date': {'week', 'date'}, 'telephone': {'telephone'}, 'periodicity': {'periodicity'}, 'company_email': {'company', 'email'}, 'day_of_week': {'week', 'day', 'of'}, 'random_number': {'number', 'random'}, 'nic_handle': {'handle', 'nic'}, 'file_name': {'name', 'file'}, 'suffix_nonbinary': {'suffix', 'nonbinary'}, 'password': {'password'}, 'windows_platform_token': {'windows', 'token', 'platform'}, 'safari': {'safari'}, 'catch_phrase': {'catch', 'phrase'}, 'random_sample': {'sample', 'random'}, 'price': {'price'}, 'uri_path': {'path', 'uri'}, 'unix_partition': {'partition', 'unix'}, 'dish': {'dish'}, 'date_time_between': {'time', 'date', 'between'}, 'country_code': {'country', 'code'}, 'ean8': {'ean8'}, 'ein': {'ein'}, 'drink': {'drink'}, 'words': {'words'}, 'gender': {'gender'}, 'get_words_list': {'get', 'list', 'words'}, 'slug': {'slug'}, 'building_number': {'number', 'building'}, 'date_this_century': {'century', 'date', 'this'}, 'ascii_email': {'email', 'ascii'}, 'json': {'json'}, 'city_suffix': {'suffix', 'city'}, 'date_between_dates': {'date', 'between', 'dates'}, 'random_element': {'element', 'random'}, 'fruit': {'fruit'}, 'binary': {'binary'}, 'future_date': {'date', 'future'}, 'credit_card_provider': {'credit', 'card', 'provider'}, 'passport_number': {'number', 'passport'}, 'postalcode': {'postalcode'}, 'name': {'name'}, 'administrative_unit': {'administrative', 'unit'}, 'random_elements': {'elements', 'random'}, 'uri': {'uri'}, 'iana_id': {'iana', 'id'}, 'suffix_female': {'suffix', 'female'}, 'date_of_birth': {'date', 'birth', 'of'}, 'month': {'month'}, 'free_email': {'free', 'email'}, 'street_suffix': {'suffix', 'street'}, 'random_digit': {'digit', 'random'}, 'stock_name': {'stock', 'name'}, 'prefix': {'prefix'}, 'views_on': {'views', 'on'}, 'date_this_year': {'year', 'date', 'this'}, 'null_boolean': {'null', 'boolean'}, 'ean13': {'ean13'}, 'ripe_id': {'ripe', 'id'}, 'port_number': {'port', 'number'}, 'zipcode_in_state': {'in', 'state', 'zipcode'}, 'pystruct': {'pystruct'}, 'prefix_nonbinary': {'prefix', 'nonbinary'}, 'mac_processor': {'mac', 'processor'}, 'date_this_decade': {'decade', 'date', 'this'}, 'get_current_locale': {'current', 'get', 'locale'}, 'past_datetime': {'past', 'datetime'}, 'birthdate': {'birthdate'}, 'sentence': {'sentence'}, 'prefix_female': {'prefix', 'female'}, 'cryptocurrency_iso_code': {'cryptocurrency', 'code', 'iso'}, 'street_address': {'address', 'street'}, 'pystr': {'pystr'}, 'prefix_male': {'male', 'prefix'}, 'passport_gender': {'gender', 'passport'}, 'text': {'text'}, 'state_abbr': {'state', 'abbr'}, 'numerify': {'numerify'}, 'job': {'job'}, 'currency': {'currency'}, 'job_female': {'job', 'female'}, 'sentences': {'sentences'}, 'hostname': {'hostname'}, 'company_suffix': {'suffix', 'company'}, 'calling_code': {'code', 'calling'}, 'safe_domain_name': {'domain', 'safe', 'name'}, 'price_in_btc': {'price', 'btc', 'in'}, 'answer': {'answer'}, 'isbn10': {'isbn10'}, 'continent': {'continent'}, 'swift11': {'swift11'}, 'texts': {'texts'}, 'street_name': {'street', 'name'}, 'get_providers': {'get', 'providers'}, 'currency_code': {'code', 'currency'}, 'ascii_free_email': {'free', 'email', 'ascii'}, 'bs': {'bs'}, 'passport_owner': {'owner', 'passport'}, 'city': {'city'}, 'sex': {'sex'}, 'localized_ean8': {'ean8', 'localized'}, 'rgb_color': {'color', 'rgb'}, 'domain_word': {'domain', 'word'}, 'random_letters': {'letters', 'random'}, 'pystr_format': {'format', 'pystr'}, 'profile': {'profile'}, 'upc_e': {'upc', 'e'}, 'ipv6': {'ipv6'}, 'gender_symbol': {'symbol', 'gender'}, 'last_name': {'last', 'name'}, 'pricetag': {'pricetag'}, 'currency_name': {'name', 'currency'}, 'vegetable': {'vegetable'}, 'future_datetime': {'future', 'datetime'}, 'pyint': {'pyint'}, 'pyfloat': {'pyfloat'}, 'color': {'color'}, 'tar': {'tar'}, 'formatted_date': {'date', 'formatted'}, 'currency_iso_code': {'iso', 'code', 'currency'}, 'file_extension': {'extension', 'file'}, 'latitude': {'latitude'}, 'unix_time': {'time', 'unix'}, 'csv': {'csv'}, 'occupation': {'occupation'}, 'postcode': {'postcode'}, 'nic_handles': {'handles', 'nic'}, 'linux_platform_token': {'linux', 'token', 'platform'}, 'academic_degree': {'academic', 'degree'}, 'blood_type': {'blood', 'type'}, 'first_name_nonbinary': {'first', 'name', 'nonbinary'}, 'firefox': {'firefox'}, 'localized_ean13': {'ean13', 'localized'}, 'date_time_this_month': {'month', 'time', 'date', 'this'}, 'credit_card_expire': {'credit', 'card', 'expire'}, 'upc_a': {'a', 'upc'}, 'hexify': {'hexify'}, 'bank': {'bank'}, 'coordinate': {'coordinate'}, 'user_name': {'name', 'user'}, 'pydecimal': {'pydecimal'}, 'cryptocurrency_code': {'cryptocurrency', 'code'}, 'date_time_this_century': {'century', 'time', 'date', 'this'}, 'last_name_male': {'last', 'male', 'name'}, 'date': {'date'}, 'currency_symbol': {'symbol', 'currency'}, 'military_apo': {'military', 'apo'}, 'level': {'level'}, 'word': {'word'}, 'spices': {'spices'}, 'identifier': {'identifier'}, 'opera': {'opera'}, 'mime_type': {'type', 'mime'}, 'coordinates': {'coordinates'}, 'swift': {'swift'}, 'swift8': {'swift8'}, 'seed_instance': {'instance', 'seed'}, 'email': {'email'}, 'university': {'university'}, 'ean': {'ean'}, 'random_digit_not_null': {'null', 'not', 'digit', 'random'}, 'invalid_ssn': {'invalid', 'ssn'}, 'region': {'region'}, 'language': {'language'}, 'credit_card_full': {'credit', 'full', 'card'}, 'surname': {'surname'}, 'country_calling_code': {'country', 'code', 'calling'}, 'gmt_offset': {'gmt', 'offset'}, 'iban': {'iban'}, 'local_latlng': {'local', 'latlng'}, 'random_lowercase_letter': {'letter', 'lowercase', 'random'}, 'safe_hex_color': {'color', 'safe', 'hex'}, 'duration': {'duration'}, 'time_object': {'time', 'object'}, 'msisdn': {'msisdn'}, 'datetime': {'datetime'}, 'safe_color_name': {'color', 'safe', 'name'}, 'timestamp': {'timestamp'}, 'randomize_nb_elements': {'elements', 'randomize', 'nb'}, 'postal_code': {'code', 'postal'}, 'passport_dates': {'passport', 'dates'}, 'address': {'address'}, 'date_time_this_year': {'year', 'time', 'date', 'this'}, 'last_name_nonbinary': {'last', 'name', 'nonbinary'}, 'military_ship': {'military', 'ship'}, 'paragraphs': {'paragraphs'}, 'timezone': {'timezone'}, 'province': {'province'}, 'pytimezone': {'pytimezone'}, 'cryptocurrency_symbol': {'cryptocurrency', 'symbol'}, 'date_object': {'date', 'object'}, 'sbn9': {'sbn9'}, 'language_name': {'language', 'name'}, 'iso8601': {'iso8601'}, 'ascii_safe_email': {'safe', 'email', 'ascii'}, 'uri_extension': {'uri', 'extension'}, 'http_method': {'http', 'method'}, 'color_hsv': {'color', 'hsv'}, 'date_time_this_decade': {'decade', 'time', 'date', 'this'}, 'name_nonbinary': {'name', 'nonbinary'}, 'pylist': {'pylist'}, 'itin': {'itin'}, 'random_choices': {'choices', 'random'}, 'full_name': {'full', 'name'}, 'latlng': {'latlng'}, 'nationality': {'nationality'}, 'localized_ean': {'ean', 'localized'}, 'mac_address': {'address', 'mac'}, 'image_url': {'image', 'url'}, 'month_name': {'month', 'name'}, 'basic_phone_number': {'phone', 'basic', 'number'}, 'mac_platform_token': {'mac', 'token', 'platform'}, 'bban': {'bban'}, 'json_bytes': {'bytes', 'json'}, 'fixed_width': {'width', 'fixed'}, 'formatted_datetime': {'formatted', 'datetime'}, 'suffix': {'suffix'}, 'company_type': {'type', 'company'}, 'stock_ticker': {'stock', 'ticker'}, 'username': {'username'}, 'formatted_time': {'time', 'formatted'}, 'pyiterable': {'pyiterable'}, 'pybool': {'pybool'}, 'first_name_female': {'first', 'female', 'name'}, 'rgb_css_color': {'color', 'rgb', 'css'}, 'zipcode': {'zipcode'}, 'android_platform_token': {'android', 'token', 'platform'}, 'domain_name': {'domain', 'name'}, 'url': {'url'}, 'credit_card_security_code': {'credit', 'card', 'code', 'security'}, 'current_country_code': {'current', 'country', 'code'}, 'military_dpo': {'military', 'dpo'}, 'emoji': {'emoji'}, 'ascii_company_email': {'company', 'email', 'ascii'}, 'uuid4': {'uuid4'}, 'ipv4_public': {'ipv4', 'public'}, 'date_between': {'date', 'between'}, 'date_this_month': {'month', 'date', 'this'}, 'internet_explorer': {'internet', 'explorer'}, 'name_female': {'female', 'name'}, 'ipv4_private': {'private', 'ipv4'}, 'pyobject': {'pyobject'}, 'linux_processor': {'linux', 'processor'}, 'color_rgb_float': {'color', 'rgb', 'float'}, 'isbn13': {'isbn13'}, 'http_status_code': {'status', 'http', 'code'}, 'zipcode_plus4': {'plus4', 'zipcode'}, 'color_hsl': {'color', 'hsl'}, 'color_rgb': {'color', 'rgb'}, 'psv': {'psv'}, 'city_prefix': {'prefix', 'city'}, 'century': {'century'}, 'unix_device': {'device', 'unix'}, 'alphabet': {'alphabet'}, 'language_code': {'language', 'code'}, 'vin': {'vin'}, 'free_email_domain': {'domain', 'free', 'email'}, 'am_pm': {'pm', 'am'}, 'reseed': {'reseed'}, 'location_on_land': {'location', 'on', 'land'}, 'bank_country': {'country', 'bank'}, 'uri_page': {'page', 'uri'}, 'safe_email': {'safe', 'email'}, 'color_name': {'color', 'name'}, 'federal_subject': {'subject', 'federal'}, 'dsv': {'dsv'}, 'time_series': {'time', 'series'}, 'dga': {'dga'}, 'tld': {'tld'}, 'height': {'height'}, 'md5': {'md5'}, 'cryptocurrency': {'cryptocurrency'}, 'pytuple': {'pytuple'}, 'prefecture': {'prefecture'}, 'first_name_male': {'male', 'first', 'name'}, 'random_letter': {'letter', 'random'}, 'sha256': {'sha256'}, 'job_male': {'male', 'job'}, 'country_emoji_flag': {'country', 'flag', 'emoji'}, 'last_name_female': {'last', 'female', 'name'}, 'license_plate': {'license', 'plate'}, 'date_time': {'time', 'date'}, 'zip': {'zip'}, 'tsv': {'tsv'}, 'worldview': {'worldview'}, 'military_state': {'military', 'state'}, 'postalcode_plus4': {'postalcode', 'plus4'}, 'locale': {'locale'}, 'date_time_ad': {'ad', 'time', 'date'}, 'random_uppercase_letter': {'letter', 'uppercase', 'random'}, 'state': {'state'}, 'country': {'country'}, 'boolean': {'boolean'}, 'ipv4_network_class': {'network', 'class', 'ipv4'}, 'sha1': {'sha1'}, 'paragraph': {'paragraph'}, 'default_country': {'country', 'default'}, 'random_int': {'int', 'random'}, 'quote': {'quote'}, 'ios_platform_token': {'ios', 'token', 'platform'}, 'gender_code': {'code', 'gender'}, 'aba': {'aba'}, 'weight': {'weight'}, 'pyset': {'pyset'}, 'suffix_male': {'male', 'suffix'}, 'credit_card_number': {'credit', 'card', 'number'}, 'time_delta': {'delta', 'time'}, 'name_male': {'male', 'name'}, 'bothify': {'bothify'}, 'zip_code': {'code', 'zip'}, 'ssn': {'ssn'}, 'hex_color': {'color', 'hex'}, 'company': {'company'}, 'political_views': {'views', 'political'}, 'lexify': {'lexify'}, 'phone_number': {'phone', 'number'}, 'ipv4': {'ipv4'}, 'first_name': {'first', 'name'}, 'past_date': {'date', 'past'}, 'year': {'year'}, 'longitude': {'longitude'}, 'icao_code': {'icao', 'code'}, 'passport_dob': {'dob', 'passport'}, 'time': {'time'}, 'title': {'title'}, 'chrome': {'chrome'}, 'simple_profile': {'simple', 'profile'}, 'secondary_address': {'secondary', 'address'}, 'pydict': {'pydict'}}
    },
}

python_builtin_types = {
    str,
    int,
    float,
    Decimal,
    bool,
    complex,
    bytes,
    tuple,
    list,
    set,
    frozenset,
    dict,
}
typing_origins = {List, Dict, Tuple, Set, Union, Literal, Optional}
recursive_types = {
    List,
    Dict,
    Tuple,
    Set,
    Union,
    Literal,
    Optional,
    list,
    dict,
    tuple,
    set,
    frozenset,
}
all_constr_attribs = {
    "default",
    "annotation",
    "min_length",
    "max_length",
    "pattern",
    "gt",
    "lt",
    "ge",
    "le",
    "multiple_of",
}

default_constr_dict = {
    "required": True,
    "default": None,
    "annotation": None,
    "min_length": None,
    "max_length": None,
    "pattern": None,
    "gt": None,
    "lt": None,
    "ge": None,
    "le": None,
    "multiple_of": None,
    "origin": None,
    "args": None,
}
        