from typing import List, Dict, Tuple, Set, Union, Literal, Optional, Any

from decimal import Decimal

from faker import Faker
import mimesis
from mimesis import Generic
import inspect
                
                
provider_return_types = {
    'Meta' : str,
    'aba' : str,
    'academic_degree' : str,
    'address' : str,
    'administrative_unit' : str,
    'alphabet' : list,
    'am_pm' : str,
    'android_platform_token' : str,
    'answer' : str,
    'ascii_company_email' : str,
    'ascii_email' : str,
    'ascii_free_email' : str,
    'ascii_safe_email' : str,
    'bank' : str,
    'bank_country' : str,
    'basic_phone_number' : str,
    'bban' : str,
    'binary' : bytes,
    'birthdate' : str,
    'blood_type' : str,
    'boolean' : str,
    'bothify' : str,
    'bs' : str,
    'building_number' : str,
    'calling_code' : str,
    'catch_phrase' : str,
    'century' : str,
    'chrome' : str,
    'city' : str,
    'city_prefix' : str,
    'city_suffix' : str,
    'color' : str,
    'color_hsl' : tuple,
    'color_hsv' : tuple,
    'color_name' : str,
    'color_rgb' : tuple,
    'color_rgb_float' : tuple,
    'company' : str,
    'company_email' : str,
    'company_suffix' : str,
    'company_type' : str,
    'continent' : str,
    'coordinate' : str,
    'coordinates' : dict,
    'country' : str,
    'country_calling_code' : str,
    'country_code' : str,
    'country_emoji_flag' : str,
    'credit_card_expire' : str,
    'credit_card_full' : str,
    'credit_card_number' : str,
    'credit_card_provider' : str,
    'credit_card_security_code' : str,
    'cryptocurrency' : tuple,
    'cryptocurrency_code' : str,
    'cryptocurrency_iso_code' : str,
    'cryptocurrency_name' : str,
    'cryptocurrency_symbol' : str,
    'csv' : str,
    'currency' : tuple,
    'currency_code' : str,
    'currency_iso_code' : str,
    'currency_name' : str,
    'currency_symbol' : str,
    'current_country' : str,
    'current_country_code' : str,
    'date' : str,
    'date_between' : str,
    'date_between_dates' : str,
    'date_object' : str,
    'date_of_birth' : str,
    'date_this_century' : str,
    'date_this_decade' : str,
    'date_this_month' : str,
    'date_this_year' : str,
    'date_time' : str,
    'date_time_ad' : str,
    'date_time_between' : str,
    'date_time_between_dates' : str,
    'date_time_this_century' : str,
    'date_time_this_decade' : str,
    'date_time_this_month' : str,
    'date_time_this_year' : str,
    'datetime' : str,
    'day_of_month' : str,
    'day_of_week' : str,
    'default_country' : str,
    'dga' : str,
    'dish' : str,
    'doi' : str,
    'domain_name' : str,
    'domain_word' : str,
    'drink' : str,
    'dsv' : str,
    'duration' : str,
    'ean' : str,
    'ean13' : str,
    'ean8' : str,
    'ein' : str,
    'email' : str,
    'emoji' : str,
    'federal_subject' : str,
    'file_extension' : str,
    'file_name' : str,
    'file_path' : str,
    'firefox' : str,
    'first_name' : str,
    'first_name_female' : str,
    'first_name_male' : str,
    'first_name_nonbinary' : str,
    'fixed_width' : str,
    'formatted_date' : str,
    'formatted_datetime' : str,
    'formatted_time' : str,
    'free_email' : str,
    'free_email_domain' : str,
    'fruit' : str,
    'full_name' : str,
    'future_date' : str,
    'future_datetime' : str,
    'gender' : str,
    'gender_code' : str,
    'gender_symbol' : str,
    'get_current_locale' : str,
    'get_providers' : list,
    'get_words_list' : list,
    'gmt_offset' : str,
    'height' : str,
    'hex_color' : str,
    'hexify' : str,
    'hostname' : str,
    'http_method' : str,
    'http_status_code' : str,
    'iana_id' : str,
    'iata_code' : str,
    'iban' : str,
    'icao_code' : str,
    'identifier' : str,
    'image_url' : str,
    'internet_explorer' : str,
    'invalid_ssn' : str,
    'ios_platform_token' : str,
    'ipv4' : str,
    'ipv4_network_class' : str,
    'ipv4_private' : str,
    'ipv4_public' : str,
    'ipv6' : str,
    'isbn10' : str,
    'isbn13' : str,
    'isd_code' : str,
    'iso8601' : str,
    'items' : list,
    'itin' : str,
    'job' : str,
    'job_female' : str,
    'job_male' : str,
    'json' : str,
    'json_bytes' : bytes,
    'language' : str,
    'language_code' : str,
    'language_name' : str,
    'last_name' : str,
    'last_name_female' : str,
    'last_name_male' : str,
    'last_name_nonbinary' : str,
    'latitude' : str,
    'latlng' : tuple,
    'level' : str,
    'lexify' : str,
    'license_plate' : str,
    'linux_platform_token' : str,
    'linux_processor' : str,
    'local_latlng' : tuple,
    'locale' : str,
    'localized_ean' : str,
    'localized_ean13' : str,
    'localized_ean8' : str,
    'location_on_land' : tuple,
    'longitude' : str,
    'mac_address' : str,
    'mac_platform_token' : str,
    'mac_processor' : str,
    'md5' : str,
    'military_apo' : str,
    'military_dpo' : str,
    'military_ship' : str,
    'military_state' : str,
    'mime_type' : str,
    'month' : str,
    'month_name' : str,
    'msisdn' : str,
    'name' : str,
    'name_female' : str,
    'name_male' : str,
    'name_nonbinary' : str,
    'nationality' : str,
    'nic_handle' : str,
    'nic_handles' : list,
    'null_boolean' : str,
    'numerify' : str,
    'occupation' : str,
    'opera' : str,
    'paragraph' : str,
    'paragraphs' : list,
    'passport_dates' : tuple,
    'passport_dob' : str,
    'passport_full' : str,
    'passport_gender' : str,
    'passport_number' : str,
    'passport_owner' : tuple,
    'password' : str,
    'past_date' : str,
    'past_datetime' : str,
    'periodicity' : str,
    'phone_number' : str,
    'political_views' : str,
    'port_number' : str,
    'postal_code' : str,
    'postalcode' : str,
    'postalcode_in_state' : str,
    'postalcode_plus4' : str,
    'postcode' : str,
    'postcode_in_state' : str,
    'prefecture' : str,
    'prefix' : str,
    'prefix_female' : str,
    'prefix_male' : str,
    'prefix_nonbinary' : str,
    'price' : str,
    'price_in_btc' : str,
    'pricetag' : str,
    'profile' : dict,
    'province' : str,
    'psv' : str,
    'pybool' : str,
    'pydecimal' : str,
    'pydict' : dict,
    'pyfloat' : str,
    'pyint' : str,
    'pyiterable' : list,
    'pylist' : list,
    'pyobject' : str,
    'pyset' : set,
    'pystr' : str,
    'pystr_format' : str,
    'pystruct' : tuple,
    'pytimezone' : str,
    'pytuple' : tuple,
    'quote' : str,
    'random_choices' : list,
    'random_digit' : str,
    'random_digit_above_two' : str,
    'random_digit_not_null' : str,
    'random_digit_not_null_or_empty' : str,
    'random_digit_or_empty' : str,
    'random_element' : str,
    'random_elements' : list,
    'random_int' : str,
    'random_letter' : str,
    'random_letters' : list,
    'random_lowercase_letter' : str,
    'random_number' : str,
    'random_sample' : list,
    'random_uppercase_letter' : str,
    'randomize_nb_elements' : str,
    'region' : str,
    'reseed' : str,
    'rgb_color' : tuple,
    'rgb_css_color' : str,
    'ripe_id' : str,
    'safari' : str,
    'safe_color_name' : str,
    'safe_domain_name' : str,
    'safe_email' : str,
    'safe_hex_color' : str,
    'sbn9' : str,
    'secondary_address' : str,
    'seed_instance' : str,
    'sentence' : str,
    'sentences' : list,
    'sex' : str,
    'sha1' : str,
    'sha256' : str,
    'simple_profile' : dict,
    'slug' : str,
    'spices' : str,
    'ssn' : str,
    'state' : str,
    'state_abbr' : str,
    'stock_exchange' : str,
    'stock_name' : str,
    'stock_ticker' : str,
    'street_address' : str,
    'street_name' : str,
    'street_number' : str,
    'street_suffix' : str,
    'suffix' : str,
    'suffix_female' : str,
    'suffix_male' : str,
    'suffix_nonbinary' : str,
    'surname' : str,
    'swift' : str,
    'swift11' : str,
    'swift8' : str,
    'tar' : bytes,
    'telephone' : str,
    'text' : str,
    'texts' : list,
    'time' : str,
    'time_delta' : str,
    'time_object' : str,
    'time_series' : str,
    'timestamp' : str,
    'timezone' : str,
    'title' : str,
    'tld' : str,
    'tsv' : str,
    'university' : str,
    'unix_device' : str,
    'unix_partition' : str,
    'unix_time' : str,
    'upc_a' : str,
    'upc_e' : str,
    'uri' : str,
    'uri_extension' : str,
    'uri_page' : str,
    'uri_path' : str,
    'url' : str,
    'user_agent' : str,
    'user_name' : str,
    'username' : str,
    'uuid4' : str,
    'vegetable' : str,
    'views_on' : str,
    'vin' : str,
    'week_date' : str,
    'weight' : str,
    'windows_platform_token' : str,
    'word' : str,
    'words' : list,
    'worldview' : str,
    'year' : str,
    'zip' : bytes,
    'zip_code' : str,
    'zipcode' : str,
    'zipcode_in_state' : str,
    'zipcode_plus4' : str,
}
provider_methods = {
    'faker' : {
        'word_list': ['ipv6', 'military_ship', 'date_between', 'random_letter', 'hostname', 'passport_gender', 'psv', 'secondary_address', 'unix_device', 'mime_type', 'date_time_ad', 'prefix', 'random_element', 'ipv4_network_class', 'format', 'time_object', 'century', 'city_suffix', 'http_method', 'port_number', 'credit_card_provider', 'latlng', 'phone_number', 'am_pm', 'date_time_this_century', 'bban', 'pystruct', 'http_status_code', 'last_name_male', 'unix_time', 'color_hsv', 'rgb_css_color', 'simple_profile', 'safe_color_name', 'localized_ean', 'locale', 'password', 'date_this_century', 'bs', 'windows_platform_token', 'random_digit_not_null_or_empty', 'random_digit', 'boolean', 'local_latlng', 'credit_card_expire', 'random_digit_above_two', 'texts', 'ios_platform_token', 'nic_handles', 'job', 'nic_handle', 'past_date', 'set_formatter', 'iana_id', 'sentences', 'date_this_year', 'name_nonbinary', 'job_male', 'swift8', 'localized_ean13', 'domain_word', 'text', 'uri_page', 'emoji', 'file_path', 'job_female', 'sha256', 'invalid_ssn', 'set_arguments', 'first_name', 'company', 'date', 'postcode', 'iso8601', 'license_plate', 'internet_explorer', 'timezone', 'xml', 'chrome', 'address', 'firefox', 'random_digit_not_null', 'time_series', 'ripe_id', 'military_apo', 'json_bytes', 'msisdn', 'uuid4', 'pystr_format', 'postalcode', 'pybool', 'isbn13', 'ipv4', 'date_time', 'pyfloat', 'month', 'ascii_free_email', 'random_lowercase_letter', 'randomize_nb_elements', 'email', 'zipcode_plus4', 'administrative_unit', 'last_name_female', 'name', 'military_dpo', 'safe_hex_color', 'time', 'dga', 'isbn10', 'cryptocurrency_code', 'ascii_safe_email', 'upc_e', 'hex_color', 'state', 'military_state', 'city', 'day_of_week', 'first_name_female', 'random_digit_or_empty', 'future_datetime', 'street_address', 'safe_email', 'name_female', 'paragraph', 'file_name', 'pytuple', 'street_name', 'color_rgb_float', 'mac_platform_token', 'ascii_company_email', 'date_time_this_month', 'md5', 'ean13', 'ascii_email', 'upc_a', 'rgb_color', 'ean8', 'words', 'credit_card_security_code', 'city_prefix', 'numerify', 'suffix_male', 'passport_owner', 'year', 'state_abbr', 'date_this_decade', 'coordinate', 'random_int', 'suffix_female', 'free_email_domain', 'pydecimal', 'localized_ean8', 'country_code', 'pytimezone', 'currency_symbol', 'tsv', 'get_providers', 'color_hsl', 'json', 'mac_processor', 'date_object', 'prefix_nonbinary', 'parse', 'passport_full', 'safe_domain_name', 'color', 'pylist', 'postalcode_in_state', 'url', 'street_suffix', 'first_name_male', 'paragraphs', 'slug', 'month_name', 'cryptocurrency', 'aba', 'last_name', 'last_name_nonbinary', 'pyiterable', 'zipcode_in_state', 'current_country_code', 'language_name', 'currency_code', 'prefix_female', 'add_provider', 'safari', 'first_name_nonbinary', 'items', 'android_platform_token', 'null_boolean', 'credit_card_number', 'word', 'latitude', 'passport_number', 'sentence', 'sbn9', 'seed_instance', 'mac_address', 'color_name', 'provider', 'suffix_nonbinary', 'get_arguments', 'tar', 'uri', 'get_formatter', 'hexify', 'bothify', 'currency', 'linux_processor', 'del_arguments', 'ean', 'doi', 'cryptocurrency_name', 'uri_path', 'postcode_in_state', 'random_letters', 'ssn', 'bank_country', 'file_extension', 'profile', 'binary', 'date_time_between', 'random_number', 'domain_name', 'vin', 'current_country', 'time_delta', 'postalcode_plus4', 'dsv', 'date_time_between_dates', 'pystr', 'image', 'linux_platform_token', 'unix_partition', 'image_url', 'location_on_land', 'longitude', 'itin', 'date_between_dates', 'random_choices', 'pyint', 'catch_phrase', 'passport_dates', 'company_email', 'zip', 'pydict', 'credit_card_full', 'building_number', 'color_rgb', 'pricetag', 'ipv4_private', 'swift', 'random_uppercase_letter', 'random_sample', 'uri_extension', 'sha1', 'fixed_width', 'csv', 'date_this_month', 'get_words_list', 'name_male', 'passport_dob', 'opera', 'prefix_male', 'enum', 'seed_locale', 'lexify', 'user_agent', 'date_time_this_year', 'random_elements', 'swift11', 'user_name', 'country', 'pyobject', 'date_time_this_decade', 'language_code', 'zipcode', 'ein', 'company_suffix', 'day_of_month', 'past_datetime', 'pyset', 'country_calling_code', 'currency_name', 'free_email', 'ipv4_public', 'tld', 'future_date', 'iban', 'suffix', 'date_of_birth', 'basic_phone_number'],
        'word_tokens': {'ipv6': ['ipv6'], 'military_ship': ['military', 'ship'], 'date_between': ['date', 'between'], 'random_letter': ['random', 'letter'], 'hostname': ['hostname'], 'passport_gender': ['passport', 'gender'], 'psv': ['psv'], 'secondary_address': ['secondary', 'address'], 'unix_device': ['unix', 'device'], 'mime_type': ['mime', 'type'], 'date_time_ad': ['date', 'time', 'ad'], 'prefix': ['prefix'], 'random_element': ['random', 'element'], 'ipv4_network_class': ['ipv4', 'network', 'class'], 'format': ['format'], 'time_object': ['time', 'object'], 'century': ['century'], 'city_suffix': ['city', 'suffix'], 'http_method': ['http', 'method'], 'port_number': ['port', 'number'], 'credit_card_provider': ['credit', 'card', 'provider'], 'latlng': ['latlng'], 'phone_number': ['phone', 'number'], 'am_pm': ['am', 'pm'], 'date_time_this_century': ['date', 'time', 'this', 'century'], 'bban': ['bban'], 'pystruct': ['pystruct'], 'http_status_code': ['http', 'status', 'code'], 'last_name_male': ['last', 'name', 'male'], 'unix_time': ['unix', 'time'], 'color_hsv': ['color', 'hsv'], 'rgb_css_color': ['rgb', 'css', 'color'], 'simple_profile': ['simple', 'profile'], 'safe_color_name': ['safe', 'color', 'name'], 'localized_ean': ['localized', 'ean'], 'locale': ['locale'], 'password': ['password'], 'date_this_century': ['date', 'this', 'century'], 'bs': ['bs'], 'windows_platform_token': ['windows', 'platform', 'token'], 'random_digit_not_null_or_empty': ['random', 'digit', 'not', 'null', 'or', 'empty'], 'random_digit': ['random', 'digit'], 'boolean': ['boolean'], 'local_latlng': ['local', 'latlng'], 'credit_card_expire': ['credit', 'card', 'expire'], 'random_digit_above_two': ['random', 'digit', 'above', 'two'], 'texts': ['texts'], 'ios_platform_token': ['ios', 'platform', 'token'], 'nic_handles': ['nic', 'handles'], 'job': ['job'], 'nic_handle': ['nic', 'handle'], 'past_date': ['past', 'date'], 'set_formatter': ['set', 'formatter'], 'iana_id': ['iana', 'id'], 'sentences': ['sentences'], 'date_this_year': ['date', 'this', 'year'], 'name_nonbinary': ['name', 'nonbinary'], 'job_male': ['job', 'male'], 'swift8': ['swift8'], 'localized_ean13': ['localized', 'ean13'], 'domain_word': ['domain', 'word'], 'text': ['text'], 'uri_page': ['uri', 'page'], 'emoji': ['emoji'], 'file_path': ['file', 'path'], 'job_female': ['job', 'female'], 'sha256': ['sha256'], 'invalid_ssn': ['invalid', 'ssn'], 'set_arguments': ['set', 'arguments'], 'first_name': ['first', 'name'], 'company': ['company'], 'date': ['date'], 'postcode': ['postcode'], 'iso8601': ['iso8601'], 'license_plate': ['license', 'plate'], 'internet_explorer': ['internet', 'explorer'], 'timezone': ['timezone'], 'xml': ['xml'], 'chrome': ['chrome'], 'address': ['address'], 'firefox': ['firefox'], 'random_digit_not_null': ['random', 'digit', 'not', 'null'], 'time_series': ['time', 'series'], 'ripe_id': ['ripe', 'id'], 'military_apo': ['military', 'apo'], 'json_bytes': ['json', 'bytes'], 'msisdn': ['msisdn'], 'uuid4': ['uuid4'], 'pystr_format': ['pystr', 'format'], 'postalcode': ['postalcode'], 'pybool': ['pybool'], 'isbn13': ['isbn13'], 'ipv4': ['ipv4'], 'date_time': ['date', 'time'], 'pyfloat': ['pyfloat'], 'month': ['month'], 'ascii_free_email': ['ascii', 'free', 'email'], 'random_lowercase_letter': ['random', 'lowercase', 'letter'], 'randomize_nb_elements': ['randomize', 'nb', 'elements'], 'email': ['email'], 'zipcode_plus4': ['zipcode', 'plus4'], 'administrative_unit': ['administrative', 'unit'], 'last_name_female': ['last', 'name', 'female'], 'name': ['name'], 'military_dpo': ['military', 'dpo'], 'safe_hex_color': ['safe', 'hex', 'color'], 'time': ['time'], 'dga': ['dga'], 'isbn10': ['isbn10'], 'cryptocurrency_code': ['cryptocurrency', 'code'], 'ascii_safe_email': ['ascii', 'safe', 'email'], 'upc_e': ['upc', 'e'], 'hex_color': ['hex', 'color'], 'state': ['state'], 'military_state': ['military', 'state'], 'city': ['city'], 'day_of_week': ['day', 'of', 'week'], 'first_name_female': ['first', 'name', 'female'], 'random_digit_or_empty': ['random', 'digit', 'or', 'empty'], 'future_datetime': ['future', 'datetime'], 'street_address': ['street', 'address'], 'safe_email': ['safe', 'email'], 'name_female': ['name', 'female'], 'paragraph': ['paragraph'], 'file_name': ['file', 'name'], 'pytuple': ['pytuple'], 'street_name': ['street', 'name'], 'color_rgb_float': ['color', 'rgb', 'float'], 'mac_platform_token': ['mac', 'platform', 'token'], 'ascii_company_email': ['ascii', 'company', 'email'], 'date_time_this_month': ['date', 'time', 'this', 'month'], 'md5': ['md5'], 'ean13': ['ean13'], 'ascii_email': ['ascii', 'email'], 'upc_a': ['upc', 'a'], 'rgb_color': ['rgb', 'color'], 'ean8': ['ean8'], 'words': ['words'], 'credit_card_security_code': ['credit', 'card', 'security', 'code'], 'city_prefix': ['city', 'prefix'], 'numerify': ['numerify'], 'suffix_male': ['suffix', 'male'], 'passport_owner': ['passport', 'owner'], 'year': ['year'], 'state_abbr': ['state', 'abbr'], 'date_this_decade': ['date', 'this', 'decade'], 'coordinate': ['coordinate'], 'random_int': ['random', 'int'], 'suffix_female': ['suffix', 'female'], 'free_email_domain': ['free', 'email', 'domain'], 'pydecimal': ['pydecimal'], 'localized_ean8': ['localized', 'ean8'], 'country_code': ['country', 'code'], 'pytimezone': ['pytimezone'], 'currency_symbol': ['currency', 'symbol'], 'tsv': ['tsv'], 'get_providers': ['get', 'providers'], 'color_hsl': ['color', 'hsl'], 'json': ['json'], 'mac_processor': ['mac', 'processor'], 'date_object': ['date', 'object'], 'prefix_nonbinary': ['prefix', 'nonbinary'], 'parse': ['parse'], 'passport_full': ['passport', 'full'], 'safe_domain_name': ['safe', 'domain', 'name'], 'color': ['color'], 'pylist': ['pylist'], 'postalcode_in_state': ['postalcode', 'in', 'state'], 'url': ['url'], 'street_suffix': ['street', 'suffix'], 'first_name_male': ['first', 'name', 'male'], 'paragraphs': ['paragraphs'], 'slug': ['slug'], 'month_name': ['month', 'name'], 'cryptocurrency': ['cryptocurrency'], 'aba': ['aba'], 'last_name': ['last', 'name'], 'last_name_nonbinary': ['last', 'name', 'nonbinary'], 'pyiterable': ['pyiterable'], 'zipcode_in_state': ['zipcode', 'in', 'state'], 'current_country_code': ['current', 'country', 'code'], 'language_name': ['language', 'name'], 'currency_code': ['currency', 'code'], 'prefix_female': ['prefix', 'female'], 'add_provider': ['add', 'provider'], 'safari': ['safari'], 'first_name_nonbinary': ['first', 'name', 'nonbinary'], 'items': ['items'], 'android_platform_token': ['android', 'platform', 'token'], 'null_boolean': ['null', 'boolean'], 'credit_card_number': ['credit', 'card', 'number'], 'word': ['word'], 'latitude': ['latitude'], 'passport_number': ['passport', 'number'], 'sentence': ['sentence'], 'sbn9': ['sbn9'], 'seed_instance': ['seed', 'instance'], 'mac_address': ['mac', 'address'], 'color_name': ['color', 'name'], 'provider': ['provider'], 'suffix_nonbinary': ['suffix', 'nonbinary'], 'get_arguments': ['get', 'arguments'], 'tar': ['tar'], 'uri': ['uri'], 'get_formatter': ['get', 'formatter'], 'hexify': ['hexify'], 'bothify': ['bothify'], 'currency': ['currency'], 'linux_processor': ['linux', 'processor'], 'del_arguments': ['del', 'arguments'], 'ean': ['ean'], 'doi': ['doi'], 'cryptocurrency_name': ['cryptocurrency', 'name'], 'uri_path': ['uri', 'path'], 'postcode_in_state': ['postcode', 'in', 'state'], 'random_letters': ['random', 'letters'], 'ssn': ['ssn'], 'bank_country': ['bank', 'country'], 'file_extension': ['file', 'extension'], 'profile': ['profile'], 'binary': ['binary'], 'date_time_between': ['date', 'time', 'between'], 'random_number': ['random', 'number'], 'domain_name': ['domain', 'name'], 'vin': ['vin'], 'current_country': ['current', 'country'], 'time_delta': ['time', 'delta'], 'postalcode_plus4': ['postalcode', 'plus4'], 'dsv': ['dsv'], 'date_time_between_dates': ['date', 'time', 'between', 'dates'], 'pystr': ['pystr'], 'image': ['image'], 'linux_platform_token': ['linux', 'platform', 'token'], 'unix_partition': ['unix', 'partition'], 'image_url': ['image', 'url'], 'location_on_land': ['location', 'on', 'land'], 'longitude': ['longitude'], 'itin': ['itin'], 'date_between_dates': ['date', 'between', 'dates'], 'random_choices': ['random', 'choices'], 'pyint': ['pyint'], 'catch_phrase': ['catch', 'phrase'], 'passport_dates': ['passport', 'dates'], 'company_email': ['company', 'email'], 'zip': ['zip'], 'pydict': ['pydict'], 'credit_card_full': ['credit', 'card', 'full'], 'building_number': ['building', 'number'], 'color_rgb': ['color', 'rgb'], 'pricetag': ['pricetag'], 'ipv4_private': ['ipv4', 'private'], 'swift': ['swift'], 'random_uppercase_letter': ['random', 'uppercase', 'letter'], 'random_sample': ['random', 'sample'], 'uri_extension': ['uri', 'extension'], 'sha1': ['sha1'], 'fixed_width': ['fixed', 'width'], 'csv': ['csv'], 'date_this_month': ['date', 'this', 'month'], 'get_words_list': ['get', 'words', 'list'], 'name_male': ['name', 'male'], 'passport_dob': ['passport', 'dob'], 'opera': ['opera'], 'prefix_male': ['prefix', 'male'], 'enum': ['enum'], 'seed_locale': ['seed', 'locale'], 'lexify': ['lexify'], 'user_agent': ['user', 'agent'], 'date_time_this_year': ['date', 'time', 'this', 'year'], 'random_elements': ['random', 'elements'], 'swift11': ['swift11'], 'user_name': ['user', 'name'], 'country': ['country'], 'pyobject': ['pyobject'], 'date_time_this_decade': ['date', 'time', 'this', 'decade'], 'language_code': ['language', 'code'], 'zipcode': ['zipcode'], 'ein': ['ein'], 'company_suffix': ['company', 'suffix'], 'day_of_month': ['day', 'of', 'month'], 'past_datetime': ['past', 'datetime'], 'pyset': ['pyset'], 'country_calling_code': ['country', 'calling', 'code'], 'currency_name': ['currency', 'name'], 'free_email': ['free', 'email'], 'ipv4_public': ['ipv4', 'public'], 'tld': ['tld'], 'future_date': ['future', 'date'], 'iban': ['iban'], 'suffix': ['suffix'], 'date_of_birth': ['date', 'of', 'birth'], 'basic_phone_number': ['basic', 'phone', 'number']},
        'word_tokens_set': {'ipv6': {'ipv6'}, 'military_ship': {'ship', 'military'}, 'date_between': {'date', 'between'}, 'random_letter': {'random', 'letter'}, 'hostname': {'hostname'}, 'passport_gender': {'passport', 'gender'}, 'psv': {'psv'}, 'secondary_address': {'secondary', 'address'}, 'unix_device': {'device', 'unix'}, 'mime_type': {'mime', 'type'}, 'date_time_ad': {'ad', 'time', 'date'}, 'prefix': {'prefix'}, 'random_element': {'random', 'element'}, 'ipv4_network_class': {'network', 'class', 'ipv4'}, 'format': {'format'}, 'time_object': {'object', 'time'}, 'century': {'century'}, 'city_suffix': {'suffix', 'city'}, 'http_method': {'method', 'http'}, 'port_number': {'port', 'number'}, 'credit_card_provider': {'credit', 'provider', 'card'}, 'latlng': {'latlng'}, 'phone_number': {'number', 'phone'}, 'am_pm': {'am', 'pm'}, 'date_time_this_century': {'time', 'date', 'this', 'century'}, 'bban': {'bban'}, 'pystruct': {'pystruct'}, 'http_status_code': {'status', 'code', 'http'}, 'last_name_male': {'male', 'name', 'last'}, 'unix_time': {'time', 'unix'}, 'color_hsv': {'hsv', 'color'}, 'rgb_css_color': {'css', 'color', 'rgb'}, 'simple_profile': {'simple', 'profile'}, 'safe_color_name': {'safe', 'name', 'color'}, 'localized_ean': {'localized', 'ean'}, 'locale': {'locale'}, 'password': {'password'}, 'date_this_century': {'date', 'this', 'century'}, 'bs': {'bs'}, 'windows_platform_token': {'windows', 'token', 'platform'}, 'random_digit_not_null_or_empty': {'not', 'random', 'or', 'digit', 'empty', 'null'}, 'random_digit': {'random', 'digit'}, 'boolean': {'boolean'}, 'local_latlng': {'local', 'latlng'}, 'credit_card_expire': {'credit', 'card', 'expire'}, 'random_digit_above_two': {'random', 'above', 'digit', 'two'}, 'texts': {'texts'}, 'ios_platform_token': {'token', 'ios', 'platform'}, 'nic_handles': {'nic', 'handles'}, 'job': {'job'}, 'nic_handle': {'nic', 'handle'}, 'past_date': {'past', 'date'}, 'set_formatter': {'set', 'formatter'}, 'iana_id': {'iana', 'id'}, 'sentences': {'sentences'}, 'date_this_year': {'year', 'date', 'this'}, 'name_nonbinary': {'name', 'nonbinary'}, 'job_male': {'male', 'job'}, 'swift8': {'swift8'}, 'localized_ean13': {'localized', 'ean13'}, 'domain_word': {'word', 'domain'}, 'text': {'text'}, 'uri_page': {'uri', 'page'}, 'emoji': {'emoji'}, 'file_path': {'file', 'path'}, 'job_female': {'job', 'female'}, 'sha256': {'sha256'}, 'invalid_ssn': {'invalid', 'ssn'}, 'set_arguments': {'arguments', 'set'}, 'first_name': {'name', 'first'}, 'company': {'company'}, 'date': {'date'}, 'postcode': {'postcode'}, 'iso8601': {'iso8601'}, 'license_plate': {'license', 'plate'}, 'internet_explorer': {'internet', 'explorer'}, 'timezone': {'timezone'}, 'xml': {'xml'}, 'chrome': {'chrome'}, 'address': {'address'}, 'firefox': {'firefox'}, 'random_digit_not_null': {'not', 'random', 'digit', 'null'}, 'time_series': {'time', 'series'}, 'ripe_id': {'ripe', 'id'}, 'military_apo': {'apo', 'military'}, 'json_bytes': {'json', 'bytes'}, 'msisdn': {'msisdn'}, 'uuid4': {'uuid4'}, 'pystr_format': {'format', 'pystr'}, 'postalcode': {'postalcode'}, 'pybool': {'pybool'}, 'isbn13': {'isbn13'}, 'ipv4': {'ipv4'}, 'date_time': {'time', 'date'}, 'pyfloat': {'pyfloat'}, 'month': {'month'}, 'ascii_free_email': {'email', 'free', 'ascii'}, 'random_lowercase_letter': {'lowercase', 'random', 'letter'}, 'randomize_nb_elements': {'nb', 'randomize', 'elements'}, 'email': {'email'}, 'zipcode_plus4': {'zipcode', 'plus4'}, 'administrative_unit': {'administrative', 'unit'}, 'last_name_female': {'name', 'last', 'female'}, 'name': {'name'}, 'military_dpo': {'dpo', 'military'}, 'safe_hex_color': {'safe', 'color', 'hex'}, 'time': {'time'}, 'dga': {'dga'}, 'isbn10': {'isbn10'}, 'cryptocurrency_code': {'cryptocurrency', 'code'}, 'ascii_safe_email': {'safe', 'email', 'ascii'}, 'upc_e': {'upc', 'e'}, 'hex_color': {'color', 'hex'}, 'state': {'state'}, 'military_state': {'state', 'military'}, 'city': {'city'}, 'day_of_week': {'week', 'day', 'of'}, 'first_name_female': {'name', 'first', 'female'}, 'random_digit_or_empty': {'random', 'or', 'digit', 'empty'}, 'future_datetime': {'future', 'datetime'}, 'street_address': {'street', 'address'}, 'safe_email': {'safe', 'email'}, 'name_female': {'name', 'female'}, 'paragraph': {'paragraph'}, 'file_name': {'file', 'name'}, 'pytuple': {'pytuple'}, 'street_name': {'street', 'name'}, 'color_rgb_float': {'float', 'color', 'rgb'}, 'mac_platform_token': {'token', 'mac', 'platform'}, 'ascii_company_email': {'company', 'email', 'ascii'}, 'date_time_this_month': {'month', 'time', 'date', 'this'}, 'md5': {'md5'}, 'ean13': {'ean13'}, 'ascii_email': {'email', 'ascii'}, 'upc_a': {'upc', 'a'}, 'rgb_color': {'color', 'rgb'}, 'ean8': {'ean8'}, 'words': {'words'}, 'credit_card_security_code': {'credit', 'security', 'code', 'card'}, 'city_prefix': {'prefix', 'city'}, 'numerify': {'numerify'}, 'suffix_male': {'suffix', 'male'}, 'passport_owner': {'owner', 'passport'}, 'year': {'year'}, 'state_abbr': {'abbr', 'state'}, 'date_this_decade': {'decade', 'date', 'this'}, 'coordinate': {'coordinate'}, 'random_int': {'random', 'int'}, 'suffix_female': {'suffix', 'female'}, 'free_email_domain': {'domain', 'email', 'free'}, 'pydecimal': {'pydecimal'}, 'localized_ean8': {'localized', 'ean8'}, 'country_code': {'country', 'code'}, 'pytimezone': {'pytimezone'}, 'currency_symbol': {'currency', 'symbol'}, 'tsv': {'tsv'}, 'get_providers': {'providers', 'get'}, 'color_hsl': {'hsl', 'color'}, 'json': {'json'}, 'mac_processor': {'mac', 'processor'}, 'date_object': {'object', 'date'}, 'prefix_nonbinary': {'prefix', 'nonbinary'}, 'parse': {'parse'}, 'passport_full': {'full', 'passport'}, 'safe_domain_name': {'safe', 'domain', 'name'}, 'color': {'color'}, 'pylist': {'pylist'}, 'postalcode_in_state': {'postalcode', 'in', 'state'}, 'url': {'url'}, 'street_suffix': {'street', 'suffix'}, 'first_name_male': {'male', 'name', 'first'}, 'paragraphs': {'paragraphs'}, 'slug': {'slug'}, 'month_name': {'month', 'name'}, 'cryptocurrency': {'cryptocurrency'}, 'aba': {'aba'}, 'last_name': {'name', 'last'}, 'last_name_nonbinary': {'name', 'last', 'nonbinary'}, 'pyiterable': {'pyiterable'}, 'zipcode_in_state': {'zipcode', 'in', 'state'}, 'current_country_code': {'country', 'code', 'current'}, 'language_name': {'name', 'language'}, 'currency_code': {'currency', 'code'}, 'prefix_female': {'prefix', 'female'}, 'add_provider': {'add', 'provider'}, 'safari': {'safari'}, 'first_name_nonbinary': {'name', 'first', 'nonbinary'}, 'items': {'items'}, 'android_platform_token': {'token', 'android', 'platform'}, 'null_boolean': {'boolean', 'null'}, 'credit_card_number': {'credit', 'number', 'card'}, 'word': {'word'}, 'latitude': {'latitude'}, 'passport_number': {'number', 'passport'}, 'sentence': {'sentence'}, 'sbn9': {'sbn9'}, 'seed_instance': {'seed', 'instance'}, 'mac_address': {'mac', 'address'}, 'color_name': {'name', 'color'}, 'provider': {'provider'}, 'suffix_nonbinary': {'suffix', 'nonbinary'}, 'get_arguments': {'get', 'arguments'}, 'tar': {'tar'}, 'uri': {'uri'}, 'get_formatter': {'get', 'formatter'}, 'hexify': {'hexify'}, 'bothify': {'bothify'}, 'currency': {'currency'}, 'linux_processor': {'linux', 'processor'}, 'del_arguments': {'del', 'arguments'}, 'ean': {'ean'}, 'doi': {'doi'}, 'cryptocurrency_name': {'cryptocurrency', 'name'}, 'uri_path': {'uri', 'path'}, 'postcode_in_state': {'in', 'state', 'postcode'}, 'random_letters': {'random', 'letters'}, 'ssn': {'ssn'}, 'bank_country': {'country', 'bank'}, 'file_extension': {'extension', 'file'}, 'profile': {'profile'}, 'binary': {'binary'}, 'date_time_between': {'time', 'date', 'between'}, 'random_number': {'number', 'random'}, 'domain_name': {'domain', 'name'}, 'vin': {'vin'}, 'current_country': {'country', 'current'}, 'time_delta': {'time', 'delta'}, 'postalcode_plus4': {'plus4', 'postalcode'}, 'dsv': {'dsv'}, 'date_time_between_dates': {'time', 'dates', 'date', 'between'}, 'pystr': {'pystr'}, 'image': {'image'}, 'linux_platform_token': {'linux', 'token', 'platform'}, 'unix_partition': {'partition', 'unix'}, 'image_url': {'image', 'url'}, 'location_on_land': {'on', 'location', 'land'}, 'longitude': {'longitude'}, 'itin': {'itin'}, 'date_between_dates': {'dates', 'date', 'between'}, 'random_choices': {'random', 'choices'}, 'pyint': {'pyint'}, 'catch_phrase': {'phrase', 'catch'}, 'passport_dates': {'passport', 'dates'}, 'company_email': {'company', 'email'}, 'zip': {'zip'}, 'pydict': {'pydict'}, 'credit_card_full': {'credit', 'full', 'card'}, 'building_number': {'number', 'building'}, 'color_rgb': {'color', 'rgb'}, 'pricetag': {'pricetag'}, 'ipv4_private': {'private', 'ipv4'}, 'swift': {'swift'}, 'random_uppercase_letter': {'random', 'uppercase', 'letter'}, 'random_sample': {'random', 'sample'}, 'uri_extension': {'extension', 'uri'}, 'sha1': {'sha1'}, 'fixed_width': {'fixed', 'width'}, 'csv': {'csv'}, 'date_this_month': {'month', 'date', 'this'}, 'get_words_list': {'get', 'words', 'list'}, 'name_male': {'male', 'name'}, 'passport_dob': {'dob', 'passport'}, 'opera': {'opera'}, 'prefix_male': {'prefix', 'male'}, 'enum': {'enum'}, 'seed_locale': {'locale', 'seed'}, 'lexify': {'lexify'}, 'user_agent': {'user', 'agent'}, 'date_time_this_year': {'time', 'year', 'date', 'this'}, 'random_elements': {'random', 'elements'}, 'swift11': {'swift11'}, 'user_name': {'user', 'name'}, 'country': {'country'}, 'pyobject': {'pyobject'}, 'date_time_this_decade': {'decade', 'time', 'date', 'this'}, 'language_code': {'code', 'language'}, 'zipcode': {'zipcode'}, 'ein': {'ein'}, 'company_suffix': {'suffix', 'company'}, 'day_of_month': {'month', 'day', 'of'}, 'past_datetime': {'past', 'datetime'}, 'pyset': {'pyset'}, 'country_calling_code': {'code', 'country', 'calling'}, 'currency_name': {'currency', 'name'}, 'free_email': {'email', 'free'}, 'ipv4_public': {'public', 'ipv4'}, 'tld': {'tld'}, 'future_date': {'future', 'date'}, 'iban': {'iban'}, 'suffix': {'suffix'}, 'date_of_birth': {'birth', 'date', 'of'}, 'basic_phone_number': {'number', 'basic', 'phone'}}
    },
    'mimesis' : {
        'word_list': ['timestamp', 'university', 'stock_ticker', 'gmt_offset', 'century', 'phone_number', 'cryptocurrency_symbol', 'icao_code', 'surname', 'isd_code', 'password', 'dish', 'text', 'emoji', 'formatted_time', 'prefecture', 'first_name', 'currency_iso_code', 'company', 'date', 'override_locale', 'answer', 'timezone', 'calling_code', 'week_date', 'address', 'get_current_locale', 'Meta', 'nationality', 'sex', 'stock_exchange', 'vegetable', 'update_dataset', 'datetime', 'language', 'month', 'stock_name', 'cryptocurrency_iso_code', 'email', 'formatted_date', 'name', 'political_views', 'federal_subject', 'time', 'street_number', 'hex_color', 'state', 'duration', 'city', 'day_of_week', 'street_name', 'fruit', 'gender', 'telephone', 'validate_enum', 'full_name', 'words', 'rgb_color', 'gender_code', 'year', 'continent', 'level', 'periodicity', 'formatted_datetime', 'views_on', 'country_code', 'currency_symbol', 'price', 'height', 'color', 'street_suffix', 'company_type', 'country_emoji_flag', 'last_name', 'word', 'latitude', 'sentence', 'username', 'quote', 'title', 'occupation', 'academic_degree', 'blood_type', 'postal_code', 'drink', 'weight', 'default_country', 'alphabet', 'zip_code', 'price_in_btc', 'birthdate', 'bank', 'identifier', 'province', 'longitude', 'coordinates', 'gender_symbol', 'region', 'spices', 'country', 'bulk_create_datetimes', 'worldview', 'day_of_month', 'iata_code', 'reseed'],
        'word_tokens': {'timestamp': ['timestamp'], 'university': ['university'], 'stock_ticker': ['stock', 'ticker'], 'gmt_offset': ['gmt', 'offset'], 'century': ['century'], 'phone_number': ['phone', 'number'], 'cryptocurrency_symbol': ['cryptocurrency', 'symbol'], 'icao_code': ['icao', 'code'], 'surname': ['surname'], 'isd_code': ['isd', 'code'], 'password': ['password'], 'dish': ['dish'], 'text': ['text'], 'emoji': ['emoji'], 'formatted_time': ['formatted', 'time'], 'prefecture': ['prefecture'], 'first_name': ['first', 'name'], 'currency_iso_code': ['currency', 'iso', 'code'], 'company': ['company'], 'date': ['date'], 'override_locale': ['override', 'locale'], 'answer': ['answer'], 'timezone': ['timezone'], 'calling_code': ['calling', 'code'], 'week_date': ['week', 'date'], 'address': ['address'], 'get_current_locale': ['get', 'current', 'locale'], 'Meta': ['Meta'], 'nationality': ['nationality'], 'sex': ['sex'], 'stock_exchange': ['stock', 'exchange'], 'vegetable': ['vegetable'], 'update_dataset': ['update', 'dataset'], 'datetime': ['datetime'], 'language': ['language'], 'month': ['month'], 'stock_name': ['stock', 'name'], 'cryptocurrency_iso_code': ['cryptocurrency', 'iso', 'code'], 'email': ['email'], 'formatted_date': ['formatted', 'date'], 'name': ['name'], 'political_views': ['political', 'views'], 'federal_subject': ['federal', 'subject'], 'time': ['time'], 'street_number': ['street', 'number'], 'hex_color': ['hex', 'color'], 'state': ['state'], 'duration': ['duration'], 'city': ['city'], 'day_of_week': ['day', 'of', 'week'], 'street_name': ['street', 'name'], 'fruit': ['fruit'], 'gender': ['gender'], 'telephone': ['telephone'], 'validate_enum': ['validate', 'enum'], 'full_name': ['full', 'name'], 'words': ['words'], 'rgb_color': ['rgb', 'color'], 'gender_code': ['gender', 'code'], 'year': ['year'], 'continent': ['continent'], 'level': ['level'], 'periodicity': ['periodicity'], 'formatted_datetime': ['formatted', 'datetime'], 'views_on': ['views', 'on'], 'country_code': ['country', 'code'], 'currency_symbol': ['currency', 'symbol'], 'price': ['price'], 'height': ['height'], 'color': ['color'], 'street_suffix': ['street', 'suffix'], 'company_type': ['company', 'type'], 'country_emoji_flag': ['country', 'emoji', 'flag'], 'last_name': ['last', 'name'], 'word': ['word'], 'latitude': ['latitude'], 'sentence': ['sentence'], 'username': ['username'], 'quote': ['quote'], 'title': ['title'], 'occupation': ['occupation'], 'academic_degree': ['academic', 'degree'], 'blood_type': ['blood', 'type'], 'postal_code': ['postal', 'code'], 'drink': ['drink'], 'weight': ['weight'], 'default_country': ['default', 'country'], 'alphabet': ['alphabet'], 'zip_code': ['zip', 'code'], 'price_in_btc': ['price', 'in', 'btc'], 'birthdate': ['birthdate'], 'bank': ['bank'], 'identifier': ['identifier'], 'province': ['province'], 'longitude': ['longitude'], 'coordinates': ['coordinates'], 'gender_symbol': ['gender', 'symbol'], 'region': ['region'], 'spices': ['spices'], 'country': ['country'], 'bulk_create_datetimes': ['bulk', 'create', 'datetimes'], 'worldview': ['worldview'], 'day_of_month': ['day', 'of', 'month'], 'iata_code': ['iata', 'code'], 'reseed': ['reseed']},
        'word_tokens_set': {'timestamp': {'timestamp'}, 'university': {'university'}, 'stock_ticker': {'stock', 'ticker'}, 'gmt_offset': {'gmt', 'offset'}, 'century': {'century'}, 'phone_number': {'number', 'phone'}, 'cryptocurrency_symbol': {'symbol', 'cryptocurrency'}, 'icao_code': {'icao', 'code'}, 'surname': {'surname'}, 'isd_code': {'isd', 'code'}, 'password': {'password'}, 'dish': {'dish'}, 'text': {'text'}, 'emoji': {'emoji'}, 'formatted_time': {'formatted', 'time'}, 'prefecture': {'prefecture'}, 'first_name': {'name', 'first'}, 'currency_iso_code': {'currency', 'code', 'iso'}, 'company': {'company'}, 'date': {'date'}, 'override_locale': {'locale', 'override'}, 'answer': {'answer'}, 'timezone': {'timezone'}, 'calling_code': {'code', 'calling'}, 'week_date': {'week', 'date'}, 'address': {'address'}, 'get_current_locale': {'locale', 'get', 'current'}, 'Meta': {'Meta'}, 'nationality': {'nationality'}, 'sex': {'sex'}, 'stock_exchange': {'stock', 'exchange'}, 'vegetable': {'vegetable'}, 'update_dataset': {'dataset', 'update'}, 'datetime': {'datetime'}, 'language': {'language'}, 'month': {'month'}, 'stock_name': {'stock', 'name'}, 'cryptocurrency_iso_code': {'cryptocurrency', 'code', 'iso'}, 'email': {'email'}, 'formatted_date': {'formatted', 'date'}, 'name': {'name'}, 'political_views': {'political', 'views'}, 'federal_subject': {'federal', 'subject'}, 'time': {'time'}, 'street_number': {'number', 'street'}, 'hex_color': {'color', 'hex'}, 'state': {'state'}, 'duration': {'duration'}, 'city': {'city'}, 'day_of_week': {'week', 'day', 'of'}, 'street_name': {'street', 'name'}, 'fruit': {'fruit'}, 'gender': {'gender'}, 'telephone': {'telephone'}, 'validate_enum': {'enum', 'validate'}, 'full_name': {'full', 'name'}, 'words': {'words'}, 'rgb_color': {'color', 'rgb'}, 'gender_code': {'code', 'gender'}, 'year': {'year'}, 'continent': {'continent'}, 'level': {'level'}, 'periodicity': {'periodicity'}, 'formatted_datetime': {'formatted', 'datetime'}, 'views_on': {'on', 'views'}, 'country_code': {'country', 'code'}, 'currency_symbol': {'currency', 'symbol'}, 'price': {'price'}, 'height': {'height'}, 'color': {'color'}, 'street_suffix': {'street', 'suffix'}, 'company_type': {'company', 'type'}, 'country_emoji_flag': {'emoji', 'country', 'flag'}, 'last_name': {'name', 'last'}, 'word': {'word'}, 'latitude': {'latitude'}, 'sentence': {'sentence'}, 'username': {'username'}, 'quote': {'quote'}, 'title': {'title'}, 'occupation': {'occupation'}, 'academic_degree': {'academic', 'degree'}, 'blood_type': {'type', 'blood'}, 'postal_code': {'postal', 'code'}, 'drink': {'drink'}, 'weight': {'weight'}, 'default_country': {'country', 'default'}, 'alphabet': {'alphabet'}, 'zip_code': {'zip', 'code'}, 'price_in_btc': {'btc', 'price', 'in'}, 'birthdate': {'birthdate'}, 'bank': {'bank'}, 'identifier': {'identifier'}, 'province': {'province'}, 'longitude': {'longitude'}, 'coordinates': {'coordinates'}, 'gender_symbol': {'symbol', 'gender'}, 'region': {'region'}, 'spices': {'spices'}, 'country': {'country'}, 'bulk_create_datetimes': {'datetimes', 'create', 'bulk'}, 'worldview': {'worldview'}, 'day_of_month': {'month', 'day', 'of'}, 'iata_code': {'code', 'iata'}, 'reseed': {'reseed'}}
    },
    'mixed' : {
        'word_list': ['random_letter', 'psv', 'unix_device', 'university', 'mime_type', 'gmt_offset', 'ipv4_network_class', 'format', 'century', 'port_number', 'latlng', 'phone_number', 'am_pm', 'icao_code', 'http_status_code', 'localized_ean', 'bs', 'random_digit_not_null_or_empty', 'past_date', 'sentences', 'swift8', 'job_male', 'uri_page', 'emoji', 'set_arguments', 'prefecture', 'currency_iso_code', 'company', 'override_locale', 'calling_code', 'address', 'get_current_locale', 'nationality', 'sex', 'ripe_id', 'uuid4', 'vegetable', 'update_dataset', 'language', 'random_lowercase_letter', 'randomize_nb_elements', 'safe_hex_color', 'hex_color', 'duration', 'safe_email', 'gender', 'telephone', 'full_name', 'credit_card_security_code', 'city_prefix', 'numerify', 'suffix_male', 'state_abbr', 'level', 'date_this_decade', 'periodicity', 'free_email_domain', 'get_providers', 'color_hsl', 'json', 'passport_full', 'pylist', 'company_type', 'slug', 'last_name', 'zipcode_in_state', 'safari', 'items', 'credit_card_number', 'color_name', 'provider', 'uri', 'get_arguments', 'blood_type', 'del_arguments', 'ean', 'cryptocurrency_name', 'uri_path', 'postcode_in_state', 'random_number', 'default_country', 'vin', 'price_in_btc', 'current_country', 'birthdate', 'identifier', 'unix_partition', 'pyint', 'ipv4_private', 'random_sample', 'passport_dob', 'gender_symbol', 'seed_locale', 'swift11', 'country', 'past_datetime', 'free_email', 'ipv6', 'hostname', 'passport_gender', 'secondary_address', 'prefix', 'random_element', 'time_object', 'date_time_this_century', 'bban', 'pystruct', 'unix_time', 'rgb_css_color', 'isd_code', 'boolean', 'local_latlng', 'credit_card_expire', 'job', 'iana_id', 'name_nonbinary', 'domain_word', 'text', 'formatted_time', 'first_name', 'postcode', 'timezone', 'xml', 'chrome', 'firefox', 'random_digit_not_null', 'military_apo', 'json_bytes', 'stock_exchange', 'postalcode', 'ipv4', 'month', 'ascii_free_email', 'zipcode_plus4', 'last_name_female', 'name', 'political_views', 'federal_subject', 'dga', 'random_digit_or_empty', 'name_female', 'street_name', 'fruit', 'mac_platform_token', 'ascii_company_email', 'words', 'gender_code', 'continent', 'suffix_female', 'pydecimal', 'views_on', 'tsv', 'price', 'safe_domain_name', 'height', 'street_suffix', 'current_country_code', 'currency_code', 'prefix_female', 'null_boolean', 'sentence', 'sbn9', 'tar', 'quote', 'occupation', 'bothify', 'postal_code', 'drink', 'doi', 'random_letters', 'ssn', 'profile', 'alphabet', 'domain_name', 'dsv', 'bank', 'pystr', 'coordinates', 'catch_phrase', 'company_email', 'color_rgb', 'pricetag', 'swift', 'csv', 'date_this_month', 'prefix_male', 'enum', 'region', 'user_agent', 'random_elements', 'zipcode', 'pyobject', 'bulk_create_datetimes', 'pyset', 'iata_code', 'currency_name', 'tld', 'basic_phone_number', 'date_between', 'timestamp', 'date_time_ad', 'city_suffix', 'credit_card_provider', 'cryptocurrency_symbol', 'simple_profile', 'safe_color_name', 'password', 'random_digit', 'random_digit_above_two', 'texts', 'date_this_year', 'file_path', 'job_female', 'invalid_ssn', 'date', 'answer', 'iso8601', 'week_date', 'time_series', 'msisdn', 'pystr_format', 'pybool', 'isbn13', 'datetime', 'cryptocurrency_iso_code', 'email', 'cryptocurrency_code', 'ascii_safe_email', 'upc_e', 'street_number', 'day_of_week', 'future_datetime', 'paragraph', 'pytuple', 'ean13', 'rgb_color', 'passport_owner', 'year', 'coordinate', 'random_int', 'formatted_datetime', 'localized_ean8', 'country_code', 'pytimezone', 'currency_symbol', 'url', 'postalcode_in_state', 'first_name_male', 'last_name_nonbinary', 'pyiterable', 'add_provider', 'word', 'first_name_nonbinary', 'android_platform_token', 'latitude', 'passport_number', 'mac_address', 'suffix_nonbinary', 'title', 'get_formatter', 'hexify', 'currency', 'linux_processor', 'weight', 'date_time_between', 'zip_code', 'time_delta', 'postalcode_plus4', 'date_time_between_dates', 'image_url', 'longitude', 'zip', 'pydict', 'uri_extension', 'sha1', 'get_words_list', 'name_male', 'opera', 'ein', 'company_suffix', 'day_of_month', 'country_calling_code', 'future_date', 'reseed', 'iban', 'military_ship', 'stock_ticker', 'http_method', 'surname', 'last_name_male', 'color_hsv', 'locale', 'date_this_century', 'windows_platform_token', 'ios_platform_token', 'nic_handles', 'nic_handle', 'set_formatter', 'dish', 'localized_ean13', 'sha256', 'license_plate', 'internet_explorer', 'Meta', 'date_time', 'pyfloat', 'stock_name', 'administrative_unit', 'formatted_date', 'military_dpo', 'time', 'isbn10', 'state', 'military_state', 'city', 'first_name_female', 'street_address', 'file_name', 'color_rgb_float', 'upc_a', 'date_time_this_month', 'md5', 'validate_enum', 'ascii_email', 'ean8', 'mac_processor', 'date_object', 'prefix_nonbinary', 'parse', 'color', 'paragraphs', 'month_name', 'cryptocurrency', 'country_emoji_flag', 'aba', 'language_name', 'seed_instance', 'username', 'academic_degree', 'bank_country', 'file_extension', 'binary', 'image', 'linux_platform_token', 'location_on_land', 'province', 'itin', 'date_between_dates', 'random_choices', 'passport_dates', 'credit_card_full', 'building_number', 'random_uppercase_letter', 'fixed_width', 'lexify', 'spices', 'date_time_this_year', 'user_name', 'date_time_this_decade', 'language_code', 'worldview', 'ipv4_public', 'suffix', 'date_of_birth'],
        'word_tokens': {'random_letter': ['random', 'letter'], 'psv': ['psv'], 'unix_device': ['unix', 'device'], 'university': ['university'], 'mime_type': ['mime', 'type'], 'gmt_offset': ['gmt', 'offset'], 'ipv4_network_class': ['ipv4', 'network', 'class'], 'format': ['format'], 'century': ['century'], 'port_number': ['port', 'number'], 'latlng': ['latlng'], 'phone_number': ['phone', 'number'], 'am_pm': ['am', 'pm'], 'icao_code': ['icao', 'code'], 'http_status_code': ['http', 'status', 'code'], 'localized_ean': ['localized', 'ean'], 'bs': ['bs'], 'random_digit_not_null_or_empty': ['random', 'digit', 'not', 'null', 'or', 'empty'], 'past_date': ['past', 'date'], 'sentences': ['sentences'], 'swift8': ['swift8'], 'job_male': ['job', 'male'], 'uri_page': ['uri', 'page'], 'emoji': ['emoji'], 'set_arguments': ['set', 'arguments'], 'prefecture': ['prefecture'], 'currency_iso_code': ['currency', 'iso', 'code'], 'company': ['company'], 'override_locale': ['override', 'locale'], 'calling_code': ['calling', 'code'], 'address': ['address'], 'get_current_locale': ['get', 'current', 'locale'], 'nationality': ['nationality'], 'sex': ['sex'], 'ripe_id': ['ripe', 'id'], 'uuid4': ['uuid4'], 'vegetable': ['vegetable'], 'update_dataset': ['update', 'dataset'], 'language': ['language'], 'random_lowercase_letter': ['random', 'lowercase', 'letter'], 'randomize_nb_elements': ['randomize', 'nb', 'elements'], 'safe_hex_color': ['safe', 'hex', 'color'], 'hex_color': ['hex', 'color'], 'duration': ['duration'], 'safe_email': ['safe', 'email'], 'gender': ['gender'], 'telephone': ['telephone'], 'full_name': ['full', 'name'], 'credit_card_security_code': ['credit', 'card', 'security', 'code'], 'city_prefix': ['city', 'prefix'], 'numerify': ['numerify'], 'suffix_male': ['suffix', 'male'], 'state_abbr': ['state', 'abbr'], 'level': ['level'], 'date_this_decade': ['date', 'this', 'decade'], 'periodicity': ['periodicity'], 'free_email_domain': ['free', 'email', 'domain'], 'get_providers': ['get', 'providers'], 'color_hsl': ['color', 'hsl'], 'json': ['json'], 'passport_full': ['passport', 'full'], 'pylist': ['pylist'], 'company_type': ['company', 'type'], 'slug': ['slug'], 'last_name': ['last', 'name'], 'zipcode_in_state': ['zipcode', 'in', 'state'], 'safari': ['safari'], 'items': ['items'], 'credit_card_number': ['credit', 'card', 'number'], 'color_name': ['color', 'name'], 'provider': ['provider'], 'uri': ['uri'], 'get_arguments': ['get', 'arguments'], 'blood_type': ['blood', 'type'], 'del_arguments': ['del', 'arguments'], 'ean': ['ean'], 'cryptocurrency_name': ['cryptocurrency', 'name'], 'uri_path': ['uri', 'path'], 'postcode_in_state': ['postcode', 'in', 'state'], 'random_number': ['random', 'number'], 'default_country': ['default', 'country'], 'vin': ['vin'], 'price_in_btc': ['price', 'in', 'btc'], 'current_country': ['current', 'country'], 'birthdate': ['birthdate'], 'identifier': ['identifier'], 'unix_partition': ['unix', 'partition'], 'pyint': ['pyint'], 'ipv4_private': ['ipv4', 'private'], 'random_sample': ['random', 'sample'], 'passport_dob': ['passport', 'dob'], 'gender_symbol': ['gender', 'symbol'], 'seed_locale': ['seed', 'locale'], 'swift11': ['swift11'], 'country': ['country'], 'past_datetime': ['past', 'datetime'], 'free_email': ['free', 'email'], 'ipv6': ['ipv6'], 'hostname': ['hostname'], 'passport_gender': ['passport', 'gender'], 'secondary_address': ['secondary', 'address'], 'prefix': ['prefix'], 'random_element': ['random', 'element'], 'time_object': ['time', 'object'], 'date_time_this_century': ['date', 'time', 'this', 'century'], 'bban': ['bban'], 'pystruct': ['pystruct'], 'unix_time': ['unix', 'time'], 'rgb_css_color': ['rgb', 'css', 'color'], 'isd_code': ['isd', 'code'], 'boolean': ['boolean'], 'local_latlng': ['local', 'latlng'], 'credit_card_expire': ['credit', 'card', 'expire'], 'job': ['job'], 'iana_id': ['iana', 'id'], 'name_nonbinary': ['name', 'nonbinary'], 'domain_word': ['domain', 'word'], 'text': ['text'], 'formatted_time': ['formatted', 'time'], 'first_name': ['first', 'name'], 'postcode': ['postcode'], 'timezone': ['timezone'], 'xml': ['xml'], 'chrome': ['chrome'], 'firefox': ['firefox'], 'random_digit_not_null': ['random', 'digit', 'not', 'null'], 'military_apo': ['military', 'apo'], 'json_bytes': ['json', 'bytes'], 'stock_exchange': ['stock', 'exchange'], 'postalcode': ['postalcode'], 'ipv4': ['ipv4'], 'month': ['month'], 'ascii_free_email': ['ascii', 'free', 'email'], 'zipcode_plus4': ['zipcode', 'plus4'], 'last_name_female': ['last', 'name', 'female'], 'name': ['name'], 'political_views': ['political', 'views'], 'federal_subject': ['federal', 'subject'], 'dga': ['dga'], 'random_digit_or_empty': ['random', 'digit', 'or', 'empty'], 'name_female': ['name', 'female'], 'street_name': ['street', 'name'], 'fruit': ['fruit'], 'mac_platform_token': ['mac', 'platform', 'token'], 'ascii_company_email': ['ascii', 'company', 'email'], 'words': ['words'], 'gender_code': ['gender', 'code'], 'continent': ['continent'], 'suffix_female': ['suffix', 'female'], 'pydecimal': ['pydecimal'], 'views_on': ['views', 'on'], 'tsv': ['tsv'], 'price': ['price'], 'safe_domain_name': ['safe', 'domain', 'name'], 'height': ['height'], 'street_suffix': ['street', 'suffix'], 'current_country_code': ['current', 'country', 'code'], 'currency_code': ['currency', 'code'], 'prefix_female': ['prefix', 'female'], 'null_boolean': ['null', 'boolean'], 'sentence': ['sentence'], 'sbn9': ['sbn9'], 'tar': ['tar'], 'quote': ['quote'], 'occupation': ['occupation'], 'bothify': ['bothify'], 'postal_code': ['postal', 'code'], 'drink': ['drink'], 'doi': ['doi'], 'random_letters': ['random', 'letters'], 'ssn': ['ssn'], 'profile': ['profile'], 'alphabet': ['alphabet'], 'domain_name': ['domain', 'name'], 'dsv': ['dsv'], 'bank': ['bank'], 'pystr': ['pystr'], 'coordinates': ['coordinates'], 'catch_phrase': ['catch', 'phrase'], 'company_email': ['company', 'email'], 'color_rgb': ['color', 'rgb'], 'pricetag': ['pricetag'], 'swift': ['swift'], 'csv': ['csv'], 'date_this_month': ['date', 'this', 'month'], 'prefix_male': ['prefix', 'male'], 'enum': ['enum'], 'region': ['region'], 'user_agent': ['user', 'agent'], 'random_elements': ['random', 'elements'], 'zipcode': ['zipcode'], 'pyobject': ['pyobject'], 'bulk_create_datetimes': ['bulk', 'create', 'datetimes'], 'pyset': ['pyset'], 'iata_code': ['iata', 'code'], 'currency_name': ['currency', 'name'], 'tld': ['tld'], 'basic_phone_number': ['basic', 'phone', 'number'], 'date_between': ['date', 'between'], 'timestamp': ['timestamp'], 'date_time_ad': ['date', 'time', 'ad'], 'city_suffix': ['city', 'suffix'], 'credit_card_provider': ['credit', 'card', 'provider'], 'cryptocurrency_symbol': ['cryptocurrency', 'symbol'], 'simple_profile': ['simple', 'profile'], 'safe_color_name': ['safe', 'color', 'name'], 'password': ['password'], 'random_digit': ['random', 'digit'], 'random_digit_above_two': ['random', 'digit', 'above', 'two'], 'texts': ['texts'], 'date_this_year': ['date', 'this', 'year'], 'file_path': ['file', 'path'], 'job_female': ['job', 'female'], 'invalid_ssn': ['invalid', 'ssn'], 'date': ['date'], 'answer': ['answer'], 'iso8601': ['iso8601'], 'week_date': ['week', 'date'], 'time_series': ['time', 'series'], 'msisdn': ['msisdn'], 'pystr_format': ['pystr', 'format'], 'pybool': ['pybool'], 'isbn13': ['isbn13'], 'datetime': ['datetime'], 'cryptocurrency_iso_code': ['cryptocurrency', 'iso', 'code'], 'email': ['email'], 'cryptocurrency_code': ['cryptocurrency', 'code'], 'ascii_safe_email': ['ascii', 'safe', 'email'], 'upc_e': ['upc', 'e'], 'street_number': ['street', 'number'], 'day_of_week': ['day', 'of', 'week'], 'future_datetime': ['future', 'datetime'], 'paragraph': ['paragraph'], 'pytuple': ['pytuple'], 'ean13': ['ean13'], 'rgb_color': ['rgb', 'color'], 'passport_owner': ['passport', 'owner'], 'year': ['year'], 'coordinate': ['coordinate'], 'random_int': ['random', 'int'], 'formatted_datetime': ['formatted', 'datetime'], 'localized_ean8': ['localized', 'ean8'], 'country_code': ['country', 'code'], 'pytimezone': ['pytimezone'], 'currency_symbol': ['currency', 'symbol'], 'url': ['url'], 'postalcode_in_state': ['postalcode', 'in', 'state'], 'first_name_male': ['first', 'name', 'male'], 'last_name_nonbinary': ['last', 'name', 'nonbinary'], 'pyiterable': ['pyiterable'], 'add_provider': ['add', 'provider'], 'word': ['word'], 'first_name_nonbinary': ['first', 'name', 'nonbinary'], 'android_platform_token': ['android', 'platform', 'token'], 'latitude': ['latitude'], 'passport_number': ['passport', 'number'], 'mac_address': ['mac', 'address'], 'suffix_nonbinary': ['suffix', 'nonbinary'], 'title': ['title'], 'get_formatter': ['get', 'formatter'], 'hexify': ['hexify'], 'currency': ['currency'], 'linux_processor': ['linux', 'processor'], 'weight': ['weight'], 'date_time_between': ['date', 'time', 'between'], 'zip_code': ['zip', 'code'], 'time_delta': ['time', 'delta'], 'postalcode_plus4': ['postalcode', 'plus4'], 'date_time_between_dates': ['date', 'time', 'between', 'dates'], 'image_url': ['image', 'url'], 'longitude': ['longitude'], 'zip': ['zip'], 'pydict': ['pydict'], 'uri_extension': ['uri', 'extension'], 'sha1': ['sha1'], 'get_words_list': ['get', 'words', 'list'], 'name_male': ['name', 'male'], 'opera': ['opera'], 'ein': ['ein'], 'company_suffix': ['company', 'suffix'], 'day_of_month': ['day', 'of', 'month'], 'country_calling_code': ['country', 'calling', 'code'], 'future_date': ['future', 'date'], 'reseed': ['reseed'], 'iban': ['iban'], 'military_ship': ['military', 'ship'], 'stock_ticker': ['stock', 'ticker'], 'http_method': ['http', 'method'], 'surname': ['surname'], 'last_name_male': ['last', 'name', 'male'], 'color_hsv': ['color', 'hsv'], 'locale': ['locale'], 'date_this_century': ['date', 'this', 'century'], 'windows_platform_token': ['windows', 'platform', 'token'], 'ios_platform_token': ['ios', 'platform', 'token'], 'nic_handles': ['nic', 'handles'], 'nic_handle': ['nic', 'handle'], 'set_formatter': ['set', 'formatter'], 'dish': ['dish'], 'localized_ean13': ['localized', 'ean13'], 'sha256': ['sha256'], 'license_plate': ['license', 'plate'], 'internet_explorer': ['internet', 'explorer'], 'Meta': ['Meta'], 'date_time': ['date', 'time'], 'pyfloat': ['pyfloat'], 'stock_name': ['stock', 'name'], 'administrative_unit': ['administrative', 'unit'], 'formatted_date': ['formatted', 'date'], 'military_dpo': ['military', 'dpo'], 'time': ['time'], 'isbn10': ['isbn10'], 'state': ['state'], 'military_state': ['military', 'state'], 'city': ['city'], 'first_name_female': ['first', 'name', 'female'], 'street_address': ['street', 'address'], 'file_name': ['file', 'name'], 'color_rgb_float': ['color', 'rgb', 'float'], 'upc_a': ['upc', 'a'], 'date_time_this_month': ['date', 'time', 'this', 'month'], 'md5': ['md5'], 'validate_enum': ['validate', 'enum'], 'ascii_email': ['ascii', 'email'], 'ean8': ['ean8'], 'mac_processor': ['mac', 'processor'], 'date_object': ['date', 'object'], 'prefix_nonbinary': ['prefix', 'nonbinary'], 'parse': ['parse'], 'color': ['color'], 'paragraphs': ['paragraphs'], 'month_name': ['month', 'name'], 'cryptocurrency': ['cryptocurrency'], 'country_emoji_flag': ['country', 'emoji', 'flag'], 'aba': ['aba'], 'language_name': ['language', 'name'], 'seed_instance': ['seed', 'instance'], 'username': ['username'], 'academic_degree': ['academic', 'degree'], 'bank_country': ['bank', 'country'], 'file_extension': ['file', 'extension'], 'binary': ['binary'], 'image': ['image'], 'linux_platform_token': ['linux', 'platform', 'token'], 'location_on_land': ['location', 'on', 'land'], 'province': ['province'], 'itin': ['itin'], 'date_between_dates': ['date', 'between', 'dates'], 'random_choices': ['random', 'choices'], 'passport_dates': ['passport', 'dates'], 'credit_card_full': ['credit', 'card', 'full'], 'building_number': ['building', 'number'], 'random_uppercase_letter': ['random', 'uppercase', 'letter'], 'fixed_width': ['fixed', 'width'], 'lexify': ['lexify'], 'spices': ['spices'], 'date_time_this_year': ['date', 'time', 'this', 'year'], 'user_name': ['user', 'name'], 'date_time_this_decade': ['date', 'time', 'this', 'decade'], 'language_code': ['language', 'code'], 'worldview': ['worldview'], 'ipv4_public': ['ipv4', 'public'], 'suffix': ['suffix'], 'date_of_birth': ['date', 'of', 'birth']},
        'word_tokens_set': {'random_letter': {'random', 'letter'}, 'psv': {'psv'}, 'unix_device': {'device', 'unix'}, 'university': {'university'}, 'mime_type': {'mime', 'type'}, 'gmt_offset': {'gmt', 'offset'}, 'ipv4_network_class': {'network', 'class', 'ipv4'}, 'format': {'format'}, 'century': {'century'}, 'port_number': {'port', 'number'}, 'latlng': {'latlng'}, 'phone_number': {'number', 'phone'}, 'am_pm': {'am', 'pm'}, 'icao_code': {'icao', 'code'}, 'http_status_code': {'status', 'code', 'http'}, 'localized_ean': {'localized', 'ean'}, 'bs': {'bs'}, 'random_digit_not_null_or_empty': {'not', 'random', 'or', 'digit', 'empty', 'null'}, 'past_date': {'past', 'date'}, 'sentences': {'sentences'}, 'swift8': {'swift8'}, 'job_male': {'male', 'job'}, 'uri_page': {'uri', 'page'}, 'emoji': {'emoji'}, 'set_arguments': {'arguments', 'set'}, 'prefecture': {'prefecture'}, 'currency_iso_code': {'currency', 'code', 'iso'}, 'company': {'company'}, 'override_locale': {'locale', 'override'}, 'calling_code': {'code', 'calling'}, 'address': {'address'}, 'get_current_locale': {'locale', 'get', 'current'}, 'nationality': {'nationality'}, 'sex': {'sex'}, 'ripe_id': {'ripe', 'id'}, 'uuid4': {'uuid4'}, 'vegetable': {'vegetable'}, 'update_dataset': {'dataset', 'update'}, 'language': {'language'}, 'random_lowercase_letter': {'lowercase', 'random', 'letter'}, 'randomize_nb_elements': {'nb', 'randomize', 'elements'}, 'safe_hex_color': {'safe', 'color', 'hex'}, 'hex_color': {'color', 'hex'}, 'duration': {'duration'}, 'safe_email': {'safe', 'email'}, 'gender': {'gender'}, 'telephone': {'telephone'}, 'full_name': {'full', 'name'}, 'credit_card_security_code': {'credit', 'security', 'code', 'card'}, 'city_prefix': {'prefix', 'city'}, 'numerify': {'numerify'}, 'suffix_male': {'suffix', 'male'}, 'state_abbr': {'abbr', 'state'}, 'level': {'level'}, 'date_this_decade': {'decade', 'date', 'this'}, 'periodicity': {'periodicity'}, 'free_email_domain': {'domain', 'email', 'free'}, 'get_providers': {'providers', 'get'}, 'color_hsl': {'hsl', 'color'}, 'json': {'json'}, 'passport_full': {'full', 'passport'}, 'pylist': {'pylist'}, 'company_type': {'company', 'type'}, 'slug': {'slug'}, 'last_name': {'name', 'last'}, 'zipcode_in_state': {'zipcode', 'in', 'state'}, 'safari': {'safari'}, 'items': {'items'}, 'credit_card_number': {'credit', 'number', 'card'}, 'color_name': {'name', 'color'}, 'provider': {'provider'}, 'uri': {'uri'}, 'get_arguments': {'get', 'arguments'}, 'blood_type': {'type', 'blood'}, 'del_arguments': {'del', 'arguments'}, 'ean': {'ean'}, 'cryptocurrency_name': {'cryptocurrency', 'name'}, 'uri_path': {'uri', 'path'}, 'postcode_in_state': {'in', 'state', 'postcode'}, 'random_number': {'number', 'random'}, 'default_country': {'country', 'default'}, 'vin': {'vin'}, 'price_in_btc': {'btc', 'price', 'in'}, 'current_country': {'country', 'current'}, 'birthdate': {'birthdate'}, 'identifier': {'identifier'}, 'unix_partition': {'partition', 'unix'}, 'pyint': {'pyint'}, 'ipv4_private': {'private', 'ipv4'}, 'random_sample': {'random', 'sample'}, 'passport_dob': {'dob', 'passport'}, 'gender_symbol': {'symbol', 'gender'}, 'seed_locale': {'locale', 'seed'}, 'swift11': {'swift11'}, 'country': {'country'}, 'past_datetime': {'past', 'datetime'}, 'free_email': {'email', 'free'}, 'ipv6': {'ipv6'}, 'hostname': {'hostname'}, 'passport_gender': {'passport', 'gender'}, 'secondary_address': {'secondary', 'address'}, 'prefix': {'prefix'}, 'random_element': {'random', 'element'}, 'time_object': {'object', 'time'}, 'date_time_this_century': {'time', 'date', 'this', 'century'}, 'bban': {'bban'}, 'pystruct': {'pystruct'}, 'unix_time': {'time', 'unix'}, 'rgb_css_color': {'css', 'color', 'rgb'}, 'isd_code': {'isd', 'code'}, 'boolean': {'boolean'}, 'local_latlng': {'local', 'latlng'}, 'credit_card_expire': {'credit', 'card', 'expire'}, 'job': {'job'}, 'iana_id': {'iana', 'id'}, 'name_nonbinary': {'name', 'nonbinary'}, 'domain_word': {'word', 'domain'}, 'text': {'text'}, 'formatted_time': {'formatted', 'time'}, 'first_name': {'name', 'first'}, 'postcode': {'postcode'}, 'timezone': {'timezone'}, 'xml': {'xml'}, 'chrome': {'chrome'}, 'firefox': {'firefox'}, 'random_digit_not_null': {'not', 'random', 'digit', 'null'}, 'military_apo': {'apo', 'military'}, 'json_bytes': {'json', 'bytes'}, 'stock_exchange': {'stock', 'exchange'}, 'postalcode': {'postalcode'}, 'ipv4': {'ipv4'}, 'month': {'month'}, 'ascii_free_email': {'email', 'free', 'ascii'}, 'zipcode_plus4': {'zipcode', 'plus4'}, 'last_name_female': {'name', 'last', 'female'}, 'name': {'name'}, 'political_views': {'political', 'views'}, 'federal_subject': {'federal', 'subject'}, 'dga': {'dga'}, 'random_digit_or_empty': {'random', 'or', 'digit', 'empty'}, 'name_female': {'name', 'female'}, 'street_name': {'street', 'name'}, 'fruit': {'fruit'}, 'mac_platform_token': {'token', 'mac', 'platform'}, 'ascii_company_email': {'company', 'email', 'ascii'}, 'words': {'words'}, 'gender_code': {'code', 'gender'}, 'continent': {'continent'}, 'suffix_female': {'suffix', 'female'}, 'pydecimal': {'pydecimal'}, 'views_on': {'on', 'views'}, 'tsv': {'tsv'}, 'price': {'price'}, 'safe_domain_name': {'safe', 'domain', 'name'}, 'height': {'height'}, 'street_suffix': {'street', 'suffix'}, 'current_country_code': {'country', 'code', 'current'}, 'currency_code': {'currency', 'code'}, 'prefix_female': {'prefix', 'female'}, 'null_boolean': {'boolean', 'null'}, 'sentence': {'sentence'}, 'sbn9': {'sbn9'}, 'tar': {'tar'}, 'quote': {'quote'}, 'occupation': {'occupation'}, 'bothify': {'bothify'}, 'postal_code': {'postal', 'code'}, 'drink': {'drink'}, 'doi': {'doi'}, 'random_letters': {'random', 'letters'}, 'ssn': {'ssn'}, 'profile': {'profile'}, 'alphabet': {'alphabet'}, 'domain_name': {'domain', 'name'}, 'dsv': {'dsv'}, 'bank': {'bank'}, 'pystr': {'pystr'}, 'coordinates': {'coordinates'}, 'catch_phrase': {'phrase', 'catch'}, 'company_email': {'company', 'email'}, 'color_rgb': {'color', 'rgb'}, 'pricetag': {'pricetag'}, 'swift': {'swift'}, 'csv': {'csv'}, 'date_this_month': {'month', 'date', 'this'}, 'prefix_male': {'prefix', 'male'}, 'enum': {'enum'}, 'region': {'region'}, 'user_agent': {'user', 'agent'}, 'random_elements': {'random', 'elements'}, 'zipcode': {'zipcode'}, 'pyobject': {'pyobject'}, 'bulk_create_datetimes': {'datetimes', 'create', 'bulk'}, 'pyset': {'pyset'}, 'iata_code': {'code', 'iata'}, 'currency_name': {'currency', 'name'}, 'tld': {'tld'}, 'basic_phone_number': {'number', 'basic', 'phone'}, 'date_between': {'date', 'between'}, 'timestamp': {'timestamp'}, 'date_time_ad': {'ad', 'time', 'date'}, 'city_suffix': {'suffix', 'city'}, 'credit_card_provider': {'credit', 'provider', 'card'}, 'cryptocurrency_symbol': {'symbol', 'cryptocurrency'}, 'simple_profile': {'simple', 'profile'}, 'safe_color_name': {'safe', 'name', 'color'}, 'password': {'password'}, 'random_digit': {'random', 'digit'}, 'random_digit_above_two': {'random', 'above', 'digit', 'two'}, 'texts': {'texts'}, 'date_this_year': {'year', 'date', 'this'}, 'file_path': {'file', 'path'}, 'job_female': {'job', 'female'}, 'invalid_ssn': {'invalid', 'ssn'}, 'date': {'date'}, 'answer': {'answer'}, 'iso8601': {'iso8601'}, 'week_date': {'week', 'date'}, 'time_series': {'time', 'series'}, 'msisdn': {'msisdn'}, 'pystr_format': {'format', 'pystr'}, 'pybool': {'pybool'}, 'isbn13': {'isbn13'}, 'datetime': {'datetime'}, 'cryptocurrency_iso_code': {'cryptocurrency', 'code', 'iso'}, 'email': {'email'}, 'cryptocurrency_code': {'cryptocurrency', 'code'}, 'ascii_safe_email': {'safe', 'email', 'ascii'}, 'upc_e': {'upc', 'e'}, 'street_number': {'number', 'street'}, 'day_of_week': {'week', 'day', 'of'}, 'future_datetime': {'future', 'datetime'}, 'paragraph': {'paragraph'}, 'pytuple': {'pytuple'}, 'ean13': {'ean13'}, 'rgb_color': {'color', 'rgb'}, 'passport_owner': {'owner', 'passport'}, 'year': {'year'}, 'coordinate': {'coordinate'}, 'random_int': {'random', 'int'}, 'formatted_datetime': {'formatted', 'datetime'}, 'localized_ean8': {'localized', 'ean8'}, 'country_code': {'country', 'code'}, 'pytimezone': {'pytimezone'}, 'currency_symbol': {'currency', 'symbol'}, 'url': {'url'}, 'postalcode_in_state': {'postalcode', 'in', 'state'}, 'first_name_male': {'male', 'name', 'first'}, 'last_name_nonbinary': {'name', 'last', 'nonbinary'}, 'pyiterable': {'pyiterable'}, 'add_provider': {'add', 'provider'}, 'word': {'word'}, 'first_name_nonbinary': {'name', 'first', 'nonbinary'}, 'android_platform_token': {'token', 'android', 'platform'}, 'latitude': {'latitude'}, 'passport_number': {'number', 'passport'}, 'mac_address': {'mac', 'address'}, 'suffix_nonbinary': {'suffix', 'nonbinary'}, 'title': {'title'}, 'get_formatter': {'get', 'formatter'}, 'hexify': {'hexify'}, 'currency': {'currency'}, 'linux_processor': {'linux', 'processor'}, 'weight': {'weight'}, 'date_time_between': {'time', 'date', 'between'}, 'zip_code': {'zip', 'code'}, 'time_delta': {'time', 'delta'}, 'postalcode_plus4': {'plus4', 'postalcode'}, 'date_time_between_dates': {'time', 'dates', 'date', 'between'}, 'image_url': {'image', 'url'}, 'longitude': {'longitude'}, 'zip': {'zip'}, 'pydict': {'pydict'}, 'uri_extension': {'extension', 'uri'}, 'sha1': {'sha1'}, 'get_words_list': {'get', 'words', 'list'}, 'name_male': {'male', 'name'}, 'opera': {'opera'}, 'ein': {'ein'}, 'company_suffix': {'suffix', 'company'}, 'day_of_month': {'month', 'day', 'of'}, 'country_calling_code': {'code', 'country', 'calling'}, 'future_date': {'future', 'date'}, 'reseed': {'reseed'}, 'iban': {'iban'}, 'military_ship': {'ship', 'military'}, 'stock_ticker': {'stock', 'ticker'}, 'http_method': {'method', 'http'}, 'surname': {'surname'}, 'last_name_male': {'male', 'name', 'last'}, 'color_hsv': {'hsv', 'color'}, 'locale': {'locale'}, 'date_this_century': {'date', 'this', 'century'}, 'windows_platform_token': {'windows', 'token', 'platform'}, 'ios_platform_token': {'token', 'ios', 'platform'}, 'nic_handles': {'nic', 'handles'}, 'nic_handle': {'nic', 'handle'}, 'set_formatter': {'set', 'formatter'}, 'dish': {'dish'}, 'localized_ean13': {'localized', 'ean13'}, 'sha256': {'sha256'}, 'license_plate': {'license', 'plate'}, 'internet_explorer': {'internet', 'explorer'}, 'Meta': {'Meta'}, 'date_time': {'time', 'date'}, 'pyfloat': {'pyfloat'}, 'stock_name': {'stock', 'name'}, 'administrative_unit': {'administrative', 'unit'}, 'formatted_date': {'formatted', 'date'}, 'military_dpo': {'dpo', 'military'}, 'time': {'time'}, 'isbn10': {'isbn10'}, 'state': {'state'}, 'military_state': {'state', 'military'}, 'city': {'city'}, 'first_name_female': {'name', 'first', 'female'}, 'street_address': {'street', 'address'}, 'file_name': {'file', 'name'}, 'color_rgb_float': {'float', 'color', 'rgb'}, 'upc_a': {'upc', 'a'}, 'date_time_this_month': {'month', 'time', 'date', 'this'}, 'md5': {'md5'}, 'validate_enum': {'enum', 'validate'}, 'ascii_email': {'email', 'ascii'}, 'ean8': {'ean8'}, 'mac_processor': {'mac', 'processor'}, 'date_object': {'object', 'date'}, 'prefix_nonbinary': {'prefix', 'nonbinary'}, 'parse': {'parse'}, 'color': {'color'}, 'paragraphs': {'paragraphs'}, 'month_name': {'month', 'name'}, 'cryptocurrency': {'cryptocurrency'}, 'country_emoji_flag': {'emoji', 'country', 'flag'}, 'aba': {'aba'}, 'language_name': {'name', 'language'}, 'seed_instance': {'seed', 'instance'}, 'username': {'username'}, 'academic_degree': {'academic', 'degree'}, 'bank_country': {'country', 'bank'}, 'file_extension': {'extension', 'file'}, 'binary': {'binary'}, 'image': {'image'}, 'linux_platform_token': {'linux', 'token', 'platform'}, 'location_on_land': {'on', 'location', 'land'}, 'province': {'province'}, 'itin': {'itin'}, 'date_between_dates': {'dates', 'date', 'between'}, 'random_choices': {'random', 'choices'}, 'passport_dates': {'passport', 'dates'}, 'credit_card_full': {'credit', 'full', 'card'}, 'building_number': {'number', 'building'}, 'random_uppercase_letter': {'random', 'uppercase', 'letter'}, 'fixed_width': {'fixed', 'width'}, 'lexify': {'lexify'}, 'spices': {'spices'}, 'date_time_this_year': {'time', 'year', 'date', 'this'}, 'user_name': {'user', 'name'}, 'date_time_this_decade': {'decade', 'time', 'date', 'this'}, 'language_code': {'code', 'language'}, 'worldview': {'worldview'}, 'ipv4_public': {'public', 'ipv4'}, 'suffix': {'suffix'}, 'date_of_birth': {'birth', 'date', 'of'}}
    },
}

python_builtin_types = {
    str,
    int,
    float,
    Decimal,
    bool,
    complex,
    bytes,
    tuple,
    list,
    set,
    frozenset,
    dict,
}
typing_origins = {List, Dict, Tuple, Set, Union, Literal, Optional}
recursive_types = {
    List,
    Dict,
    Tuple,
    Set,
    Union,
    Literal,
    Optional,
    list,
    dict,
    tuple,
    set,
    frozenset,
}
all_constr_attribs = {
    "default",
    "annotation",
    "min_length",
    "max_length",
    "pattern",
    "gt",
    "lt",
    "ge",
    "le",
    "multiple_of",
}

default_constr_dict = {
    "required": True,
    "default": None,
    "annotation": None,
    "min_length": None,
    "max_length": None,
    "pattern": None,
    "gt": None,
    "lt": None,
    "ge": None,
    "le": None,
    "multiple_of": None,
    "origin": None,
    "args": None,
}
        