from typing import (
    List,
    Dict,
    Tuple,
    Set,
    Union,
    Optional,
    Literal,
    Any,
    Type,
)
from smoke_mirrors.synthesiser.constraints import make_one_string, get_applied_constraints, check_generation_constraints
from smoke_mirrors.synthesiser.matching_fields import match_fields
from smoke_mirrors.synthesiser.provider_methods import list_match_methods, make_resolved_methods
from smoke_mirrors.tools.model_funcs import get_json_model_fields, infer_json_type, get_json_model_data, infer_json_args, is_json_model, flatten_json_types, load_parse_json_schema
from smoke_mirrors.pre_made_data import provider_methods
from smoke_mirrors.tools.regex_generator import regex_builder
from collections import deque
from multiprocessing import Pool
from functools import partial
from smoke_mirrors.library.jsonschemaclass import JsonSchemaClass
from decimal import Decimal
from smoke_mirrors.pre_made_data import (
    default_constr_dict,
    recursive_types,
    python_builtin_types,
    provider_return_types
)
from jsonschema import validate
from jsonschema.validators import validator_for
from jsonschema.exceptions import ValidationError
import re
import time
import string
import random
import rstr
import exrex
import math

from rich import print as richprint


"""
Generation path:\n
    format of  'Schema_name(field_name)[amount/length]'
    format of  'n(f)[a].Type(index)[amount/length]'
    e.g.
    1:\n
        class User():
            address: (_,_,_)
        User(address)[1].Tuple(0)[1]
        -> would be generating a data pool for
        class User():
            address: (X,_,_)
    2:\n
        class Address():
            street : str
        class User():
            nested : Address
        User(nested)[100].Address(street)[1]
    3:\n
        class User():
            address: List[str,int]
        User(address)[1].List(0)[10]
        -> means
            [str]*10
        
        User(address)[1].List(1)[20]
        -> means
            [int]*20
"""


def print_path(generate_path, elapsed_time,print):
    """
    inputs:
        generate path
        elapsed time
    prints based on path depth:
        Time taken: ... seconds          path
    """
    pooling_depth = len(list(map(int, re.findall(r"\[(\d+)\]", generate_path))))
    time_str = f"{elapsed_time:.2f}"
    print(
        f"Time taken: {time_str} seconds",
        " " * (10 - max(10, len(time_str))),
        "    " * (pooling_depth - 1),
        generate_path,
    )


string_list = string.ascii_letters + string.digits

safe_builtins = {
    "len": len, "range": range, "min": min, "max": max, "sum":sum, "sorted":sorted, "any":any,
    "list": list, "tuple": tuple, "chr": chr, "ord": ord,
    "set": set, "map": map, "int": int, "AssertionError": AssertionError,
    "enumerate": enumerate, "reversed": reversed,
    "str": str, "RuntimeError": RuntimeError, "ValueError": ValueError,
    "TypeError": TypeError, "print": print, "bool": bool,
}
env = {
    "__builtins__": safe_builtins,
    "random": random,
    "string": string,
    "deque": deque,
}
def regex_parallel_worker(args,_):
    src, amount = args
    exec(src, env)
    gen = env["gen"]
    return [gen() for _ in range(amount)]


def validate_synthesised_data(synthesised_data: Dict, schema_model: List[Dict],instances=None) -> None:
    if instances is not None:
        try:
            instances[0].validate(synthesised_data)
        except:
            instances[1].validate(synthesised_data)
    else:
        try:
            validate(instance=synthesised_data, schema=schema_model.contents)
        except:
            validate(instance=synthesised_data, schema=schema_model.sanitised_contents)

class JsonSynthesiser():
    def __init__(self, method="faker",stdcout=False,rich_output=False):
        self.outputpooling = {}
        self.applied_constraints_cache = {}
        self.schema_keys_cache = {}
        self.method = method
        data_set = provider_methods[method]
        self.word_list, methods_map = list_match_methods(method)
        self.word_tokens = data_set['word_tokens'] # {word: word.split("_") for word in word_list}
        self.word_tokens_set = data_set['word_tokens_set'] # {word: set(word.split("_")) for word in word_list}
        self.resolved_methods = make_resolved_methods(self.word_list, methods_map)
        self.stdcout = stdcout
        self.defs = {}
        self.applied_constraints = {}
        self.field_match_pairs = {}
        self.yield_schema = None
        self.yield_schema_data = None
        self.PERFORMANCE = False
        self.print = richprint if rich_output else print

    # ----- Constraint based generation -----
    def generate_from_constraints(
        self, field_name:str, constraints:Dict[str,Any], generate_path:str
    ) -> Any:  # value
        """
        Inputs:\n
            field_name
            constraints ( generated by check_generation_constraints() )
            generation path string
        Outputs:\n
            a single generated value based on constraints
            if a data pool for the generation path hasnt been made:
                it will first generate a data pool for the path
        """

        # print(f"Name:{field_name}\nFields:{constraints}")
        # print("__")
        data_type = constraints["annotation"]
        if generate_path in self.outputpooling:
            length_of_pool = len(self.outputpooling[generate_path])
        else:
            length_of_pool = 0
        if length_of_pool == 0:
            pooling_numbers = list(map(int, re.findall(r"\[(\d+)\]", generate_path)))
            amount = pooling_numbers[0]
            pooling_count = 1
            for x in pooling_numbers:
                pooling_count *= x

            start_time = time.time()
            data_pool = []

            if constraints["pattern"] is not None:
                # print(f"Path:{generate_path}")
                # HERE HERE
                # check if a map exists for this constraint sequence (pattern and constraints)
                # if there is not, generate a map of possible results and then run regex forward pass over each (could be slow for initial pass through)
                # save the forward pass map to global

                # print(constraints["pattern"])

                min_length = constraints["min_length"]
                max_length = constraints["max_length"]
                pattern = constraints["pattern"]

                quantifier_match = re.search(r"(.*?)(\{\d+(?:,\d*)?\})(\$?)$", pattern)
                if quantifier_match:
                    base, quant, end = quantifier_match.groups()
                    
                    m = re.match(r"\{(\d+)(?:,(\d*))?\}", quant)
                    if m:
                        existing_min = int(m.group(1))
                        existing_max = int(m.group(2)) if m.group(2) not in (None, '') else None

                        new_min = min_length if min_length is not None else existing_min
                        if max_length is not None:
                            new_max = max_length
                        else:
                            new_max = existing_max

                        if new_max is None:
                            new_quant = f"{{{new_min}}}"
                        elif new_min == new_max:
                            new_quant = f"{{{new_min}}}"
                        else:
                            new_quant = f"{{{new_min},{new_max}}}"

                        pattern = base + new_quant + end
                else:
                    if pattern.endswith("$"):
                        pattern = pattern[:-1]
                    while pattern and pattern[-1] in ["+", "*", "?"]:
                        pattern = pattern[:-1]

                    if min_length is None and max_length is None:
                        pattern = pattern
                    elif min_length is not None and max_length is None:
                        pattern = pattern + f"{{{min_length}}}$"
                    elif min_length is None and max_length is not None:
                        pattern = pattern + f"{{0,{max_length}}}$"
                    else:
                        pattern = pattern + f"{{{min_length},{max_length}}}$"
                # print(pattern)
                # print(exrex.getone(pattern))
                # print(self.make_one_string(pattern))

                # now required due to pattern constraints being auto generated by model.model_json_schema and containing lookarounds
                src = regex_builder.compile_regex_to_function_source(pattern,max_repeat=max(2,pooling_count//amount))
                thread_count = 8
                tries = 0
                exec(src, env)
                gen = env["gen"]
                if (pooling_count//thread_count+1) >= 10000 and self.PERFORMANCE:
                    worker_func = partial(regex_parallel_worker, (src, max(1,pooling_count//thread_count+1)))
                    with Pool(thread_count) as p:
                        data_pool_list = p.map(worker_func, range(thread_count))

                    data_pool = [item for temp_list in data_pool_list for item in temp_list]
                else:
                    data_pool = [gen() for _ in range(max(1, pooling_count))]
                data_pool = [ val for val in data_pool if re.fullmatch(pattern,val) ]
                while len(data_pool) < max(1, pooling_count) or tries == max(1, pooling_count):
                    val = gen()
                    if re.fullmatch(pattern,val):
                        data_pool.append(val)
                    tries+=1
                if len(data_pool) < max(1, pooling_count):
                    if self.PERFORMANCE:
                        with Pool() as p:
                            data_pool = p.map(
                                make_one_string, [pattern] * max(1, pooling_count)
                            )
                    else:
                        if "(?" not in pattern: 
                            try:
                                data_pool = [
                                    exrex.getone(pattern) for _ in range(max(1, pooling_count))
                                ]
                            except Exception as e:
                                self.print(f"failed reg pool and used fallback: {e}")
                                data_pool = [
                                    rstr.xeger(pattern) for _ in range(max(1, pooling_count))
                                ]
                        else:
                            raise ValueError(f"Pattern '{pattern}' contains unhandled lookarounds and failed to generate")

                if data_pool == []:
                    raise Exception(f"No data pool for {constraints['pattern']}")
            else:
                if data_type is str:
                    temp_string_list = string_list
                    min_length = constraints.get("min_length")
                    max_length = constraints.get("max_length")
                    if min_length is None:
                        min_length = 1
                    if max_length is None:
                        max_length = min_length + max(1, (pooling_count // amount)) + 3
                    
                    temp_string_list = string.ascii_letters + string.digits
                    r_range = range(min_length, max_length+1)
                    random_vals = random.choices(r_range,k=max(1, pooling_count))
                    data_pool = ["".join(random.choices(temp_string_list,k=(rv)))for rv in random_vals]

                    if data_pool == []:
                        raise Exception(f"No data pool for str:{generate_path}")

                elif data_type in (int,float,Decimal):
                    lt = constraints.get("lt")
                    le = constraints.get("le")
                    gt = constraints.get("gt")
                    ge = constraints.get("ge")
                    multiple_of = constraints.get("multiple_of")
                    
                    if lt is None:
                        if gt is None:
                            lt = 10 * max(1, (pooling_count // amount) + 3)
                        else:
                            lt = gt+(10 * max(1, (pooling_count // amount) + 3))
                    else:
                        lt = lt - 1
                    if le is not None:
                        lt = min(lt, le)

                    if gt is None:
                        gt = lt * -1
                    else:
                        if data_type is int:
                            gt = gt + 1
                        else:
                            if multiple_of is not None:
                                gt = gt + multiple_of
                    if ge is not None:
                        gt = max(gt, ge)

                    if gt >= lt:
                        raise Exception(f"Value for gt:{gt} is greater than or equal to value for lt:{lt}")

                    if multiple_of is not None:
                        gt = math.nextafter(gt, float('inf'))
                        lt = math.nextafter(lt, float('-inf'))
                        multiple_of = Decimal(str(constraints["multiple_of"]))
                        first = (Decimal(Decimal(gt) + multiple_of) // multiple_of) * multiple_of

                        count = Decimal(lt - gt) // multiple_of
                        if count <= 0:
                            raise Exception(
                                f"No multiples of {multiple_of} fit in the range [{gt}, {lt})."
                            )

                        data_pool = [
                            first + Decimal(idx+1+random.randint(0,int(count)-1)) * multiple_of
                            for idx in range(pooling_count)
                        ]
                        random.shuffle(data_pool)
                    else:
                        if data_type == int:
                            r_range = range(gt,lt+1)
                            data_pool = random.choices(r_range,k=max(1, pooling_count))
                        else:
                            gt = math.nextafter(gt, float('inf'))
                            lt = math.nextafter(lt, float('-inf'))
                            data_pool = [random.uniform(gt,lt) for _ in range(pooling_count)]
                    if data_pool == []:
                        raise Exception(f"No data pool for num:{generate_path}")

                    # if the data pool doesnt have enough elements, extend it with copies of existing elements
                    original_len = len(data_pool)
                    while len(data_pool) < pooling_count:
                        # Append elements from the original list in order
                        for item in data_pool[:original_len]:
                            if len(data_pool) < pooling_count:
                                data_pool.append(item)
                            else:
                                break
                elif data_type is bool:
                    r_range = [0,1]
                    data_pool = random.choices(r_range,k=max(1, pooling_count))
                    data_pool = [x == 1 for x in data_pool]
                    if data_pool == []:
                        raise Exception(f"No data pool for bool:{generate_path}")
                elif data_type is complex:
                    # return_value= '0+0j'
                    max_num = 10 ** max(1, (pooling_count // amount) + 3)
                    min_num = max_num * -1

                    data_pool = [
                        complex(
                            random.randint(0, min_num + max_num) - min_num,
                            random.randint(0, min_num + max_num) - min_num,
                        )
                        for _ in range(max(1, pooling_count))
                    ]
                    if data_pool == []:
                        raise Exception(f"No data pool for complex:{generate_path}")
                elif data_type is bytes:
                    min_length = constraints.get("min_length")
                    max_length = constraints.get("max_length")
                    if min_length is None:
                        min_length = 1
                        
                    if max_length is None:
                        max_length = min_length + max(1, (pooling_count // amount)) + 3
                    data_pool = [
                        random.randbytes(random.randint(min_length, max_length))
                        for _ in range(max(1, pooling_count))
                    ]
                    if data_pool == []:
                        raise Exception(f"No data pool for bytes:{generate_path}")
                else:
                    raise Exception(f"No data pool for default:{generate_path}")

            elapsed_time = time.time() - start_time  # end timer
            if self.stdcout:
                print_path(generate_path, elapsed_time, self.print)

            self.outputpooling[generate_path] = data_pool
            # print(f"Pool | Time taken: {elapsed_time:.2f} seconds\n")
        return_value = self.outputpooling[generate_path].pop()
        if (length_of_pool-1) == 0:
            del self.outputpooling[generate_path]
        if not isinstance(return_value,data_type):
            if data_type is bytes:
                return_value = data_type(str(return_value), "utf-8")
            elif constraints["multiple_of"] is None:
                return_value = data_type(return_value)
        # input("wait...")
        # exit()
        return return_value

    def apply_constraints(
        self,
        return_value:Any,
        constraints:Dict[str,Any],
        match_name:str,
        generate_path:str,
        pooling_count:int,
        amount:int,
    ) -> Any:
        """
        Input:\n
            value
            value contraints
            generation provider name
            generation path
            path amount
            batch amount
        Output:\n
            value with constraints applied to it
        """
        data_type = constraints.get("annotation")
        if not isinstance(return_value,data_type):
            try:
                return_value = data_type(return_value)
            except (ValueError, TypeError):
                return_value = None
        if data_type is str:
            min_length = constraints.get("min_length")
            max_length = constraints.get("max_length")
            if min_length is None:
                min_length = 1
            if len(return_value) < min_length:
                pad_length = min_length - len(return_value)
                return_value += "".join(random.choices(string_list, k=pad_length))
            if max_length is not None:
                if len(return_value) > max_length:
                    return_value = return_value[:max_length]

        elif data_type in (int,float):
            if return_value is None:
                return_value = self.generate_from_constraints(
                    match_name, constraints, generate_path
                )
            else:
                lt = constraints.get("lt")
                le = constraints.get("le")
                gt = constraints.get("gt")
                ge = constraints.get("ge")
                multiple_of = constraints.get("multiple_of")
                
                if lt is None:
                    if gt is None:
                        lt = 10 * max(1, (pooling_count // amount) + 3)
                    else:
                        lt = gt+(10 * max(1, (pooling_count // amount) + 3))
                else:
                    lt = lt - 1
                if le is not None:
                    lt = min(lt, le)

                if gt is None:
                    gt = lt * -1
                else:
                    if data_type is int:
                        gt = gt + 1
                    else:
                        if multiple_of is not None:
                           gt = gt + multiple_of
                if ge is not None:
                    gt = max(gt, ge)

                if gt >= lt:
                    raise Exception(f"Value for gt:{gt} is greater than or equal to value for lt:{lt}")

                if multiple_of is not None:
                    first = ((gt + multiple_of) // multiple_of) * multiple_of

                    count = (lt - gt) // multiple_of
                    if count <= 0:
                        raise Exception(
                            f"No multiples of {multiple_of} fit in the range [{gt}, {lt})."
                        )
                    idx = (return_value // multiple_of) % count

                    return_value = first + idx * multiple_of
                else:
                    if return_value >= lt or return_value <= gt:
                        return_value = return_value%(lt-gt)+gt
                        if data_type == int:
                            if lt-gt <= 1:
                                raise Exception(f"No whole integers are greater than {gt} and less than {lt}")
                            return_value = min(lt-1,max(gt+1,return_value))
                        else:
                            gt = math.nextafter(gt, float('inf'))
                            lt = math.nextafter(lt, float('-inf'))
                            return_value = min(lt,max(gt,return_value))


        elif data_type is bool:
            try:
                return_value = bool(return_value)
            except:
                return_value = random.choice([True, False])

        elif data_type in (complex,bytes):
            try:
                return_value = complex(return_value)
            except:
                return_value = self.generate_from_constraints(
                    match_name, constraints, generate_path
                )
        if data_type is bytes:
            return_value = data_type(str(return_value), "utf-8")
        else:
            return_value = data_type(return_value)
        return return_value
    # ----- Constraint based generation -----

    # ----- Synth based generation -----  
    def generate_synth_data(
        self, field_name:str, match_name:str, applied_constraints:Dict[str,Any], generate_path:str
    ) -> Any:
        """
        Inputs:\n
            field name
            match name
            constraints
            generate path
        Recursive function that crawls through the constraints structure\n
        Handles collection types and model recursion\n
        Outputs:\n
            python structure of the constraints format with fully generated data
        """
        # print("__")
        # print(f"	Generating for: {field_name}")
        # print(applied_constraints)
        # data_type = get_origin(applied_constraints["annotation"])
        if generate_path in self.applied_constraints_cache:
            applied_constraints = self.applied_constraints_cache[generate_path]
        else:
            applied_constraints = check_generation_constraints(field_name,applied_constraints["origin"])
            self.applied_constraints_cache[generate_path] = applied_constraints
        data_type = applied_constraints["annotation"]
            
        # all traversals can be considered "annotated"
        if data_type is type(None) or data_type is None:
            return None
        elif data_type in recursive_types:
            data_args = applied_constraints["args"]
            if applied_constraints["min_length"] is not None:
                min_amount = applied_constraints["min_length"]
            else:
                min_amount = 1
            if applied_constraints["max_length"] is not None:
                max_amount = applied_constraints["max_length"]
            else:
                max_amount = min_amount + 4

            new_applied_constraints = {**default_constr_dict, **applied_constraints}
            if len(data_args) == 0:
                type_args_list = [{"annotation":str,"origin":{"type":"string"},"args":[]}]
            else:
                type_args_list = [{"annotation":infer_json_type(chosen_type),"origin":chosen_type,"args":infer_json_args(chosen_type)} for chosen_type in data_args]

            if data_type in [List, list]:
                output_data = []
                new_applied_constraints.update(type_args_list[0])
                list_generate_path = (
                    generate_path + f".List(0)[{max_amount}]"
                )
                output_data = [
                        self.generate_synth_data(
                            field_name,
                            match_name,
                            new_applied_constraints,
                            list_generate_path,
                        )
                    for _ in range(random.randint(min_amount, max_amount))
                ]
            
            elif data_type in [Dict, dict]:
                if len(data_args) == 0:
                    type_args_list.append(type_args_list[0])
                chosen_type_info_left = type_args_list[0]
                chosen_type_info_right = type_args_list[1]
                new_left_applied_constraints = {**new_applied_constraints, **chosen_type_info_left}
                new_right_applied_constraints = {**new_applied_constraints, **chosen_type_info_right}

                output_data = {}
                target_amount = random.randint(min_amount, max_amount)
                current_tries = 0
                target_amountx2 = target_amount * 2
                # for x in range(random.randint(min_amount,max_amount)):
                dict_keys = set()
                generate_path_left = f"{generate_path}.Dict(L)[{max_amount}]"
                generate_path_right = f"{generate_path}.Dict(R)[{max_amount}]"

                while len(dict_keys) < target_amount and current_tries < target_amountx2:
                    v1 = self.generate_synth_data(
                        field_name,
                        match_name,
                        new_left_applied_constraints,
                        generate_path_left,
                    )
                    dict_keys.add(v1)
                    current_tries += 1

                if len(dict_keys) < min_amount:
                    raise Exception(
                        f"Not enough provider keys for {field_name}, "
                        f"keys generated: {len(dict_keys)} / {min_amount}"
                    )
                output_data = {
                    key: self.generate_synth_data(
                        field_name,
                        match_name,
                        new_right_applied_constraints,
                        generate_path_right,
                    )
                    for key in dict_keys
                }

            elif data_type in [Tuple, tuple]:
                output_data = []
                if len(data_args) == 0:
                    type_args_list.extend([type_args_list[0] for _ in range(random.randint(min_amount, max_amount))])
                for x in range(len(data_args)):
                    chosen_type_info = type_args_list[x]
                    new_applied_constraints.update(chosen_type_info)
                    tuple_generate_path = (
                        generate_path + f".Tuple({x})[{max_amount}]"
                    )
                    output_data.append(
                        self.generate_synth_data(
                            field_name,
                            match_name,
                            new_applied_constraints,
                            tuple_generate_path,
                        )
                    )

            elif data_type in [Set, set, frozenset]:
                output_data = set()
                target_amount = random.randint(min_amount, max_amount)
                chosen_type_info = type_args_list[0]
                new_applied_constraints.update(chosen_type_info)
                current_tries = 0
                target_amountx2 = target_amount * 2
                if data_type is frozenset:
                    pathstr = "FrozenSet"
                else:
                    pathstr = "Set"
                set_generate_path = (
                    generate_path + f".{pathstr}(0)[{max_amount}]"
                )
                while len(output_data) < target_amount and current_tries < target_amountx2:
                    output_data.add(
                        self.generate_synth_data(
                            field_name,
                            match_name,
                            new_applied_constraints,
                            set_generate_path,
                        )
                    )
                    current_tries += 1

                if len(output_data) < min_amount:
                    raise Exception(
                        f"Not enough provider keys for {field_name}, "
                        f"keys generated: {len(output_data)} / {min_amount}"
                    )
                output_data = list(output_data)

            elif data_type == Union:
                chosen_index = random.randint(0, len(type_args_list) - 1)
                chosen_type_info = type_args_list[chosen_index]
                new_applied_constraints.update(chosen_type_info)
                generate_path += f".Union({chosen_index})"
                output_data = self.generate_synth_data(
                    field_name, match_name, new_applied_constraints, generate_path
                )

            elif data_type == Optional:
                # should use Union, but still here for fallback
                type_args_list.append(None)
                chosen_index = random.randint(0, len(type_args_list) - 1)
                chosen_type_info = type_args_list[chosen_index]
                if chosen_type_info is None:
                    output_data = None
                else:
                    new_applied_constraints.update(chosen_type_info)
                    generate_path += f".Optional({chosen_index})"
                    output_data = self.generate_synth_data(
                        field_name,
                        match_name,
                        new_applied_constraints,
                        generate_path,
                    )

            elif data_type == Literal:
                output_data = random.choice(data_args)

            else:
                raise Exception(
                    f"Recersive data type| {data_type} : {data_args} |not handled"
                )
        elif data_type in python_builtin_types:
            if match_name == "":
                func = None
            else:
                func = self.resolved_methods[match_name]
            if (applied_constraints["pattern"] is not None) or (match_name == "") or (match_name != "" and provider_return_types[match_name] != applied_constraints["annotation"]):
                output_data = self.generate_from_constraints(
                    field_name, applied_constraints, generate_path
                )
            else:
                if generate_path not in self.outputpooling or (
                    len(self.outputpooling[generate_path]) == 0
                ):
                    pooling_numbers = list(
                        map(int, re.findall(r"\[(\d+)\]", generate_path))
                    )
                    pooling_count = 1
                    for x in pooling_numbers:
                        pooling_count *= x

                    start_time = time.time()
                    data_temp_pool = [func() for _ in range(pooling_count)]

                    if any([applied_constraints.get(constraint) is not None for constraint in ["lt","le","gt","ge","multiple_of","min_length","max_length"]]):
                        data_pool = [
                            self.apply_constraints(
                                func_val,
                                applied_constraints,
                                match_name,
                                generate_path,
                                pooling_count,
                                pooling_numbers[0],
                            )
                            for func_val in data_temp_pool
                        ]
                    else:
                        data_pool = [ data_type(temp_data) for temp_data in data_temp_pool ]

                    elapsed_time = time.time() - start_time
                    if self.stdcout:
                        print_path(generate_path, elapsed_time, self.print)

                    self.outputpooling[generate_path] = data_pool
                output_data = self.outputpooling[generate_path].pop()

        else:
            if data_type is JsonSchemaClass:
                ref_name = applied_constraints["origin"]["$ref"].split("/")[-1]
                data_type = self.defs[ref_name]
                output_data = self.synthesise_recursive(
                    data_type, self.method, amount=1, path=generate_path + "."
                )
                # print("big nested")

            else:
                raise Exception(
                    f"Unkown data type ({data_type}) for field {field_name}"
                )
        # apply constraints of output after data is provided
        return output_data

    def generate_single_value(self, field_name:str, field_type:Type) -> Any:
        """
        Inputs:\n
            field_name
            field_type
        Outputs:\n
            single generated value
        """
        matched_field = match_fields([field_name],self.method,field_types={field_name:field_type})
        value = None
        if matched_field[field_name] != "":
            func = self.resolved_methods[matched_field[field_name]]
            try: #this will fail if the function cant be loaded in the current venv (e.g. importing)
                value = func()
            except:
                pass
        if value != None:
            try:
                value = field_type(value)
            except:
                applied_constraints = default_constr_dict.copy()
                applied_constraints["annotation"] = field_type
                value = self.apply_constraints(
                    value,
                    applied_constraints,
                    matched_field[field_name],
                    "self()[1].generate",
                    1,
                    1,
                )
        else:
            applied_constraints = default_constr_dict.copy()
            applied_constraints["annotation"] = field_type
            value = self.generate_from_constraints(
                field_name, applied_constraints, "self()[1].generate"
            )
        return value
    # ----- Constraint based generation -----

    # ----- recursive functions -----
    def recursive_match_fields(self,schema_model:JsonSchemaClass, method, field_match_pairs:Dict[str,Dict[str,str]]=None) -> Dict[str, Dict[str, str]]:
        """
        Goes through an input schema model and matches all fields to a generation provider\n
        recurses through nested schemas, adding to list of providers for each field\n
        uses optional field_match_pairs input during recursion and remove duplicate nested schemas\n
        Inputs:\n
            schema model
            optional field match pairs (generated during output from recursion)
        Outputs:\n
            field match pairs = {schema name: {field name: match name}}
        """
        if self.defs == {}:
            self.defs = schema_model.defs
        if field_match_pairs is None:
            field_match_pairs = {}
        schema_name = schema_model.__name__
        if schema_model.contents["type"] != "object":
            field_match_pairs[schema_name] = match_fields([schema_name], method, field_types={schema_name:infer_json_type(schema_model.contents)})

        model_data = get_json_model_data(schema_model)
        field_names = [x[0] for x in model_data]

        if schema_name not in field_match_pairs.keys():
            field_match_pairs[schema_name] = match_fields(field_names, method, field_types={name:infer_json_type(content) for name,content in model_data})
        for x in model_data:
            nested_types = [ft for ft in list(flatten_json_types(x[1])) if is_json_model(ft)]
            for nt in nested_types:
                ref_name = nt["$ref"].split("/")[-1]
                if ref_name not in field_match_pairs.keys():
                    # print(data_type.__name__, field_match_pairs.keys())
                    if ref_name not in self.defs:
                        raise Exception(f"'{ref_name}' not in defs '{self.defs}'")
                    if self.defs == {}:
                        raise Exception("Synthesiser .defs have not been defined")
                    field_match_pairs.update(self.recursive_match_fields(self.defs[ref_name],method))
        return field_match_pairs

    def recursive_get_applied_constraints(
        self, schema_model:JsonSchemaClass
    ) -> Dict[str, Dict[str, Dict[str, Any]]]:
        """
        Inputs:\n
            schema model
        Outputs:\n
            nested constraints for all recursed schemas = 
            { 
                schema name: {
                    field name: constraints
                }
            }
        Recursive function to get applied constraint of input schema and all nested schemas\n
        """
        if self.defs == {}:
            self.defs = schema_model.defs
        applied_constraints = {}
        model_data = get_json_model_data(schema_model)

        applied_constraints[schema_model.__name__] = get_applied_constraints(
            schema_model
        )

        for x in model_data:
            nested_types = [ft for ft in list(flatten_json_types(x[1])) if is_json_model(ft)]
            for nt in nested_types:
                ref_name = nt["$ref"].split("/")[-1]
                if ref_name not in applied_constraints.keys():
                    if ref_name not in self.defs:
                        raise Exception(f"'{ref_name}' not in defs '{self.defs}' | consider clearing defs before using internal functions")
                    if self.defs == {}:
                        raise Exception("Synthesiser .defs have not been defined")
                    applied_constraints.update(
                        self.recursive_get_applied_constraints(self.defs[ref_name])
                    )
        return applied_constraints
    # ----- recursive functions -----


    # ----- Central called functions -----
    def synthesise_recursive(
        self, schema_model:JsonSchemaClass, method="faker", amount:int=1, path:str=""
    ) -> Dict[str, Any]:
        """
        The main recursive call of the synthesiser class\n
        Used internally by generate_synth_data for nested schema models\n
        Inputs:\n
            schema model
            method of the methods "faker","mimesis","mixed"
            amount
            generation path
        Outputs:\n
            synthesised data = 
            {field name: content}
        """
        if self.field_match_pairs == {}:
            self.field_match_pairs = self.recursive_match_fields(schema_model,method)
        if self.applied_constraints == {}:
            self.applied_constraints = self.recursive_get_applied_constraints(schema_model)
        schema_name = schema_model.__name__

        synthesised_data = {}
        # print("__")
        if schema_model.contents["type"] != "object":
            generate_path = path + f"{schema_name}({schema_name})[{amount}]"
            synthesised_data = self.generate_synth_data(
                schema_name,
                self.field_match_pairs[schema_name][schema_name],
                self.applied_constraints[schema_name][schema_name],
                generate_path,
            )

        else:
            if schema_name in self.schema_keys_cache:
                schema_keys = self.schema_keys_cache[schema_name]
            else:
                schema_keys = get_json_model_fields(schema_model).keys()
                self.schema_keys_cache[schema_name] = schema_keys
            for name in schema_keys:
                # print(f"Field:{name}")
                if not self.applied_constraints[schema_name][name]["required"]:
                    if random.randint(1, 2) == 1:
                        continue

                generate_path = path + f"{schema_name}({name})[{amount}]"
                # self.apply_constraints(func(), applied_constraints, match_name, generate_path)
                synthesised_data[name] = self.generate_synth_data(
                    name,
                    self.field_match_pairs[schema_name][name],
                    self.applied_constraints[schema_name][name],
                    generate_path,
                )
                # print(f"	Data:{synthesised_data[name]}")
        # print("__")
        return synthesised_data


    def synthesise(
        self, schema_model:Union[JsonSchemaClass,Dict], method=None, amount=1, seed="random",stdcout=False, performance=False
    ) -> List[Dict[str,Any]]:
        """
        The main call function of the synthesiser class
        Inputs:\n
            schema model
            method of methods "faker","mimesis","mixed"
            amount of returned data to generate as int
            data seed as either int or as "random","relational"
        calls recursive synthesis on schema model after initial setup\n
        Ouputs:\n
            list of pydantic BaseModel with synthesised data
            [BaseModel]*amount
        """
        if amount == 0:
            return []
        if isinstance(schema_model,dict):
            if "title" not in schema_model:
                raise Exception("JSON schema must have a title")
            schema_model = JsonSchemaClass(schema_model)
        schema_model = load_parse_json_schema(schema_model)
        if stdcout:
            self.stdcout = stdcout
        self.yield_schema = schema_model
        self.PERFORMANCE = performance
        """
        if seed == "random":
            self.input_seed = "random"
            self.seed = random.randint(0, 1_000_000_000_000)
            random.seed(seed)
        elif seed == "relational":  # not done
            self.input_seed = seed
            self.seed = random.randint(0, 1_000_000_000_000)
            random.seed(seed)
        else:
            print(seed)
            try:
                print("seeded")
                seed = int(seed)
                self.input_seed = seed
                random.seed(seed)
            except:
                print("seed error")
                self.input_seed = seed
                self.seed = random.randint(0, 1_000_000_000_000)
                random.seed(seed)
        """
        self.defs = schema_model.defs
        self.outputpooling.clear()
        self.applied_constraints_cache.clear()
        self.schema_keys_cache.clear()
        if method != None:
            self.method = method
        else:
            method = self.method
        if schema_model.contents["type"] != "object":
            dataset = []
            constraints = check_generation_constraints("",schema_model.contents)
            if "title" in schema_model.contents:
                field_name = schema_model.contents["title"]
                self.field_match_pairs = match_fields([field_name],method,{field_name:infer_json_type(schema_model.contents)})
                match_name = self.field_match_pairs[field_name]
            else:
                field_name = ""
                match_name = ""
                self.field_match_pairs = {}
            
            
            for x in range(amount):
                synthesised_data = self.generate_synth_data(field_name,match_name,constraints,f"{field_name}(?)[{amount}]")
                if performance == False or x < 10:  #validate 10 to confirm, then skip the rest if performance is active
                    validate_synthesised_data(synthesised_data,schema_model)
                dataset.append(synthesised_data)
            return dataset
        else:
            schema1 = schema_model.contents
            klass1 = validator_for(schema1)
            klass1.check_schema(schema1)
            instance1 = klass1(schema1)
            schema2 = schema_model.sanitised_contents
            klass2 = validator_for(schema2)
            klass2.check_schema(schema2)
            instance2 = klass1(schema2)
            self.field_match_pairs = self.recursive_match_fields(schema_model,method)
            self.applied_constraints = self.recursive_get_applied_constraints(schema_model)
            # print(self.applied_constraints)
            dataset = []
            for x in range(amount):
                synthesised_data = self.synthesise_recursive(
                    schema_model, method=method, amount=amount
                )
                if x < 10:  #validate 10 to confirm, then skip the rest
                    validate_synthesised_data(synthesised_data,schema_model,instances=(instance1,instance2))
                dataset.append(synthesised_data)
                if self.stdcout:
                    if (x + 1) % max(1, amount // 100) == 0:  # 1% at a time
                        self.print(
                            f"Completed: {x + 1}/{amount} | {round(((x + 1) / amount) * 100, 2)}%{' ' * 30}",
                            end="\r",
                        )
            self.print("\nValidating data")
            if performance == False:
                for x,synthesised_data in enumerate(dataset):
                    validate_synthesised_data(synthesised_data,schema_model,instances=(instance1,instance2))
                    if (x + 1) % max(1, amount // 100) == 0:  # 1% at a time
                        self.print(
                            f"Completed: {x + 1}/{amount} | {round(((x + 1) / amount) * 100, 2)}%{' ' * 30}",
                            end="\r",
                        )
                           
            if self.stdcout:
                self.print(f"Completed: {amount}/{amount}{' ' * 30}")
            # lp.print_stats()
            return dataset
    # ----- Central called functions -----

    def register_schema(self, schema_model:Union[JsonSchemaClass,Dict], method=None, amount=1, seed="random",stdcout=False):
        if amount == 0:
            return []
        if isinstance(schema_model,dict):
            if "title" not in schema_model:
                raise Exception("JSON schema must have a title")
            schema_model = JsonSchemaClass(schema_model)
        schema_model = load_parse_json_schema(schema_model)
        if stdcout:
            self.stdcout = stdcout
        self.yield_schema = schema_model

        self.defs = schema_model.defs
        self.outputpooling.clear()
        self.applied_constraints_cache.clear()
        self.schema_keys_cache.clear()
        if method != None:
            self.method = method
        else:
            method = self.method
        if schema_model.contents["type"] != "object":

            constraints = check_generation_constraints("",schema_model.contents)
            if "title" in schema_model.contents:
                field_name = schema_model.contents["title"]
                self.field_match_pairs = match_fields([field_name],method,{field_name:infer_json_type(schema_model.contents)})
                match_name = self.field_match_pairs[field_name]
            else:
                field_name = ""
                match_name = ""
                self.field_match_pairs = {}
            self.yield_schema_data = {"constraints":constraints,"field_match_pairs":{"name":field_name,"match":match_name}}
        else:
            self.field_match_pairs = self.recursive_match_fields(schema_model,method)
            self.applied_constraints = self.recursive_get_applied_constraints(schema_model)
            self.yield_schema_data = {"constraints":self.applied_constraints,"field_match_pairs":self.field_match_pairs}

    def yield_instance(self,amount=1,seed="random",stdcout=False, performance=False):
        prevcout = self.stdcout
        # prevseed = self.seed
        if stdcout:
            self.stdcout = stdcout
        schema_model = self.yield_schema
        yield_schema_data = self.yield_schema_data
        method = self.method
        self.PERFORMANCE = performance
        if schema_model.contents["type"] != "object": 
            field_name = yield_schema_data["field_match_pairs"]["name"]
            match_name = yield_schema_data["field_match_pairs"]["match"]
            constraints = yield_schema_data["constraints"]
            dataset = []
            for x in range(amount):
                synthesised_data = self.generate_synth_data(field_name,match_name,constraints,f"{field_name}(?)[{amount}]")
                if performance == False or x < 10:  #validate 10 to confirm, then skip the rest if performance is active
                    validate_synthesised_data(synthesised_data,schema_model)
                dataset.append(synthesised_data)
        else:
            
            dataset = []
            for x in range(amount):
                synthesised_data = self.synthesise_recursive(
                    schema_model, method=method, amount=amount
                )
                dataset.append(synthesised_data)
                if self.stdcout:
                    if (x + 1) % max(1, amount // 100) == 0:  # 1% at a time
                        self.print(
                            f"Completed: {x + 1}/{amount}:{round(((x + 1) / amount) * 100, 2)}%{' ' * 30}",
                            end="\r",
                        )
            if self.stdcout:
                self.print(f"Completed: {amount}/{amount}{' ' * 30}")
        self.stdcout = prevcout
        # self.seed = prevseed
        return dataset


